package com.fis.esme.scheduleraction;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.1
 * 2014-10-02T14:56:06.789+07:00
 * Generated source version: 2.4.1
 * 
 */
@WebService(targetNamespace = "http://scheduleraction.esme.fis.com/", name = "SchedulerActionTransferer")
@XmlSeeAlso({ObjectFactory.class})
public interface SchedulerActionTransferer {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "count", targetNamespace = "http://scheduleraction.esme.fis.com/", className = "com.fis.esme.scheduleraction.Count")
    @WebMethod
    @ResponseWrapper(localName = "countResponse", targetNamespace = "http://scheduleraction.esme.fis.com/", className = "com.fis.esme.scheduleraction.CountResponse")
    public int count(
        @WebParam(name = "arg0", targetNamespace = "")
        com.fis.esme.persistence.EsmeSchedulerAction arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        boolean arg1
    );

    @RequestWrapper(localName = "update", targetNamespace = "http://scheduleraction.esme.fis.com/", className = "com.fis.esme.scheduleraction.Update")
    @WebMethod
    @ResponseWrapper(localName = "updateResponse", targetNamespace = "http://scheduleraction.esme.fis.com/", className = "com.fis.esme.scheduleraction.UpdateResponse")
    public void update(
        @WebParam(name = "arg0", targetNamespace = "")
        com.fis.esme.persistence.EsmeSchedulerAction arg0
    ) throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://scheduleraction.esme.fis.com/", className = "com.fis.esme.scheduleraction.Add")
    @WebMethod
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://scheduleraction.esme.fis.com/", className = "com.fis.esme.scheduleraction.AddResponse")
    public java.lang.Long add(
        @WebParam(name = "arg0", targetNamespace = "")
        com.fis.esme.persistence.EsmeSchedulerAction arg0
    ) throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "checkConstraints", targetNamespace = "http://scheduleraction.esme.fis.com/", className = "com.fis.esme.scheduleraction.CheckConstraints")
    @WebMethod
    @ResponseWrapper(localName = "checkConstraintsResponse", targetNamespace = "http://scheduleraction.esme.fis.com/", className = "com.fis.esme.scheduleraction.CheckConstraintsResponse")
    public boolean checkConstraints(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Long arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findAllWithoutParameter", targetNamespace = "http://scheduleraction.esme.fis.com/", className = "com.fis.esme.scheduleraction.FindAllWithoutParameter")
    @WebMethod
    @ResponseWrapper(localName = "findAllWithoutParameterResponse", targetNamespace = "http://scheduleraction.esme.fis.com/", className = "com.fis.esme.scheduleraction.FindAllWithoutParameterResponse")
    public java.util.List<com.fis.esme.persistence.EsmeSchedulerAction> findAllWithoutParameter() throws Exception_Exception;

    @RequestWrapper(localName = "delete", targetNamespace = "http://scheduleraction.esme.fis.com/", className = "com.fis.esme.scheduleraction.Delete")
    @WebMethod
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://scheduleraction.esme.fis.com/", className = "com.fis.esme.scheduleraction.DeleteResponse")
    public void delete(
        @WebParam(name = "arg0", targetNamespace = "")
        com.fis.esme.persistence.EsmeSchedulerAction arg0
    ) throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findAllWithOrderPaging", targetNamespace = "http://scheduleraction.esme.fis.com/", className = "com.fis.esme.scheduleraction.FindAllWithOrderPaging")
    @WebMethod
    @ResponseWrapper(localName = "findAllWithOrderPagingResponse", targetNamespace = "http://scheduleraction.esme.fis.com/", className = "com.fis.esme.scheduleraction.FindAllWithOrderPagingResponse")
    public java.util.List<com.fis.esme.persistence.EsmeSchedulerAction> findAllWithOrderPaging(
        @WebParam(name = "arg0", targetNamespace = "")
        com.fis.esme.persistence.EsmeSchedulerAction arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        boolean arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        int arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        int arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        boolean arg5
    ) throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "checkExisted", targetNamespace = "http://scheduleraction.esme.fis.com/", className = "com.fis.esme.scheduleraction.CheckExisted")
    @WebMethod
    @ResponseWrapper(localName = "checkExistedResponse", targetNamespace = "http://scheduleraction.esme.fis.com/", className = "com.fis.esme.scheduleraction.CheckExistedResponse")
    public int checkExisted(
        @WebParam(name = "arg0", targetNamespace = "")
        com.fis.esme.persistence.EsmeSchedulerAction arg0
    );
}
