
package com.fis.esme.scheduleraction;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.1
 * 2014-10-02T14:56:06.553+07:00
 * Generated source version: 2.4.1
 * 
 */
public final class SchedulerActionTransferer_SchedulerActionTransfererPort_Client {

    private static final QName SERVICE_NAME = new QName("http://scheduleraction.esme.fis.com/", "SchedulerActionTransfererService");

    private SchedulerActionTransferer_SchedulerActionTransfererPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = SchedulerActionTransfererService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        SchedulerActionTransfererService ss = new SchedulerActionTransfererService(wsdlURL, SERVICE_NAME);
        SchedulerActionTransferer port = ss.getSchedulerActionTransfererPort();  
        

        System.exit(0);
    }

}
