package com.fis.esme.scheduleraction;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.1
 * 2014-10-02T14:56:06.803+07:00
 * Generated source version: 2.4.1
 * 
 */
@WebServiceClient(name = "SchedulerActionTransfererService", 
                  wsdlLocation = "http://localhost:7080/ESME_Business/services/SchedulerActionTransfererPort?wsdl",
                  targetNamespace = "http://scheduleraction.esme.fis.com/") 
public class SchedulerActionTransfererService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://scheduleraction.esme.fis.com/", "SchedulerActionTransfererService");
    public final static QName SchedulerActionTransfererPort = new QName("http://scheduleraction.esme.fis.com/", "SchedulerActionTransfererPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:7080/ESME_Business/services/SchedulerActionTransfererPort?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SchedulerActionTransfererService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:7080/ESME_Business/services/SchedulerActionTransfererPort?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SchedulerActionTransfererService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SchedulerActionTransfererService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SchedulerActionTransfererService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns SchedulerActionTransferer
     */
    @WebEndpoint(name = "SchedulerActionTransfererPort")
    public SchedulerActionTransferer getSchedulerActionTransfererPort() {
        return super.getPort(SchedulerActionTransfererPort, SchedulerActionTransferer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SchedulerActionTransferer
     */
    @WebEndpoint(name = "SchedulerActionTransfererPort")
    public SchedulerActionTransferer getSchedulerActionTransfererPort(WebServiceFeature... features) {
        return super.getPort(SchedulerActionTransfererPort, SchedulerActionTransferer.class, features);
    }

}
