package com.fis.esme.subscriberdt;

/**
 * Please modify this class to meet your needs This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.4.1 2014-10-16T12:22:46.298+07:00 Generated source version: 2.4.1
 * 
 */
public final class SubscriberDTTransferer_SubscriberDTTransfererPort_Client {

	private static final QName SERVICE_NAME = new QName("http://subscriberdt.esme.fis.com/", "SubscriberDTTransfererService");

	private SubscriberDTTransferer_SubscriberDTTransfererPort_Client() {

	}

	public static void main(String args[]) throws java.lang.Exception {

		URL wsdlURL = SubscriberDTTransfererService.WSDL_LOCATION;
		if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
			File wsdlFile = new File(args[0]);
			try {
				if (wsdlFile.exists()) {
					wsdlURL = wsdlFile.toURI().toURL();
				} else {
					wsdlURL = new URL(args[0]);
				}
			} catch (MalformedURLException e) {
				e.printStackTrace();
			}
		}

		SubscriberDTTransfererService ss = new SubscriberDTTransfererService(wsdlURL, SERVICE_NAME);
		SubscriberDTTransferer port = ss.getSubscriberDTTransfererPort();

		// {
		// System.out.println("Invoking update...");
		// com.fis.esme.subscriberdt.Subscriber _update_arg0 = new com.fis.esme.subscriberdt.Subscriber();
		// _update_arg0.setAddress("Address-1800696047");
		// _update_arg0.setBirthDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-10-16T12:22:46.364+07:00"));
		// _update_arg0.setCreateDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-10-16T12:22:46.366+07:00"));
		// _update_arg0.setEmail("Email-1783988259");
		// _update_arg0.setMsisdn("Msisdn1166361091");
		// _update_arg0.setSex("Sex-758049310");
		// _update_arg0.setStatus("Status-734330578");
		// java.util.List<java.lang.Object> _update_arg0SubGroups = new java.util.ArrayList<java.lang.Object>();
		// java.lang.Object _update_arg0SubGroupsVal1 = null;
		// _update_arg0SubGroups.add(_update_arg0SubGroupsVal1);
		// _update_arg0.getSubGroups().addAll(_update_arg0SubGroups);
		// _update_arg0.setSubId(-4423504278621701718l);
		// long _update_arg1 = -7375703007482556452l;
		// try {
		// port.update(_update_arg0, _update_arg1);
		//
		// } catch (Exception_Exception e) {
		// System.out.println("Expected exception: Exception has occurred.");
		// System.out.println(e.toString());
		// }
		// }
		// {
		// System.out.println("Invoking count...");
		// com.fis.esme.subscriberdt.SearchEntity _count_arg0 = new com.fis.esme.subscriberdt.SearchEntity();
		// _count_arg0.setAccountId(Long.valueOf(-8890138193847119091l));
		// _count_arg0.setFromDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-10-16T12:22:46.392+07:00"));
		// _count_arg0.setKey("Key1847502769");
		// java.util.List<java.lang.Integer> _count_arg0ListInteger = new java.util.ArrayList<java.lang.Integer>();
		// java.lang.Integer _count_arg0ListIntegerVal1 = Integer.valueOf(-1875997274);
		// _count_arg0ListInteger.add(_count_arg0ListIntegerVal1);
		// _count_arg0.getListInteger().addAll(_count_arg0ListInteger);
		// java.util.List<java.lang.Long> _count_arg0ListLong = new java.util.ArrayList<java.lang.Long>();
		// java.lang.Long _count_arg0ListLongVal1 = Long.valueOf(-3008880683581192425l);
		// _count_arg0ListLong.add(_count_arg0ListLongVal1);
		// _count_arg0.getListLong().addAll(_count_arg0ListLong);
		// java.util.List<java.lang.String> _count_arg0ListString = new java.util.ArrayList<java.lang.String>();
		// java.lang.String _count_arg0ListStringVal1 = "_count_arg0ListStringVal-625429150";
		// _count_arg0ListString.add(_count_arg0ListStringVal1);
		// _count_arg0.getListString().addAll(_count_arg0ListString);
		// _count_arg0.setMsisdn("Msisdn1043064759");
		// _count_arg0.setOnoff(Boolean.valueOf(false));
		// _count_arg0.setRoleId(Integer.valueOf(-455500765));
		// _count_arg0.setSubId(Long.valueOf(8340975125131814101l));
		// _count_arg0.setSubcType("SubcType-867708610");
		// _count_arg0.setSwitchCase("SwitchCase821592090");
		// _count_arg0.setToDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-10-16T12:22:46.394+07:00"));
		// _count_arg0.setValues("Values968042740");
		// com.fis.esme.subscriberdt.Subscriber _count_arg1 = new com.fis.esme.subscriberdt.Subscriber();
		// _count_arg1.setAddress("Address-1794203762");
		// _count_arg1.setBirthDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-10-16T12:22:46.395+07:00"));
		// _count_arg1.setCreateDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-10-16T12:22:46.395+07:00"));
		// _count_arg1.setEmail("Email-887247534");
		// _count_arg1.setMsisdn("Msisdn-938053697");
		// _count_arg1.setSex("Sex-1270785728");
		// _count_arg1.setStatus("Status1755705264");
		// java.util.List<java.lang.Object> _count_arg1SubGroups = new java.util.ArrayList<java.lang.Object>();
		// java.lang.Object _count_arg1SubGroupsVal1 = null;
		// _count_arg1SubGroups.add(_count_arg1SubGroupsVal1);
		// _count_arg1.getSubGroups().addAll(_count_arg1SubGroups);
		// _count_arg1.setSubId(6769909750731145033l);
		// boolean _count_arg2 = false;
		// int _count__return = port.count(_count_arg0, _count_arg1, _count_arg2);
		// System.out.println("count.result=" + _count__return);
		//
		//
		// }
		// {
		// System.out.println("Invoking subscriberDTTransferer...");
		// port.subscriberDTTransferer();
		//
		//
		// }
		// {
		// System.out.println("Invoking delete...");
		// com.fis.esme.subscriberdt.Subscriber _delete_arg0 = new com.fis.esme.subscriberdt.Subscriber();
		// _delete_arg0.setAddress("Address733394685");
		// _delete_arg0.setBirthDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-10-16T12:22:46.398+07:00"));
		// _delete_arg0.setCreateDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-10-16T12:22:46.398+07:00"));
		// _delete_arg0.setEmail("Email-1190819938");
		// _delete_arg0.setMsisdn("Msisdn-294234063");
		// _delete_arg0.setSex("Sex1841796874");
		// _delete_arg0.setStatus("Status-1132215009");
		// java.util.List<java.lang.Object> _delete_arg0SubGroups = new java.util.ArrayList<java.lang.Object>();
		// java.lang.Object _delete_arg0SubGroupsVal1 = null;
		// _delete_arg0SubGroups.add(_delete_arg0SubGroupsVal1);
		// _delete_arg0.getSubGroups().addAll(_delete_arg0SubGroups);
		// _delete_arg0.setSubId(4373209841763565645l);
		// long _delete_arg1 = -7984233904762353959l;
		// try {
		// port.delete(_delete_arg0, _delete_arg1);
		//
		// } catch (Exception_Exception e) {
		// System.out.println("Expected exception: Exception has occurred.");
		// System.out.println(e.toString());
		// }
		// }
		// {
		// System.out.println("Invoking checkExisted...");
		// com.fis.esme.subscriberdt.Subscriber _checkExisted_arg0 = new com.fis.esme.subscriberdt.Subscriber();
		// _checkExisted_arg0.setAddress("Address1176815104");
		// _checkExisted_arg0.setBirthDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-10-16T12:22:46.400+07:00"));
		// _checkExisted_arg0.setCreateDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-10-16T12:22:46.401+07:00"));
		// _checkExisted_arg0.setEmail("Email102759966");
		// _checkExisted_arg0.setMsisdn("Msisdn-35380872");
		// _checkExisted_arg0.setSex("Sex1270936703");
		// _checkExisted_arg0.setStatus("Status-2039073325");
		// java.util.List<java.lang.Object> _checkExisted_arg0SubGroups = new java.util.ArrayList<java.lang.Object>();
		// java.lang.Object _checkExisted_arg0SubGroupsVal1 = null;
		// _checkExisted_arg0SubGroups.add(_checkExisted_arg0SubGroupsVal1);
		// _checkExisted_arg0.getSubGroups().addAll(_checkExisted_arg0SubGroups);
		// _checkExisted_arg0.setSubId(-6056727537226870126l);
		// int _checkExisted__return = port.checkExisted(_checkExisted_arg0);
		// System.out.println("checkExisted.result=" + _checkExisted__return);
		//
		//
		// }
		// {
		// System.out.println("Invoking add...");
		// com.fis.esme.subscriberdt.Subscriber _add_arg0 = new com.fis.esme.subscriberdt.Subscriber();
		// _add_arg0.setAddress("Address-392727640");
		// _add_arg0.setBirthDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-10-16T12:22:46.403+07:00"));
		// _add_arg0.setCreateDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-10-16T12:22:46.404+07:00"));
		// _add_arg0.setEmail("Email554936714");
		// _add_arg0.setMsisdn("Msisdn-2066555141");
		// _add_arg0.setSex("Sex417357370");
		// _add_arg0.setStatus("Status103456801");
		// java.util.List<java.lang.Object> _add_arg0SubGroups = new java.util.ArrayList<java.lang.Object>();
		// java.lang.Object _add_arg0SubGroupsVal1 = null;
		// _add_arg0SubGroups.add(_add_arg0SubGroupsVal1);
		// _add_arg0.getSubGroups().addAll(_add_arg0SubGroups);
		// _add_arg0.setSubId(5729547455069389538l);
		// long _add_arg1 = 2347611117696331812l;
		// try {
		// java.lang.Long _add__return = port.add(_add_arg0, _add_arg1);
		// System.out.println("add.result=" + _add__return);
		//
		// } catch (Exception_Exception e) {
		// System.out.println("Expected exception: Exception has occurred.");
		// System.out.println(e.toString());
		// }
		// }
		// {
		// System.out.println("Invoking findAllWithOrderPaging...");
		// com.fis.esme.subscriberdt.SearchEntity _findAllWithOrderPaging_arg0 = new com.fis.esme.subscriberdt.SearchEntity();
		// _findAllWithOrderPaging_arg0.setAccountId(Long.valueOf(386033528704701334l));
		// _findAllWithOrderPaging_arg0.setFromDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-10-16T12:22:46.406+07:00"));
		// _findAllWithOrderPaging_arg0.setKey("Key160026051");
		// java.util.List<java.lang.Integer> _findAllWithOrderPaging_arg0ListInteger = new java.util.ArrayList<java.lang.Integer>();
		// java.lang.Integer _findAllWithOrderPaging_arg0ListIntegerVal1 = Integer.valueOf(1183410120);
		// _findAllWithOrderPaging_arg0ListInteger.add(_findAllWithOrderPaging_arg0ListIntegerVal1);
		// _findAllWithOrderPaging_arg0.getListInteger().addAll(_findAllWithOrderPaging_arg0ListInteger);
		// java.util.List<java.lang.Long> _findAllWithOrderPaging_arg0ListLong = new java.util.ArrayList<java.lang.Long>();
		// java.lang.Long _findAllWithOrderPaging_arg0ListLongVal1 = Long.valueOf(7697394315524469673l);
		// _findAllWithOrderPaging_arg0ListLong.add(_findAllWithOrderPaging_arg0ListLongVal1);
		// _findAllWithOrderPaging_arg0.getListLong().addAll(_findAllWithOrderPaging_arg0ListLong);
		// java.util.List<java.lang.String> _findAllWithOrderPaging_arg0ListString = new java.util.ArrayList<java.lang.String>();
		// java.lang.String _findAllWithOrderPaging_arg0ListStringVal1 = "_findAllWithOrderPaging_arg0ListStringVal-300088833";
		// _findAllWithOrderPaging_arg0ListString.add(_findAllWithOrderPaging_arg0ListStringVal1);
		// _findAllWithOrderPaging_arg0.getListString().addAll(_findAllWithOrderPaging_arg0ListString);
		// _findAllWithOrderPaging_arg0.setMsisdn("Msisdn455659451");
		// _findAllWithOrderPaging_arg0.setOnoff(Boolean.valueOf(false));
		// _findAllWithOrderPaging_arg0.setRoleId(Integer.valueOf(-1275697522));
		// _findAllWithOrderPaging_arg0.setSubId(Long.valueOf(2929907983192171311l));
		// _findAllWithOrderPaging_arg0.setSubcType("SubcType-1061353969");
		// _findAllWithOrderPaging_arg0.setSwitchCase("SwitchCase-1920552524");
		// _findAllWithOrderPaging_arg0.setToDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-10-16T12:22:46.407+07:00"));
		// _findAllWithOrderPaging_arg0.setValues("Values-1933570822");
		// com.fis.esme.subscriberdt.Subscriber _findAllWithOrderPaging_arg1 = new com.fis.esme.subscriberdt.Subscriber();
		// _findAllWithOrderPaging_arg1.setAddress("Address1395042578");
		// _findAllWithOrderPaging_arg1.setBirthDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-10-16T12:22:46.408+07:00"));
		// _findAllWithOrderPaging_arg1.setCreateDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-10-16T12:22:46.409+07:00"));
		// _findAllWithOrderPaging_arg1.setEmail("Email-1425748243");
		// _findAllWithOrderPaging_arg1.setMsisdn("Msisdn-2120729898");
		// _findAllWithOrderPaging_arg1.setSex("Sex-1349036086");
		// _findAllWithOrderPaging_arg1.setStatus("Status-367563647");
		// java.util.List<java.lang.Object> _findAllWithOrderPaging_arg1SubGroups = new java.util.ArrayList<java.lang.Object>();
		// java.lang.Object _findAllWithOrderPaging_arg1SubGroupsVal1 = null;
		// _findAllWithOrderPaging_arg1SubGroups.add(_findAllWithOrderPaging_arg1SubGroupsVal1);
		// _findAllWithOrderPaging_arg1.getSubGroups().addAll(_findAllWithOrderPaging_arg1SubGroups);
		// _findAllWithOrderPaging_arg1.setSubId(3572434157829961617l);
		// java.lang.String _findAllWithOrderPaging_arg2 = "_findAllWithOrderPaging_arg2146469084";
		// boolean _findAllWithOrderPaging_arg3 = false;
		// int _findAllWithOrderPaging_arg4 = 807906334;
		// int _findAllWithOrderPaging_arg5 = -167394762;
		// boolean _findAllWithOrderPaging_arg6 = false;
		// try {
		// java.util.List<com.fis.esme.subscriberdt.Subscriber> _findAllWithOrderPaging__return = port.findAllWithOrderPaging(_findAllWithOrderPaging_arg0, _findAllWithOrderPaging_arg1,
		// _findAllWithOrderPaging_arg2, _findAllWithOrderPaging_arg3, _findAllWithOrderPaging_arg4, _findAllWithOrderPaging_arg5, _findAllWithOrderPaging_arg6);
		// System.out.println("findAllWithOrderPaging.result=" + _findAllWithOrderPaging__return);
		//
		// } catch (Exception_Exception e) {
		// System.out.println("Expected exception: Exception has occurred.");
		// System.out.println(e.toString());
		// }
		// }
		// {
		// System.out.println("Invoking findAllWithoutParameter...");
		// try {
		// java.util.List<com.fis.esme.subscriberdt.Subscriber> _findAllWithoutParameter__return = port.findAllWithoutParameter();
		// System.out.println("findAllWithoutParameter.result=" + _findAllWithoutParameter__return);
		//
		// } catch (Exception_Exception e) {
		// System.out.println("Expected exception: Exception has occurred.");
		// System.out.println(e.toString());
		// }
		// }
		// {
		// System.out.println("Invoking findGroupsBySub...");
		// long _findGroupsBySub_arg0 = 5512400305552087969l;
		// try {
		// java.util.List<com.fis.esme.subscriberdt.Groups> _findGroupsBySub__return = port.findGroupsBySub(_findGroupsBySub_arg0);
		// System.out.println("findGroupsBySub.result=" + _findGroupsBySub__return);
		//
		// } catch (Exception_Exception e) {
		// System.out.println("Expected exception: Exception has occurred.");
		// System.out.println(e.toString());
		// }
		// }

		System.exit(0);
	}

}
