package com.fis.esme.subscriberdt;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.1
 * 2014-10-16T17:13:06.358+07:00
 * Generated source version: 2.4.1
 * 
 */
@WebServiceClient(name = "SubscriberDTTransfererService", 
                  wsdlLocation = "http://localhost:7080/ESME_Business/services/SubscriberDTTransfererPort?wsdl",
                  targetNamespace = "http://subscriberdt.esme.fis.com/") 
public class SubscriberDTTransfererService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://subscriberdt.esme.fis.com/", "SubscriberDTTransfererService");
    public final static QName SubscriberDTTransfererPort = new QName("http://subscriberdt.esme.fis.com/", "SubscriberDTTransfererPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:7080/ESME_Business/services/SubscriberDTTransfererPort?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SubscriberDTTransfererService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:7080/ESME_Business/services/SubscriberDTTransfererPort?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SubscriberDTTransfererService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SubscriberDTTransfererService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SubscriberDTTransfererService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SubscriberDTTransfererService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SubscriberDTTransfererService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SubscriberDTTransfererService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns SubscriberDTTransferer
     */
    @WebEndpoint(name = "SubscriberDTTransfererPort")
    public SubscriberDTTransferer getSubscriberDTTransfererPort() {
        return super.getPort(SubscriberDTTransfererPort, SubscriberDTTransferer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SubscriberDTTransferer
     */
    @WebEndpoint(name = "SubscriberDTTransfererPort")
    public SubscriberDTTransferer getSubscriberDTTransfererPort(WebServiceFeature... features) {
        return super.getPort(SubscriberDTTransfererPort, SubscriberDTTransferer.class, features);
    }

}
