package com.fis.esme.subscriberdt;

/**
 * Please modify this class to meet your needs This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.4.1 2014-10-16T17:13:06.213+07:00 Generated source version: 2.4.1
 * 
 */
public final class SubscriberDTTransferer_SubscriberDTTransfererPort_Client {

	private static final QName SERVICE_NAME = new QName("http://subscriberdt.esme.fis.com/", "SubscriberDTTransfererService");

	private SubscriberDTTransferer_SubscriberDTTransfererPort_Client() {

	}

	public static void main(String args[]) throws java.lang.Exception {

		URL wsdlURL = SubscriberDTTransfererService.WSDL_LOCATION;
		if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
			File wsdlFile = new File(args[0]);
			try {
				if (wsdlFile.exists()) {
					wsdlURL = wsdlFile.toURI().toURL();
				} else {
					wsdlURL = new URL(args[0]);
				}
			} catch (MalformedURLException e) {
				e.printStackTrace();
			}
		}

		SubscriberDTTransfererService ss = new SubscriberDTTransfererService(wsdlURL, SERVICE_NAME);
		SubscriberDTTransferer port = ss.getSubscriberDTTransfererPort();

		// {
		// System.out.println("Invoking findSubcribersByGroup...");
		// long _findSubcribersByGroup_arg0 = 492378185754939325l;
		// try {
		// java.util.List<com.fis.esme.subscriberdt.Subscriber> _findSubcribersByGroup__return = port.findSubcribersByGroup(_findSubcribersByGroup_arg0);
		// System.out.println("findSubcribersByGroup.result=" + _findSubcribersByGroup__return);
		//
		// } catch (Exception_Exception e) {
		// System.out.println("Expected exception: Exception has occurred.");
		// System.out.println(e.toString());
		// }
		// }
		// {
		// System.out.println("Invoking update...");
		// com.fis.esme.subscriberdt.Subscriber _update_arg0 = new com.fis.esme.subscriberdt.Subscriber();
		// _update_arg0.setAddress("Address-333020575");
		// _update_arg0.setBirthDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-10-16T17:13:06.289+07:00"));
		// _update_arg0.setCreateDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-10-16T17:13:06.290+07:00"));
		// _update_arg0.setEmail("Email-2089676107");
		// _update_arg0.setMsisdn("Msisdn-1700363096");
		// _update_arg0.setSex("Sex-1937863754");
		// _update_arg0.setStatus("Status-512114666");
		// java.util.List<java.lang.Object> _update_arg0SubGroups = new java.util.ArrayList<java.lang.Object>();
		// java.lang.Object _update_arg0SubGroupsVal1 = null;
		// _update_arg0SubGroups.add(_update_arg0SubGroupsVal1);
		// _update_arg0.getSubGroups().addAll(_update_arg0SubGroups);
		// _update_arg0.setSubId(8607054413619292629l);
		// long _update_arg1 = -9146471887293387516l;
		// try {
		// port.update(_update_arg0, _update_arg1);
		//
		// } catch (Exception_Exception e) {
		// System.out.println("Expected exception: Exception has occurred.");
		// System.out.println(e.toString());
		// }
		// }
		// {
		// System.out.println("Invoking count...");
		// com.fis.esme.subscriberdt.SearchEntity _count_arg0 = new com.fis.esme.subscriberdt.SearchEntity();
		// _count_arg0.setAccountId(Long.valueOf(4359032513669482127l));
		// _count_arg0.setFromDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-10-16T17:13:06.293+07:00"));
		// _count_arg0.setKey("Key496455186");
		// java.util.List<java.lang.Integer> _count_arg0ListInteger = new java.util.ArrayList<java.lang.Integer>();
		// java.lang.Integer _count_arg0ListIntegerVal1 = Integer.valueOf(1159622702);
		// _count_arg0ListInteger.add(_count_arg0ListIntegerVal1);
		// _count_arg0.getListInteger().addAll(_count_arg0ListInteger);
		// java.util.List<java.lang.Long> _count_arg0ListLong = new java.util.ArrayList<java.lang.Long>();
		// java.lang.Long _count_arg0ListLongVal1 = Long.valueOf(8889004777728472734l);
		// _count_arg0ListLong.add(_count_arg0ListLongVal1);
		// _count_arg0.getListLong().addAll(_count_arg0ListLong);
		// java.util.List<java.lang.String> _count_arg0ListString = new java.util.ArrayList<java.lang.String>();
		// java.lang.String _count_arg0ListStringVal1 = "_count_arg0ListStringVal-952601572";
		// _count_arg0ListString.add(_count_arg0ListStringVal1);
		// _count_arg0.getListString().addAll(_count_arg0ListString);
		// _count_arg0.setMsisdn("Msisdn657512320");
		// _count_arg0.setOnoff(Boolean.valueOf(false));
		// _count_arg0.setRoleId(Integer.valueOf(707878289));
		// _count_arg0.setSubId(Long.valueOf(-8524728471260858863l));
		// _count_arg0.setSubcType("SubcType-980855852");
		// _count_arg0.setSwitchCase("SwitchCase193919129");
		// _count_arg0.setToDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-10-16T17:13:06.294+07:00"));
		// _count_arg0.setValues("Values-402888929");
		// com.fis.esme.subscriberdt.Subscriber _count_arg1 = new com.fis.esme.subscriberdt.Subscriber();
		// _count_arg1.setAddress("Address13443752");
		// _count_arg1.setBirthDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-10-16T17:13:06.295+07:00"));
		// _count_arg1.setCreateDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-10-16T17:13:06.295+07:00"));
		// _count_arg1.setEmail("Email1808415405");
		// _count_arg1.setMsisdn("Msisdn-264459596");
		// _count_arg1.setSex("Sex-2046808134");
		// _count_arg1.setStatus("Status1594546817");
		// java.util.List<java.lang.Object> _count_arg1SubGroups = new java.util.ArrayList<java.lang.Object>();
		// java.lang.Object _count_arg1SubGroupsVal1 = null;
		// _count_arg1SubGroups.add(_count_arg1SubGroupsVal1);
		// _count_arg1.getSubGroups().addAll(_count_arg1SubGroups);
		// _count_arg1.setSubId(2536555128999978765l);
		// boolean _count_arg2 = false;
		// int _count__return = port.count(_count_arg0, _count_arg1, _count_arg2);
		// System.out.println("count.result=" + _count__return);
		//
		//
		// }
		// {
		// System.out.println("Invoking subscriberDTTransferer...");
		// port.subscriberDTTransferer();
		//
		//
		// }
		// {
		// System.out.println("Invoking delete...");
		// com.fis.esme.subscriberdt.Subscriber _delete_arg0 = new com.fis.esme.subscriberdt.Subscriber();
		// _delete_arg0.setAddress("Address1648381009");
		// _delete_arg0.setBirthDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-10-16T17:13:06.297+07:00"));
		// _delete_arg0.setCreateDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-10-16T17:13:06.297+07:00"));
		// _delete_arg0.setEmail("Email-1671337884");
		// _delete_arg0.setMsisdn("Msisdn-1691574878");
		// _delete_arg0.setSex("Sex-1805384813");
		// _delete_arg0.setStatus("Status-1362456698");
		// java.util.List<java.lang.Object> _delete_arg0SubGroups = new java.util.ArrayList<java.lang.Object>();
		// java.lang.Object _delete_arg0SubGroupsVal1 = null;
		// _delete_arg0SubGroups.add(_delete_arg0SubGroupsVal1);
		// _delete_arg0.getSubGroups().addAll(_delete_arg0SubGroups);
		// _delete_arg0.setSubId(-4576777190014874073l);
		// long _delete_arg1 = 7838442129972169682l;
		// try {
		// port.delete(_delete_arg0, _delete_arg1);
		//
		// } catch (Exception_Exception e) {
		// System.out.println("Expected exception: Exception has occurred.");
		// System.out.println(e.toString());
		// }
		// }
		// {
		// System.out.println("Invoking checkExisted...");
		// com.fis.esme.subscriberdt.Subscriber _checkExisted_arg0 = new com.fis.esme.subscriberdt.Subscriber();
		// _checkExisted_arg0.setAddress("Address-630691018");
		// _checkExisted_arg0.setBirthDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-10-16T17:13:06.300+07:00"));
		// _checkExisted_arg0.setCreateDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-10-16T17:13:06.301+07:00"));
		// _checkExisted_arg0.setEmail("Email22373674");
		// _checkExisted_arg0.setMsisdn("Msisdn512241324");
		// _checkExisted_arg0.setSex("Sex-1388522262");
		// _checkExisted_arg0.setStatus("Status-1670736410");
		// java.util.List<java.lang.Object> _checkExisted_arg0SubGroups = new java.util.ArrayList<java.lang.Object>();
		// java.lang.Object _checkExisted_arg0SubGroupsVal1 = null;
		// _checkExisted_arg0SubGroups.add(_checkExisted_arg0SubGroupsVal1);
		// _checkExisted_arg0.getSubGroups().addAll(_checkExisted_arg0SubGroups);
		// _checkExisted_arg0.setSubId(-6033900497931611214l);
		// int _checkExisted__return = port.checkExisted(_checkExisted_arg0);
		// System.out.println("checkExisted.result=" + _checkExisted__return);
		//
		//
		// }
		// {
		// System.out.println("Invoking add...");
		// com.fis.esme.subscriberdt.Subscriber _add_arg0 = new com.fis.esme.subscriberdt.Subscriber();
		// _add_arg0.setAddress("Address-696975734");
		// _add_arg0.setBirthDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-10-16T17:13:06.303+07:00"));
		// _add_arg0.setCreateDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-10-16T17:13:06.303+07:00"));
		// _add_arg0.setEmail("Email354676361");
		// _add_arg0.setMsisdn("Msisdn-699551811");
		// _add_arg0.setSex("Sex1699020894");
		// _add_arg0.setStatus("Status-1890865987");
		// java.util.List<java.lang.Object> _add_arg0SubGroups = new java.util.ArrayList<java.lang.Object>();
		// java.lang.Object _add_arg0SubGroupsVal1 = null;
		// _add_arg0SubGroups.add(_add_arg0SubGroupsVal1);
		// _add_arg0.getSubGroups().addAll(_add_arg0SubGroups);
		// _add_arg0.setSubId(2318597518698070640l);
		// long _add_arg1 = 265553270583256154l;
		// try {
		// java.lang.Long _add__return = port.add(_add_arg0, _add_arg1);
		// System.out.println("add.result=" + _add__return);
		//
		// } catch (Exception_Exception e) {
		// System.out.println("Expected exception: Exception has occurred.");
		// System.out.println(e.toString());
		// }
		// }
		// {
		// System.out.println("Invoking findAllWithOrderPaging...");
		// com.fis.esme.subscriberdt.SearchEntity _findAllWithOrderPaging_arg0 = new com.fis.esme.subscriberdt.SearchEntity();
		// _findAllWithOrderPaging_arg0.setAccountId(Long.valueOf(5627221320069118961l));
		// _findAllWithOrderPaging_arg0.setFromDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-10-16T17:13:06.305+07:00"));
		// _findAllWithOrderPaging_arg0.setKey("Key30293843");
		// java.util.List<java.lang.Integer> _findAllWithOrderPaging_arg0ListInteger = new java.util.ArrayList<java.lang.Integer>();
		// java.lang.Integer _findAllWithOrderPaging_arg0ListIntegerVal1 = Integer.valueOf(796418001);
		// _findAllWithOrderPaging_arg0ListInteger.add(_findAllWithOrderPaging_arg0ListIntegerVal1);
		// _findAllWithOrderPaging_arg0.getListInteger().addAll(_findAllWithOrderPaging_arg0ListInteger);
		// java.util.List<java.lang.Long> _findAllWithOrderPaging_arg0ListLong = new java.util.ArrayList<java.lang.Long>();
		// java.lang.Long _findAllWithOrderPaging_arg0ListLongVal1 = Long.valueOf(6097703266527485164l);
		// _findAllWithOrderPaging_arg0ListLong.add(_findAllWithOrderPaging_arg0ListLongVal1);
		// _findAllWithOrderPaging_arg0.getListLong().addAll(_findAllWithOrderPaging_arg0ListLong);
		// java.util.List<java.lang.String> _findAllWithOrderPaging_arg0ListString = new java.util.ArrayList<java.lang.String>();
		// java.lang.String _findAllWithOrderPaging_arg0ListStringVal1 = "_findAllWithOrderPaging_arg0ListStringVal-1347685852";
		// _findAllWithOrderPaging_arg0ListString.add(_findAllWithOrderPaging_arg0ListStringVal1);
		// _findAllWithOrderPaging_arg0.getListString().addAll(_findAllWithOrderPaging_arg0ListString);
		// _findAllWithOrderPaging_arg0.setMsisdn("Msisdn486927399");
		// _findAllWithOrderPaging_arg0.setOnoff(Boolean.valueOf(false));
		// _findAllWithOrderPaging_arg0.setRoleId(Integer.valueOf(711883010));
		// _findAllWithOrderPaging_arg0.setSubId(Long.valueOf(3126412989495513662l));
		// _findAllWithOrderPaging_arg0.setSubcType("SubcType-933005194");
		// _findAllWithOrderPaging_arg0.setSwitchCase("SwitchCase-622916697");
		// _findAllWithOrderPaging_arg0.setToDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-10-16T17:13:06.307+07:00"));
		// _findAllWithOrderPaging_arg0.setValues("Values999347481");
		// com.fis.esme.subscriberdt.Subscriber _findAllWithOrderPaging_arg1 = new com.fis.esme.subscriberdt.Subscriber();
		// _findAllWithOrderPaging_arg1.setAddress("Address-361525158");
		// _findAllWithOrderPaging_arg1.setBirthDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-10-16T17:13:06.307+07:00"));
		// _findAllWithOrderPaging_arg1.setCreateDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-10-16T17:13:06.308+07:00"));
		// _findAllWithOrderPaging_arg1.setEmail("Email-1141193315");
		// _findAllWithOrderPaging_arg1.setMsisdn("Msisdn-703334580");
		// _findAllWithOrderPaging_arg1.setSex("Sex-780448930");
		// _findAllWithOrderPaging_arg1.setStatus("Status-300521504");
		// java.util.List<java.lang.Object> _findAllWithOrderPaging_arg1SubGroups = new java.util.ArrayList<java.lang.Object>();
		// java.lang.Object _findAllWithOrderPaging_arg1SubGroupsVal1 = null;
		// _findAllWithOrderPaging_arg1SubGroups.add(_findAllWithOrderPaging_arg1SubGroupsVal1);
		// _findAllWithOrderPaging_arg1.getSubGroups().addAll(_findAllWithOrderPaging_arg1SubGroups);
		// _findAllWithOrderPaging_arg1.setSubId(8654421107327062719l);
		// java.lang.String _findAllWithOrderPaging_arg2 = "_findAllWithOrderPaging_arg2-1777338730";
		// boolean _findAllWithOrderPaging_arg3 = true;
		// int _findAllWithOrderPaging_arg4 = 950484618;
		// int _findAllWithOrderPaging_arg5 = -2086639406;
		// boolean _findAllWithOrderPaging_arg6 = true;
		// try {
		// java.util.List<com.fis.esme.subscriberdt.Subscriber> _findAllWithOrderPaging__return = port.findAllWithOrderPaging(_findAllWithOrderPaging_arg0, _findAllWithOrderPaging_arg1,
		// _findAllWithOrderPaging_arg2, _findAllWithOrderPaging_arg3, _findAllWithOrderPaging_arg4, _findAllWithOrderPaging_arg5, _findAllWithOrderPaging_arg6);
		// System.out.println("findAllWithOrderPaging.result=" + _findAllWithOrderPaging__return);
		//
		// } catch (Exception_Exception e) {
		// System.out.println("Expected exception: Exception has occurred.");
		// System.out.println(e.toString());
		// }
		// }
		// {
		// System.out.println("Invoking findAllWithoutParameter...");
		// try {
		// java.util.List<com.fis.esme.subscriberdt.Subscriber> _findAllWithoutParameter__return = port.findAllWithoutParameter();
		// System.out.println("findAllWithoutParameter.result=" + _findAllWithoutParameter__return);
		//
		// } catch (Exception_Exception e) {
		// System.out.println("Expected exception: Exception has occurred.");
		// System.out.println(e.toString());
		// }
		// }
		// {
		// System.out.println("Invoking findGroupsBySub...");
		// long _findGroupsBySub_arg0 = 9145747426223751648l;
		// try {
		// java.util.List<com.fis.esme.subscriberdt.Groups> _findGroupsBySub__return = port.findGroupsBySub(_findGroupsBySub_arg0);
		// System.out.println("findGroupsBySub.result=" + _findGroupsBySub__return);
		//
		// } catch (Exception_Exception e) {
		// System.out.println("Expected exception: Exception has occurred.");
		// System.out.println(e.toString());
		// }
		// }

		System.exit(0);
	}

}
