package com.fis.esme.shortcode;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.1
 * 2013-11-28T11:23:46.429+07:00
 * Generated source version: 2.4.1
 * 
 */
@WebService(targetNamespace = "http://shortcode.esme.fis.com/", name = "ShortCodeTransferer")
@XmlSeeAlso({ObjectFactory.class})
public interface ShortCodeTransferer {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "count", targetNamespace = "http://shortcode.esme.fis.com/", className = "com.fis.esme.shortcode.Count")
    @WebMethod
    @ResponseWrapper(localName = "countResponse", targetNamespace = "http://shortcode.esme.fis.com/", className = "com.fis.esme.shortcode.CountResponse")
    public int count(
        @WebParam(name = "arg0", targetNamespace = "")
        com.fis.esme.persistence.EsmeShortCode arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        boolean arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://shortcode.esme.fis.com/", className = "com.fis.esme.shortcode.Add")
    @WebMethod
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://shortcode.esme.fis.com/", className = "com.fis.esme.shortcode.AddResponse")
    public java.lang.Long add(
        @WebParam(name = "arg0", targetNamespace = "")
        com.fis.esme.persistence.EsmeShortCode arg0
    ) throws Exception_Exception;

    @RequestWrapper(localName = "delete", targetNamespace = "http://shortcode.esme.fis.com/", className = "com.fis.esme.shortcode.Delete")
    @WebMethod
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://shortcode.esme.fis.com/", className = "com.fis.esme.shortcode.DeleteResponse")
    public void delete(
        @WebParam(name = "arg0", targetNamespace = "")
        com.fis.esme.persistence.EsmeShortCode arg0
    ) throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "checkConstraints", targetNamespace = "http://shortcode.esme.fis.com/", className = "com.fis.esme.shortcode.CheckConstraints")
    @WebMethod
    @ResponseWrapper(localName = "checkConstraintsResponse", targetNamespace = "http://shortcode.esme.fis.com/", className = "com.fis.esme.shortcode.CheckConstraintsResponse")
    public boolean checkConstraints(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Long arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findAllWithoutParameter", targetNamespace = "http://shortcode.esme.fis.com/", className = "com.fis.esme.shortcode.FindAllWithoutParameter")
    @WebMethod
    @ResponseWrapper(localName = "findAllWithoutParameterResponse", targetNamespace = "http://shortcode.esme.fis.com/", className = "com.fis.esme.shortcode.FindAllWithoutParameterResponse")
    public java.util.List<com.fis.esme.persistence.EsmeShortCode> findAllWithoutParameter() throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findAllWithOrderPaging", targetNamespace = "http://shortcode.esme.fis.com/", className = "com.fis.esme.shortcode.FindAllWithOrderPaging")
    @WebMethod
    @ResponseWrapper(localName = "findAllWithOrderPagingResponse", targetNamespace = "http://shortcode.esme.fis.com/", className = "com.fis.esme.shortcode.FindAllWithOrderPagingResponse")
    public java.util.List<com.fis.esme.persistence.EsmeShortCode> findAllWithOrderPaging(
        @WebParam(name = "arg0", targetNamespace = "")
        com.fis.esme.persistence.EsmeShortCode arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        boolean arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        int arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        int arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        boolean arg5
    ) throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "checkExisted", targetNamespace = "http://shortcode.esme.fis.com/", className = "com.fis.esme.shortcode.CheckExisted")
    @WebMethod
    @ResponseWrapper(localName = "checkExistedResponse", targetNamespace = "http://shortcode.esme.fis.com/", className = "com.fis.esme.shortcode.CheckExistedResponse")
    public int checkExisted(
        @WebParam(name = "arg0", targetNamespace = "")
        com.fis.esme.persistence.EsmeShortCode arg0
    );

    @RequestWrapper(localName = "update", targetNamespace = "http://shortcode.esme.fis.com/", className = "com.fis.esme.shortcode.Update")
    @WebMethod
    @ResponseWrapper(localName = "updateResponse", targetNamespace = "http://shortcode.esme.fis.com/", className = "com.fis.esme.shortcode.UpdateResponse")
    public void update(
        @WebParam(name = "arg0", targetNamespace = "")
        com.fis.esme.persistence.EsmeShortCode arg0
    ) throws Exception_Exception;
}
