
package com.fis.esme.shortcode;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.1
 * 2013-11-28T11:23:46.313+07:00
 * Generated source version: 2.4.1
 * 
 */
public final class ShortCodeTransferer_ShortCodeTransfererPort_Client {

    private static final QName SERVICE_NAME = new QName("http://shortcode.esme.fis.com/", "ShortCodeTransfererService");

    private ShortCodeTransferer_ShortCodeTransfererPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ShortCodeTransfererService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ShortCodeTransfererService ss = new ShortCodeTransfererService(wsdlURL, SERVICE_NAME);
        ShortCodeTransferer port = ss.getShortCodeTransfererPort();  
        
        System.out.println("s>>>>>"+port.findAllWithoutParameter().size());
        
        System.exit(0);
    }

}
