package com.fis.esme.shortcode;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.1
 * 2013-11-28T11:23:46.441+07:00
 * Generated source version: 2.4.1
 * 
 */
@WebServiceClient(name = "ShortCodeTransfererService", 
                  wsdlLocation = "http://localhost:7080/ESME_Business/services/ShortCodeTransfererPort?wsdl",
                  targetNamespace = "http://shortcode.esme.fis.com/") 
public class ShortCodeTransfererService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://shortcode.esme.fis.com/", "ShortCodeTransfererService");
    public final static QName ShortCodeTransfererPort = new QName("http://shortcode.esme.fis.com/", "ShortCodeTransfererPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:7080/ESME_Business/services/ShortCodeTransfererPort?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ShortCodeTransfererService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:7080/ESME_Business/services/ShortCodeTransfererPort?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ShortCodeTransfererService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ShortCodeTransfererService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ShortCodeTransfererService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns ShortCodeTransferer
     */
    @WebEndpoint(name = "ShortCodeTransfererPort")
    public ShortCodeTransferer getShortCodeTransfererPort() {
        return super.getPort(ShortCodeTransfererPort, ShortCodeTransferer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ShortCodeTransferer
     */
    @WebEndpoint(name = "ShortCodeTransfererPort")
    public ShortCodeTransferer getShortCodeTransfererPort(WebServiceFeature... features) {
        return super.getPort(ShortCodeTransfererPort, ShortCodeTransferer.class, features);
    }

}
