
package com.fis.esme.commandsummary.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.4.1
 * Thu Dec 19 16:14:56 ICT 2013
 * Generated source version: 2.4.1
 */

@XmlRootElement(name = "findAllByDateAndId", namespace = "http://commandsummary.esme.fis.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "findAllByDateAndId", namespace = "http://commandsummary.esme.fis.com/", propOrder = {"arg0", "arg1", "arg2"})

public class FindAllByDateAndId {

    @XmlElement(name = "arg0")
    private java.lang.Long arg0;
    @XmlElement(name = "arg1")
    private java.util.Date arg1;
    @XmlElement(name = "arg2")
    private java.util.Date arg2;

    public java.lang.Long getArg0() {
        return this.arg0;
    }

    public void setArg0(java.lang.Long newArg0)  {
        this.arg0 = newArg0;
    }

    public java.util.Date getArg1() {
        return this.arg1;
    }

    public void setArg1(java.util.Date newArg1)  {
        this.arg1 = newArg1;
    }

    public java.util.Date getArg2() {
        return this.arg2;
    }

    public void setArg2(java.util.Date newArg2)  {
        this.arg2 = newArg2;
    }

}

