
package com.fis.esme.commandsummary.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.4.1
 * Thu Dec 19 16:14:56 ICT 2013
 * Generated source version: 2.4.1
 */

@XmlRootElement(name = "findAllByDateResponse", namespace = "http://commandsummary.esme.fis.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "findAllByDateResponse", namespace = "http://commandsummary.esme.fis.com/")

public class FindAllByDateResponse {

    @XmlElement(name = "return")
    private java.util.List<com.fis.esme.persistence.EsmeDailyCommandSummary> _return;

    public java.util.List<com.fis.esme.persistence.EsmeDailyCommandSummary> getReturn() {
        return this._return;
    }

    public void setReturn(java.util.List<com.fis.esme.persistence.EsmeDailyCommandSummary> new_return)  {
        this._return = new_return;
    }

}

