package com.fis.esme.isdnspecial;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.1
 * 2014-02-26T15:10:58.175+07:00
 * Generated source version: 2.4.1
 * 
 */
@WebServiceClient(name = "IsdnSpecialTransfererService", 
                  wsdlLocation = "file:/D:/FIS/ESME/ESME_Business/WebContent/wsdl/isdnspecialtransferer.wsdl",
                  targetNamespace = "http://isdnspecial.esme.fis.com/") 
public class IsdnSpecialTransfererService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://isdnspecial.esme.fis.com/", "IsdnSpecialTransfererService");
    public final static QName IsdnSpecialTransfererPort = new QName("http://isdnspecial.esme.fis.com/", "IsdnSpecialTransfererPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/FIS/ESME/ESME_Business/WebContent/wsdl/isdnspecialtransferer.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(IsdnSpecialTransfererService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/FIS/ESME/ESME_Business/WebContent/wsdl/isdnspecialtransferer.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public IsdnSpecialTransfererService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public IsdnSpecialTransfererService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IsdnSpecialTransfererService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns IsdnSpecialTransferer
     */
    @WebEndpoint(name = "IsdnSpecialTransfererPort")
    public IsdnSpecialTransferer getIsdnSpecialTransfererPort() {
        return super.getPort(IsdnSpecialTransfererPort, IsdnSpecialTransferer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IsdnSpecialTransferer
     */
    @WebEndpoint(name = "IsdnSpecialTransfererPort")
    public IsdnSpecialTransferer getIsdnSpecialTransfererPort(WebServiceFeature... features) {
        return super.getPort(IsdnSpecialTransfererPort, IsdnSpecialTransferer.class, features);
    }

}
