package com.fis.esme.persistence;

import java.util.Date;

// default package
// Generated Dec 18, 2013 10:06:11 AM by Hibernate Tools 3.4.0.CR1

/**
 * EsmeDailyCommandSummary generated by hbm2java
 */
public class EsmeDailyCommandSummary implements java.io.Serializable {

	private Date summaryDate;
	private Long commandId;
	private Long totalSms;
	private Long totalSmsIncomeIncorrect;
	private Long totalSmsIncome;
	private Long totalSmsIncomeHandler;
	private Long totalSmsIncomeFail;
	private Long totalSmsIncomeHasResponse;
	private Long totalSmsOutbound;
	private Long totalSmsSubmitFail;
	private Long totalSmsAckFail;
	private Long totalSmsMobileReceived;
	private Long totalSmsMobileNoReveived;
	private Long totalSmsWaitingDelivery;
	private Long totalSmsIncomeCpReceived;

	public Long getTotalSmsIncomeCpReceived() {
		return totalSmsIncomeCpReceived;
	}
	public void setTotalSmsIncomeCpReceived(Long totalSmsIncomeCpReceived) {
		this.totalSmsIncomeCpReceived = totalSmsIncomeCpReceived;
	}
	public EsmeDailyCommandSummary() {
	}
	public Date getSummaryDate() {
		return this.summaryDate;
	}

	public void setSummaryDate(Date summaryDate) {
		this.summaryDate = summaryDate;
	}

	public Long getCommandId() {
		return this.commandId;
	}

	public void setCommandId(Long commandId) {
		this.commandId = commandId;
	}

	public Long getTotalSms() {
		return this.totalSms;
	}

	public void setTotalSms(Long totalSms) {
		this.totalSms = totalSms;
	}

	public Long getTotalSmsIncomeIncorrect() {
		return this.totalSmsIncomeIncorrect;
	}

	public void setTotalSmsIncomeIncorrect(Long totalSmsIncomeIncorrect) {
		this.totalSmsIncomeIncorrect = totalSmsIncomeIncorrect;
	}

	public Long getTotalSmsIncome() {
		return this.totalSmsIncome;
	}

	public void setTotalSmsIncome(Long totalSmsIncome) {
		this.totalSmsIncome = totalSmsIncome;
	}

	public Long getTotalSmsIncomeHandler() {
		return this.totalSmsIncomeHandler;
	}

	public void setTotalSmsIncomeHandler(Long totalSmsIncomeHandler) {
		this.totalSmsIncomeHandler = totalSmsIncomeHandler;
	}

	public Long getTotalSmsIncomeFail() {
		return this.totalSmsIncomeFail;
	}

	public void setTotalSmsIncomeFail(Long totalSmsIncomeFail) {
		this.totalSmsIncomeFail = totalSmsIncomeFail;
	}

	public Long getTotalSmsIncomeHasResponse() {
		return this.totalSmsIncomeHasResponse;
	}

	public void setTotalSmsIncomeHasResponse(Long totalSmsIncomeHasResponse) {
		this.totalSmsIncomeHasResponse = totalSmsIncomeHasResponse;
	}

	public Long getTotalSmsOutbound() {
		return this.totalSmsOutbound;
	}

	public void setTotalSmsOutbound(Long totalSmsOutbound) {
		this.totalSmsOutbound = totalSmsOutbound;
	}

	public Long getTotalSmsSubmitFail() {
		return this.totalSmsSubmitFail;
	}

	public void setTotalSmsSubmitFail(Long totalSmsSubmitFail) {
		this.totalSmsSubmitFail = totalSmsSubmitFail;
	}

	public Long getTotalSmsAckFail() {
		return this.totalSmsAckFail;
	}

	public void setTotalSmsAckFail(Long totalSmsAckFail) {
		this.totalSmsAckFail = totalSmsAckFail;
	}

	public Long getTotalSmsMobileReceived() {
		return this.totalSmsMobileReceived;
	}

	public void setTotalSmsMobileReceived(Long totalSmsMobileReceived) {
		this.totalSmsMobileReceived = totalSmsMobileReceived;
	}

	public Long getTotalSmsMobileNoReveived() {
		return this.totalSmsMobileNoReveived;
	}

	public void setTotalSmsMobileNoReveived(Long totalSmsMobileNoReveived) {
		this.totalSmsMobileNoReveived = totalSmsMobileNoReveived;
	}

	public Long getTotalSmsWaitingDelivery() {
		return this.totalSmsWaitingDelivery;
	}

	public void setTotalSmsWaitingDelivery(Long totalSmsWaitingDelivery) {
		this.totalSmsWaitingDelivery = totalSmsWaitingDelivery;
	}

	

}
