package com.fis.esme.persistence;
// default package
// Generated Nov 27, 2013 2:12:26 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * EsmeIsdnSpecial generated by hbm2java
 */
public class EsmeIsdnSpecial implements java.io.Serializable {

	private String msisdn;
	private String name;
	private String status;
	private String type;
	private String reason;
	private Set esmeIsdnPermissions = new HashSet(0);

	public EsmeIsdnSpecial() {
	}

	public EsmeIsdnSpecial(String msisdn) {
		this.msisdn = msisdn;
	}

	public EsmeIsdnSpecial(String msisdn, String name, String status,
			String type, String reason, Set esmeIsdnPermissions) {
		this.msisdn = msisdn;
		this.name = name;
		this.status = status;
		this.type = type;
		this.reason = reason;
		this.esmeIsdnPermissions = esmeIsdnPermissions;
	}

	public String getMsisdn() {
		return this.msisdn;
	}

	public void setMsisdn(String msisdn) {
		this.msisdn = msisdn;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getReason() {
		return this.reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

	public Set getEsmeIsdnPermissions() {
		return this.esmeIsdnPermissions;
	}

	public void setEsmeIsdnPermissions(Set esmeIsdnPermissions) {
		this.esmeIsdnPermissions = esmeIsdnPermissions;
	}

}
