package com.fis.esme.persistence;
// default package
// Generated Dec 4, 2013 2:28:41 PM by Hibernate Tools 3.4.0.CR1

/**
 * EsmeSmscRouting generated by hbm2java
 */
public class EsmeSmscRouting implements java.io.Serializable {

	private long smscRoutingId;
	private EsmeIsdnPrefix esmeIsdnPrefix;
	private EsmeSmsc esmeSmsc;

	public EsmeSmscRouting() {
	}

//	public EsmeSmscRouting(long smscRoutingId, long prefixId,
//			long smscId, String shortcode) {
//		this.smscRoutingId = smscRoutingId;
//		this.prefixId = prefixId;
//		this.smscId = smscId;
//		this.shortcode = shortcode;
//	}

	public long getSmscRoutingId() {
		return this.smscRoutingId;
	}

	public void setSmscRoutingId(long smscRoutingId) {
		this.smscRoutingId = smscRoutingId;
	}

//	public EsmeIsdnPrefix getEsmeIsdnPrefix() {
//		return this.esmeIsdnPrefix;
//	}
//
//	public void setEsmeIsdnPrefix(EsmeIsdnPrefix esmeIsdnPrefix) {
//		this.esmeIsdnPrefix = esmeIsdnPrefix;
//	}

//	public EsmeSmsc getEsmeSmsc() {
//		return this.esmeSmsc;
//	}
//
//	public void setEsmeSmsc(EsmeSmsc esmeSmsc) {
//		this.esmeSmsc = esmeSmsc;
//	}

	public EsmeIsdnPrefix getEsmeIsdnPrefix() {
		return this.esmeIsdnPrefix;
	}

	public void setEsmeIsdnPrefix(EsmeIsdnPrefix esmeIsdnPrefix) {
		this.esmeIsdnPrefix = esmeIsdnPrefix;
	}

	public EsmeSmsc getEsmeSmsc() {
		return this.esmeSmsc;
	}

	public void setEsmeSmsc(EsmeSmsc esmeSmsc) {
		this.esmeSmsc = esmeSmsc;
	}

}
