package com.fis.esme.persistence;
// default package
// Generated Nov 27, 2013 2:12:26 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * EsmeShortCode generated by hbm2java
 */
public class EsmeShortCode implements java.io.Serializable {

	private long shortCodeId;
	private String code;
	private String status;
	private String desciption;
	private Long price;
	private Byte mtFreeNumber;
	private Set esmeSmsRoutings = new HashSet(0);

	public EsmeShortCode() {
	}

	public EsmeShortCode(long shortCodeId, String code) {
		this.shortCodeId = shortCodeId;
		this.code = code;
	}

	public EsmeShortCode(long shortCodeId, String code, String status,
			String desciption, Long price, Byte mtFreeNumber,
			Set esmeSmsRoutings) {
		this.shortCodeId = shortCodeId;
		this.code = code;
		this.status = status;
		this.desciption = desciption;
		this.price = price;
		this.mtFreeNumber = mtFreeNumber;
		this.esmeSmsRoutings = esmeSmsRoutings;
	}

	public long getShortCodeId() {
		return this.shortCodeId;
	}

	public void setShortCodeId(long shortCodeId) {
		this.shortCodeId = shortCodeId;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getDesciption() {
		return this.desciption;
	}

	public void setDesciption(String desciption) {
		this.desciption = desciption;
	}

	public Long getPrice() {
		return this.price;
	}

	public void setPrice(Long price) {
		this.price = price;
	}

	public Byte getMtFreeNumber() {
		return this.mtFreeNumber;
	}

	public void setMtFreeNumber(Byte mtFreeNumber) {
		this.mtFreeNumber = mtFreeNumber;
	}

	public Set getEsmeSmsRoutings() {
		return this.esmeSmsRoutings;
	}

	public void setEsmeSmsRoutings(Set esmeSmsRoutings) {
		this.esmeSmsRoutings = esmeSmsRoutings;
	}

}
