package com.fis.esme.persistence;
// default package
// Generated Nov 27, 2013 2:12:26 PM by Hibernate Tools 3.4.0.CR1

/**
 * EsmeSmsLogId generated by hbm2java
 */
public class EsmeSmsLogId implements java.io.Serializable {

	private long logId;
	private String msisdn;

	public EsmeSmsLogId() {
	}

	public EsmeSmsLogId(long logId, String msisdn) {
		this.logId = logId;
		this.msisdn = msisdn;
	}

	public long getLogId() {
		return this.logId;
	}

	public void setLogId(long logId) {
		this.logId = logId;
	}

	public String getMsisdn() {
		return this.msisdn;
	}

	public void setMsisdn(String msisdn) {
		this.msisdn = msisdn;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EsmeSmsLogId))
			return false;
		EsmeSmsLogId castOther = (EsmeSmsLogId) other;

		return (this.getLogId() == castOther.getLogId())
				&& ((this.getMsisdn() == castOther.getMsisdn()) || (this
						.getMsisdn() != null && castOther.getMsisdn() != null && this
						.getMsisdn().equals(castOther.getMsisdn())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getLogId();
		result = 37 * result
				+ (getMsisdn() == null ? 0 : this.getMsisdn().hashCode());
		return result;
	}

}
