package com.fis.esme.persistence;

// default package
// Generated Dec 4, 2013 2:28:41 PM by Hibernate Tools 3.4.0.CR1

/**
 * EsmeSmscParam generated by hbm2java
 */
public class EsmeSmscParam implements java.io.Serializable {

	// private long smscId;
	private EsmeSmsc smscId;
	private String name;
	// private EsmeSmsc esmeSmsc;
	private String value;

	public EsmeSmscParam() {
	}

	// public EsmeSmscParam(long smscId, String name) {
	// this.smscId = smscId;
	// this.name = name;
	// // this.esmeSmsc = esmeSmsc;
	// }
	//
	// public EsmeSmscParam(long smscId, String name, String value) {
	// this.smscId = smscId;
	// // this.esmeSmsc = esmeSmsc;
	// this.value = value;
	// }

	// public long getSmscId() {
	// return this.smscId;
	// }
	//
	// public void setSmscId(long smscId) {
	// this.smscId = smscId;
	// }

	public EsmeSmsc getSmscId() {
		return smscId;
	}

	public void setSmscId(EsmeSmsc smscId) {
		this.smscId = smscId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	// public EsmeSmsc getEsmeSmsc() {
	// return this.esmeSmsc;
	// }
	//
	// public void setEsmeSmsc(EsmeSmsc esmeSmsc) {
	// this.esmeSmsc = esmeSmsc;
	// }

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
