package com.fis.esme.persistence;
// default package
// Generated Nov 27, 2013 2:12:26 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * EsmeSmsComamnd generated by hbm2java
 */
public class EsmeSmsCommand implements java.io.Serializable {

	private long commandId;
	private String code;
	private String name;
	private String status;
	private Set esmeSmsRoutings = new HashSet(0);

	public EsmeSmsCommand() {
	}

	public EsmeSmsCommand(long commandId, String code, String status) {
		this.commandId = commandId;
		this.code = code;
		this.status = status;
	}

	public EsmeSmsCommand(long commandId, String code, String name,
			String status, Set esmeSmsRoutings) {
		this.commandId = commandId;
		this.code = code;
		this.name = name;
		this.status = status;
		this.esmeSmsRoutings = esmeSmsRoutings;
	}

	public long getCommandId() {
		return this.commandId;
	}

	public void setCommandId(long commandId) {
		this.commandId = commandId;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Set getEsmeSmsRoutings() {
		return this.esmeSmsRoutings;
	}

	public void setEsmeSmsRoutings(Set esmeSmsRoutings) {
		this.esmeSmsRoutings = esmeSmsRoutings;
	}

}
