package com.fis.esme.persistence;

import java.util.Date;

/**
 * EsmeFileUploadId generated by hbm2java
 */
public class EsmeFileUpload implements java.io.Serializable {

	/**
	 * 
	 */
	private Long fileUploadId;
	private String fileName;
	private Date createDate;
	private String status;
	private String url;
	private Long totalRecord;
	private String type;
	private Long totalSucess;
	private Long totalFail;
	private EsmeServices esmeServices;

	public EsmeFileUpload() {
	}

	public EsmeFileUpload(Long fileUploadId, String fileName, Date createDate,
			String status, String url, Long totalRecord, String type,
			Long totalSucess, Long totalFail, EsmeServices esmeServices) {
		super();
		this.fileUploadId = fileUploadId;
		this.fileName = fileName;
		this.createDate = createDate;
		this.status = status;
		this.url = url;
		this.totalRecord = totalRecord;
		this.type = type;
		this.totalSucess = totalSucess;
		this.totalFail = totalFail;
		this.esmeServices = esmeServices;
	}
	
	public EsmeServices getEsmeServices() {
		return esmeServices;
	}

	public void setEsmeServices(EsmeServices esmeServices) {
		this.esmeServices = esmeServices;
	}

	public Long getFileUploadId() {
		return this.fileUploadId;
	}

	public void setFileUploadId(Long fileUploadId) {
		this.fileUploadId = fileUploadId;
	}

	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public Long getTotalRecord() {
		return this.totalRecord;
	}

	public void setTotalRecord(Long totalRecord) {
		this.totalRecord = totalRecord;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Long getTotalSucess() {
		return this.totalSucess;
	}

	public void setTotalSucess(Long totalSucess) {
		this.totalSucess = totalSucess;
	}

	public Long getTotalFail() {
		return this.totalFail;
	}

	public void setTotalFail(Long totalFail) {
		this.totalFail = totalFail;
	}

}
