package com.fis.esme.persistence;
// default package
// Generated Nov 27, 2013 2:12:26 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * EsmeLanguage generated by hbm2java
 */
public class EsmeLanguage implements java.io.Serializable {

	private long languageId;
	private String code;
	private String isDefault;
	private String name;
	private String status;
	private Set esmeMessageContents = new HashSet(0);

	public EsmeLanguage() {
	}

	public EsmeLanguage(long languageId, String code, String name, String status) {
		this.languageId = languageId;
		this.code = code;
		this.name = name;
		this.status = status;
	}

	public EsmeLanguage(long languageId, String code, String isDefault,
			String name, String status, Set esmeMessageContents) {
		this.languageId = languageId;
		this.code = code;
		this.isDefault = isDefault;
		this.name = name;
		this.status = status;
		this.esmeMessageContents = esmeMessageContents;
	}

	public long getLanguageId() {
		return this.languageId;
	}

	public void setLanguageId(long languageId) {
		this.languageId = languageId;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getIsDefault() {
		return this.isDefault;
	}

	public void setIsDefault(String isDefault) {
		this.isDefault = isDefault;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Set getEsmeMessageContents() {
		return this.esmeMessageContents;
	}

	public void setEsmeMessageContents(Set esmeMessageContents) {
		this.esmeMessageContents = esmeMessageContents;
	}

}
