package com.fis.esme.persistence;

// default package
// Generated Nov 28, 2013 10:01:33 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * EsmeSmsLog generated by hbm2java
 */
public class EsmeSmsLog implements java.io.Serializable {

	private long logId;
	private Long requestId;
	private String msisdn;
	private Date requestTime;
	private String status;
	private String type;
	// private Long serviceId;
	private Long responseId;
	private Long serviceParentId;
	private Long serviceRoorId;

	private EsmeServices esmeServices;
	private EsmeCp esmeCp;
	private EsmeSmsc esmeSmsc;
	private EsmeShortCode esmeShortCode;
	private EsmeSmsCommand esmeSmsCommand;
	// private long cpId;
	// private long smscId;
	// private long shortCodeId;
	// private long commandId;
	private Long ackId;
	private Date ackDate;
	private Date lastUpdate;
	private String smsContent;
	private Byte totalSms;
	private Long sourceSmsId;
	private String errorCode;
	private EsmeFileUpload esmeFileUpload;

	public EsmeSmsLog() {
	}

	public EsmeSmsLog(long logId, Long requestId, String msisdn,
			Date requestTime, String status, String type, Long responseId,
			Long serviceParentId, Long serviceRoorId,
			EsmeServices esmeServices, EsmeCp esmeCp, EsmeSmsc esmeSmsc,
			EsmeShortCode esmeShortCode, EsmeSmsCommand esmeSmsCommand,
			Long ackId, Date ackDate, Date lastUpdate, String smsContent,
			Byte totalSms, Long sourceSmsId, String errorCode,
			EsmeFileUpload esmeFileUpload) {
		super();
		this.logId = logId;
		this.requestId = requestId;
		this.msisdn = msisdn;
		this.requestTime = requestTime;
		this.status = status;
		this.type = type;
		this.responseId = responseId;
		this.serviceParentId = serviceParentId;
		this.serviceRoorId = serviceRoorId;
		this.esmeServices = esmeServices;
		this.esmeCp = esmeCp;
		this.esmeSmsc = esmeSmsc;
		this.esmeShortCode = esmeShortCode;
		this.esmeSmsCommand = esmeSmsCommand;
		this.ackId = ackId;
		this.ackDate = ackDate;
		this.lastUpdate = lastUpdate;
		this.smsContent = smsContent;
		this.totalSms = totalSms;
		this.sourceSmsId = sourceSmsId;
		this.errorCode = errorCode;
		this.esmeFileUpload = esmeFileUpload;
	}

	public long getLogId() {
		return logId;
	}

	public void setLogId(long logId) {
		this.logId = logId;
	}

	public Long getRequestId() {
		return requestId;
	}

	public void setRequestId(Long requestId) {
		this.requestId = requestId;
	}

	public String getMsisdn() {
		return msisdn;
	}

	public void setMsisdn(String msisdn) {
		this.msisdn = msisdn;
	}

	public Date getRequestTime() {
		return requestTime;
	}

	public void setRequestTime(Date requestTime) {
		this.requestTime = requestTime;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Long getResponseId() {
		return responseId;
	}

	public void setResponseId(Long responseId) {
		this.responseId = responseId;
	}

	public Long getServiceParentId() {
		return serviceParentId;
	}

	public void setServiceParentId(Long serviceParentId) {
		this.serviceParentId = serviceParentId;
	}

	public Long getServiceRoorId() {
		return serviceRoorId;
	}

	public void setServiceRoorId(Long serviceRoorId) {
		this.serviceRoorId = serviceRoorId;
	}

	public EsmeServices getEsmeServices() {
		return esmeServices;
	}

	public void setEsmeServices(EsmeServices esmeServices) {
		this.esmeServices = esmeServices;
	}

	public EsmeCp getEsmeCp() {
		return esmeCp;
	}

	public void setEsmeCp(EsmeCp esmeCp) {
		this.esmeCp = esmeCp;
	}

	public EsmeSmsc getEsmeSmsc() {
		return esmeSmsc;
	}

	public void setEsmeSmsc(EsmeSmsc esmeSmsc) {
		this.esmeSmsc = esmeSmsc;
	}

	public EsmeShortCode getEsmeShortCode() {
		return esmeShortCode;
	}

	public void setEsmeShortCode(EsmeShortCode esmeShortCode) {
		this.esmeShortCode = esmeShortCode;
	}

	public EsmeSmsCommand getEsmeSmsCommand() {
		return esmeSmsCommand;
	}

	public void setEsmeSmsCommand(EsmeSmsCommand esmeSmsCommand) {
		this.esmeSmsCommand = esmeSmsCommand;
	}

	public Long getAckId() {
		return ackId;
	}

	public void setAckId(Long ackId) {
		this.ackId = ackId;
	}

	public Date getAckDate() {
		return ackDate;
	}

	public void setAckDate(Date ackDate) {
		this.ackDate = ackDate;
	}

	public Date getLastUpdate() {
		return lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	public String getSmsContent() {
		return smsContent;
	}

	public void setSmsContent(String smsContent) {
		this.smsContent = smsContent;
	}

	public Byte getTotalSms() {
		return totalSms;
	}

	public void setTotalSms(Byte totalSms) {
		this.totalSms = totalSms;
	}

	public Long getSourceSmsId() {
		return sourceSmsId;
	}

	public void setSourceSmsId(Long sourceSmsId) {
		this.sourceSmsId = sourceSmsId;
	}

	public String getErrorCode() {
		return errorCode;
	}

	public void setErrorCode(String errorCode) {
		this.errorCode = errorCode;
	}

	public EsmeFileUpload getEsmeFileUpload() {
		return esmeFileUpload;
	}

	public void setEsmeFileUpload(EsmeFileUpload esmeFileUpload) {
		this.esmeFileUpload = esmeFileUpload;
	}

}
