package com.fis.esme.persistence;// default package

import java.util.Date;

// Generated Dec 18, 2013 10:06:11 AM by Hibernate Tools 3.4.0.CR1

/**
 * EsmeDailyCpSummary generated by hbm2java
 */
public class EsmeDailyCpSummary implements java.io.Serializable {

	private Date summaryDate;
	private Long cpId;
	private Long totalSms;
	private Long totalSmsIncomeIncorrect;
	private Long totalSmsIncome;
	private Long totalSmsIncomeHandler;
	private Long totalSmsIncomeFail;
	private Long totalSmsIncomeHasResponse;
	private Long totalSmsOutbound;
	private Long totalSmsSubmitFail;
	private Long totalSmsAckFail;
	private Long totalSmsMobileReceived;
	private Long totalSmsMobileNoReveived;
	private Long totalSmsWaitingDelivery;
	private Long totalSmsIncomeCpReceived;

	public Long getTotalSmsIncomeCpReceived() {
		return totalSmsIncomeCpReceived;
	}
	public void setTotalSmsIncomeCpReceived(Long totalSmsIncomeCpReceived) {
		this.totalSmsIncomeCpReceived = totalSmsIncomeCpReceived;
	}
	public EsmeDailyCpSummary() {
	}

	public Date getSummaryDate() {
		return this.summaryDate;
	}

	public void setSummaryDate(Date summaryDate) {
		this.summaryDate = summaryDate;
	}

	public Long getCpId() {
		return this.cpId;
	}

	public void setCpId(Long cpId) {
		this.cpId = cpId;
	}

	public Long getTotalSms() {
		return this.totalSms;
	}

	public void setTotalSms(Long totalSms) {
		this.totalSms = totalSms;
	}

	public Long getTotalSmsIncomeIncorrect() {
		return this.totalSmsIncomeIncorrect;
	}

	public void setTotalSmsIncomeIncorrect(Long totalSmsIncomeIncorrect) {
		this.totalSmsIncomeIncorrect = totalSmsIncomeIncorrect;
	}

	public Long getTotalSmsIncome() {
		return this.totalSmsIncome;
	}

	public void setTotalSmsIncome(Long totalSmsIncome) {
		this.totalSmsIncome = totalSmsIncome;
	}

	public Long getTotalSmsIncomeHandler() {
		return this.totalSmsIncomeHandler;
	}

	public void setTotalSmsIncomeHandler(Long totalSmsIncomeHandler) {
		this.totalSmsIncomeHandler = totalSmsIncomeHandler;
	}

	public Long getTotalSmsIncomeFail() {
		return this.totalSmsIncomeFail;
	}

	public void setTotalSmsIncomeFail(Long totalSmsIncomeFail) {
		this.totalSmsIncomeFail = totalSmsIncomeFail;
	}

	public Long getTotalSmsIncomeHasResponse() {
		return this.totalSmsIncomeHasResponse;
	}

	public void setTotalSmsIncomeHasResponse(Long totalSmsIncomeHasResponse) {
		this.totalSmsIncomeHasResponse = totalSmsIncomeHasResponse;
	}

	public Long getTotalSmsOutbound() {
		return this.totalSmsOutbound;
	}

	public void setTotalSmsOutbound(Long totalSmsOutbound) {
		this.totalSmsOutbound = totalSmsOutbound;
	}

	public Long getTotalSmsSubmitFail() {
		return this.totalSmsSubmitFail;
	}

	public void setTotalSmsSubmitFail(Long totalSmsSubmitFail) {
		this.totalSmsSubmitFail = totalSmsSubmitFail;
	}

	public Long getTotalSmsAckFail() {
		return this.totalSmsAckFail;
	}

	public void setTotalSmsAckFail(Long totalSmsAckFail) {
		this.totalSmsAckFail = totalSmsAckFail;
	}

	public Long getTotalSmsMobileReceived() {
		return this.totalSmsMobileReceived;
	}

	public void setTotalSmsMobileReceived(Long totalSmsMobileReceived) {
		this.totalSmsMobileReceived = totalSmsMobileReceived;
	}

	public Long getTotalSmsMobileNoReveived() {
		return this.totalSmsMobileNoReveived;
	}

	public void setTotalSmsMobileNoReveived(Long totalSmsMobileNoReveived) {
		this.totalSmsMobileNoReveived = totalSmsMobileNoReveived;
	}

	public Long getTotalSmsWaitingDelivery() {
		return this.totalSmsWaitingDelivery;
	}

	public void setTotalSmsWaitingDelivery(Long totalSmsWaitingDelivery) {
		this.totalSmsWaitingDelivery = totalSmsWaitingDelivery;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EsmeDailyCpSummaryId))
			return false;
		EsmeDailyCpSummaryId castOther = (EsmeDailyCpSummaryId) other;

		return ((this.getSummaryDate() == castOther.getSummaryDate()) || (this
				.getSummaryDate() != null && castOther.getSummaryDate() != null && this
				.getSummaryDate().equals(castOther.getSummaryDate())))
				&& ((this.getCpId() == castOther.getCpId()) || (this.getCpId() != null
						&& castOther.getCpId() != null && this.getCpId()
						.equals(castOther.getCpId())))
				&& ((this.getTotalSms() == castOther.getTotalSms()) || (this
						.getTotalSms() != null
						&& castOther.getTotalSms() != null && this
						.getTotalSms().equals(castOther.getTotalSms())))
				&& ((this.getTotalSmsIncomeIncorrect() == castOther
						.getTotalSmsIncomeIncorrect()) || (this
						.getTotalSmsIncomeIncorrect() != null
						&& castOther.getTotalSmsIncomeIncorrect() != null && this
						.getTotalSmsIncomeIncorrect().equals(
								castOther.getTotalSmsIncomeIncorrect())))
				&& ((this.getTotalSmsIncome() == castOther.getTotalSmsIncome()) || (this
						.getTotalSmsIncome() != null
						&& castOther.getTotalSmsIncome() != null && this
						.getTotalSmsIncome().equals(
								castOther.getTotalSmsIncome())))
				&& ((this.getTotalSmsIncomeHandler() == castOther
						.getTotalSmsIncomeHandler()) || (this
						.getTotalSmsIncomeHandler() != null
						&& castOther.getTotalSmsIncomeHandler() != null && this
						.getTotalSmsIncomeHandler().equals(
								castOther.getTotalSmsIncomeHandler())))
				&& ((this.getTotalSmsIncomeFail() == castOther
						.getTotalSmsIncomeFail()) || (this
						.getTotalSmsIncomeFail() != null
						&& castOther.getTotalSmsIncomeFail() != null && this
						.getTotalSmsIncomeFail().equals(
								castOther.getTotalSmsIncomeFail())))
				&& ((this.getTotalSmsIncomeHasResponse() == castOther
						.getTotalSmsIncomeHasResponse()) || (this
						.getTotalSmsIncomeHasResponse() != null
						&& castOther.getTotalSmsIncomeHasResponse() != null && this
						.getTotalSmsIncomeHasResponse().equals(
								castOther.getTotalSmsIncomeHasResponse())))
				&& ((this.getTotalSmsOutbound() == castOther
						.getTotalSmsOutbound()) || (this.getTotalSmsOutbound() != null
						&& castOther.getTotalSmsOutbound() != null && this
						.getTotalSmsOutbound().equals(
								castOther.getTotalSmsOutbound())))
				&& ((this.getTotalSmsSubmitFail() == castOther
						.getTotalSmsSubmitFail()) || (this
						.getTotalSmsSubmitFail() != null
						&& castOther.getTotalSmsSubmitFail() != null && this
						.getTotalSmsSubmitFail().equals(
								castOther.getTotalSmsSubmitFail())))
				&& ((this.getTotalSmsAckFail() == castOther
						.getTotalSmsAckFail()) || (this.getTotalSmsAckFail() != null
						&& castOther.getTotalSmsAckFail() != null && this
						.getTotalSmsAckFail().equals(
								castOther.getTotalSmsAckFail())))
				&& ((this.getTotalSmsMobileReceived() == castOther
						.getTotalSmsMobileReceived()) || (this
						.getTotalSmsMobileReceived() != null
						&& castOther.getTotalSmsMobileReceived() != null && this
						.getTotalSmsMobileReceived().equals(
								castOther.getTotalSmsMobileReceived())))
				&& ((this.getTotalSmsMobileNoReveived() == castOther
						.getTotalSmsMobileNoReveived()) || (this
						.getTotalSmsMobileNoReveived() != null
						&& castOther.getTotalSmsMobileNoReveived() != null && this
						.getTotalSmsMobileNoReveived().equals(
								castOther.getTotalSmsMobileNoReveived())))
				&& ((this.getTotalSmsWaitingDelivery() == castOther
						.getTotalSmsWaitingDelivery()) || (this
						.getTotalSmsWaitingDelivery() != null
						&& castOther.getTotalSmsWaitingDelivery() != null && this
						.getTotalSmsWaitingDelivery().equals(
								castOther.getTotalSmsWaitingDelivery())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getSummaryDate() == null ? 0 : this.getSummaryDate()
						.hashCode());
		result = 37 * result
				+ (getCpId() == null ? 0 : this.getCpId().hashCode());
		result = 37 * result
				+ (getTotalSms() == null ? 0 : this.getTotalSms().hashCode());
		result = 37
				* result
				+ (getTotalSmsIncomeIncorrect() == null ? 0 : this
						.getTotalSmsIncomeIncorrect().hashCode());
		result = 37
				* result
				+ (getTotalSmsIncome() == null ? 0 : this.getTotalSmsIncome()
						.hashCode());
		result = 37
				* result
				+ (getTotalSmsIncomeHandler() == null ? 0 : this
						.getTotalSmsIncomeHandler().hashCode());
		result = 37
				* result
				+ (getTotalSmsIncomeFail() == null ? 0 : this
						.getTotalSmsIncomeFail().hashCode());
		result = 37
				* result
				+ (getTotalSmsIncomeHasResponse() == null ? 0 : this
						.getTotalSmsIncomeHasResponse().hashCode());
		result = 37
				* result
				+ (getTotalSmsOutbound() == null ? 0 : this
						.getTotalSmsOutbound().hashCode());
		result = 37
				* result
				+ (getTotalSmsSubmitFail() == null ? 0 : this
						.getTotalSmsSubmitFail().hashCode());
		result = 37
				* result
				+ (getTotalSmsAckFail() == null ? 0 : this.getTotalSmsAckFail()
						.hashCode());
		result = 37
				* result
				+ (getTotalSmsMobileReceived() == null ? 0 : this
						.getTotalSmsMobileReceived().hashCode());
		result = 37
				* result
				+ (getTotalSmsMobileNoReveived() == null ? 0 : this
						.getTotalSmsMobileNoReveived().hashCode());
		result = 37
				* result
				+ (getTotalSmsWaitingDelivery() == null ? 0 : this
						.getTotalSmsWaitingDelivery().hashCode());
		return result;
	}
}
