package com.fis.esme.persistence;
// default package
// Generated Nov 27, 2013 2:12:26 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * EsmeSmsMo generated by hbm2java
 */
public class EsmeSmsMo implements java.io.Serializable {

	private long moId;
	private long requestId;
	private String message;
	private Date requestTime;
	private String status;
	private String msisdn;
	private String shortCode;
	private Byte retryNumber;
	private Date lastUpdate;
	private String type;
	private String reason;

	public EsmeSmsMo() {
	}

	public EsmeSmsMo(long moId, long requestId, String message, String status,
			String msisdn, String shortCode) {
		this.moId = moId;
		this.requestId = requestId;
		this.message = message;
		this.status = status;
		this.msisdn = msisdn;
		this.shortCode = shortCode;
	}

	public EsmeSmsMo(long moId, long requestId, String message,
			Date requestTime, String status, String msisdn, String shortCode,
			Byte retryNumber, Date lastUpdate, String type, String reason) {
		this.moId = moId;
		this.requestId = requestId;
		this.message = message;
		this.requestTime = requestTime;
		this.status = status;
		this.msisdn = msisdn;
		this.shortCode = shortCode;
		this.retryNumber = retryNumber;
		this.lastUpdate = lastUpdate;
		this.type = type;
		this.reason = reason;
	}

	public long getMoId() {
		return this.moId;
	}

	public void setMoId(long moId) {
		this.moId = moId;
	}

	public long getRequestId() {
		return this.requestId;
	}

	public void setRequestId(long requestId) {
		this.requestId = requestId;
	}

	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	public Date getRequestTime() {
		return this.requestTime;
	}

	public void setRequestTime(Date requestTime) {
		this.requestTime = requestTime;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getMsisdn() {
		return this.msisdn;
	}

	public void setMsisdn(String msisdn) {
		this.msisdn = msisdn;
	}

	public String getShortCode() {
		return this.shortCode;
	}

	public void setShortCode(String shortCode) {
		this.shortCode = shortCode;
	}

	public Byte getRetryNumber() {
		return this.retryNumber;
	}

	public void setRetryNumber(Byte retryNumber) {
		this.retryNumber = retryNumber;
	}

	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getReason() {
		return this.reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

}
