package com.fis.esme.persistence;

// default package
// Generated Dec 14, 2013 11:16:00 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * EsmeSmsMt generated by hbm2java
 */
public class EsmeSmsMt implements java.io.Serializable {

	private long mtId;
	private Long requestId;
	private Date requestTime;
	private String message;
	private long cpId;
	private String shortCode;
	private String msisdn;
	private String status;
	private Integer retryNumber;
	private Date lastRetryTime;
	private String commandCode;
	private String registerDeliveryReport;
	private Integer reloadNumber;
	private Long fileUploadId;

	public EsmeSmsMt() {
	}

	public EsmeSmsMt(long mtId, long cpId, String shortCode, String msisdn,
			String status, String commandCode) {
		this.mtId = mtId;
		this.cpId = cpId;
		this.shortCode = shortCode;
		this.msisdn = msisdn;
		this.status = status;
		this.commandCode = commandCode;
	}

	public EsmeSmsMt(long mtId, Long requestId, Date requestTime,
			String message, long cpId, String shortCode, String msisdn,
			String status, Integer retryNumber, Date lastRetryTime,
			String commandCode, String registerDeliveryReport,
			Integer reloadNumber, Long fileUploadId) {
		this.mtId = mtId;
		this.requestId = requestId;
		this.requestTime = requestTime;
		this.message = message;
		this.cpId = cpId;
		this.shortCode = shortCode;
		this.msisdn = msisdn;
		this.status = status;
		this.retryNumber = retryNumber;
		this.lastRetryTime = lastRetryTime;
		this.commandCode = commandCode;
		this.registerDeliveryReport = registerDeliveryReport;
		this.reloadNumber = reloadNumber;
		this.fileUploadId = fileUploadId;
	}

	public long getMtId() {
		return this.mtId;
	}

	public void setMtId(long mtId) {
		this.mtId = mtId;
	}

	public Long getRequestId() {
		return this.requestId;
	}

	public void setRequestId(Long requestId) {
		this.requestId = requestId;
	}

	public Date getRequestTime() {
		return this.requestTime;
	}

	public void setRequestTime(Date requestTime) {
		this.requestTime = requestTime;
	}

	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	public long getCpId() {
		return this.cpId;
	}

	public void setCpId(long cpId) {
		this.cpId = cpId;
	}

	public String getShortCode() {
		return this.shortCode;
	}

	public void setShortCode(String shortCode) {
		this.shortCode = shortCode;
	}

	public String getMsisdn() {
		return this.msisdn;
	}

	public void setMsisdn(String msisdn) {
		this.msisdn = msisdn;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Integer getRetryNumber() {
		return this.retryNumber;
	}

	public void setRetryNumber(Integer retryNumber) {
		this.retryNumber = retryNumber;
	}

	public Date getLastRetryTime() {
		return this.lastRetryTime;
	}

	public void setLastRetryTime(Date lastRetryTime) {
		this.lastRetryTime = lastRetryTime;
	}

	public String getCommandCode() {
		return this.commandCode;
	}

	public void setCommandCode(String commandCode) {
		this.commandCode = commandCode;
	}

	public String getRegisterDeliveryReport() {
		return this.registerDeliveryReport;
	}

	public void setRegisterDeliveryReport(String registerDeliveryReport) {
		this.registerDeliveryReport = registerDeliveryReport;
	}

	public Integer getReloadNumber() {
		return this.reloadNumber;
	}

	public void setReloadNumber(Integer reloadNumber) {
		this.reloadNumber = reloadNumber;
	}

	public Long getFileUploadId() {
		return this.fileUploadId;
	}

	public void setFileUploadId(Long fileUploadId) {
		this.fileUploadId = fileUploadId;
	}

}
