// default package
// Generated Sep 25, 2014 12:12:46 PM by Hibernate Tools 3.4.0.CR1
package com.fis.esme.persistence;
/**
 * SubGroup generated by hbm2java
 */
public class SubGroup implements java.io.Serializable {

	private long groupId;
	private long subId;
	public SubGroup() {
	}

	public SubGroup(long groupId, long subId) {
		this.groupId = groupId;
		this.subId = subId;
	}

	public long getGroupId() {
		return groupId;
	}

	public void setGroupId(long groupId) {
		this.groupId = groupId;
	}

	public long getSubId() {
		return subId;
	}

	public void setSubId(long subId) {
		this.subId = subId;
	}


}
