package com.fis.esme.persistence;

// default package
// Generated Sep 25, 2014 12:12:46 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Subscriber generated by hbm2java
 */
public class Subscriber implements java.io.Serializable {

	private long subId;
	private String msisdn;
	private String status;
	private String email;
	private String sex;
	private Date createDate;
	private String address;
	private Date birthDate;
	private Set subGroups = new HashSet(0);

	public Subscriber() {
	}

	public Subscriber(long subId, String msisdn, String status, String email) {
		this.subId = subId;
		this.msisdn = msisdn;
		this.status = status;
		this.email = email;
	}

	public Subscriber(long subId, String msisdn, String status, String email,
			String sex, Date createDate, String address, Date birthDate,
			Set subGroups) {
		this.subId = subId;
		this.msisdn = msisdn;
		this.status = status;
		this.email = email;
		this.sex = sex;
		this.createDate = createDate;
		this.address = address;
		this.birthDate = birthDate;
		this.subGroups = subGroups;
	}

	public long getSubId() {
		return this.subId;
	}

	public void setSubId(long subId) {
		this.subId = subId;
	}

	public String getMsisdn() {
		return this.msisdn;
	}

	public void setMsisdn(String msisdn) {
		this.msisdn = msisdn;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public Date getBirthDate() {
		return this.birthDate;
	}

	public void setBirthDate(Date birthDate) {
		this.birthDate = birthDate;
	}

	public Set getSubGroups() {
		return this.subGroups;
	}

	public void setSubGroups(Set subGroups) {
		this.subGroups = subGroups;
	}

}
