package com.fis.esme.persistence;
// default package
// Generated Nov 27, 2013 2:12:26 PM by Hibernate Tools 3.4.0.CR1

/**
 * Thread generated by hbm2java
 */
public class Thread implements java.io.Serializable {

	private long threadId;
	private ThreadParam threadParam;
	private String threadName;
	private String className;
	private String startupType;
	private String status;
	private String command;
	private String schedule;
	private String threadType;

	public Thread() {
	}

	public Thread(long threadId, ThreadParam threadParam) {
		this.threadId = threadId;
		this.threadParam = threadParam;
	}

	public Thread(long threadId, ThreadParam threadParam, String threadName,
			String className, String startupType, String status,
			String command, String schedule, String threadType) {
		this.threadId = threadId;
		this.threadParam = threadParam;
		this.threadName = threadName;
		this.className = className;
		this.startupType = startupType;
		this.status = status;
		this.command = command;
		this.schedule = schedule;
		this.threadType = threadType;
	}

	public long getThreadId() {
		return this.threadId;
	}

	public void setThreadId(long threadId) {
		this.threadId = threadId;
	}

	public ThreadParam getThreadParam() {
		return this.threadParam;
	}

	public void setThreadParam(ThreadParam threadParam) {
		this.threadParam = threadParam;
	}

	public String getThreadName() {
		return this.threadName;
	}

	public void setThreadName(String threadName) {
		this.threadName = threadName;
	}

	public String getClassName() {
		return this.className;
	}

	public void setClassName(String className) {
		this.className = className;
	}

	public String getStartupType() {
		return this.startupType;
	}

	public void setStartupType(String startupType) {
		this.startupType = startupType;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getCommand() {
		return this.command;
	}

	public void setCommand(String command) {
		this.command = command;
	}

	public String getSchedule() {
		return this.schedule;
	}

	public void setSchedule(String schedule) {
		this.schedule = schedule;
	}

	public String getThreadType() {
		return this.threadType;
	}

	public void setThreadType(String threadType) {
		this.threadType = threadType;
	}

}
