
package com.fis.esme.subscriber.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.4.1
 * Tue Sep 30 17:20:29 ICT 2014
 * Generated source version: 2.4.1
 */

@XmlRootElement(name = "add", namespace = "http://subscriber.esme.fis.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "add", namespace = "http://subscriber.esme.fis.com/")

public class Add {

    @XmlElement(name = "arg0")
    private com.fis.esme.persistence.EsmeSubscriber arg0;

    public com.fis.esme.persistence.EsmeSubscriber getArg0() {
        return this.arg0;
    }

    public void setArg0(com.fis.esme.persistence.EsmeSubscriber newArg0)  {
        this.arg0 = newArg0;
    }

}

