
package com.fis.esme.emsmt.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.4.1
 * Tue Sep 30 18:00:58 ICT 2014
 * Generated source version: 2.4.1
 */

@XmlRootElement(name = "findByMtIDResponse", namespace = "http://emsmt.esme.fis.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "findByMtIDResponse", namespace = "http://emsmt.esme.fis.com/")

public class FindByMtIDResponse {

    @XmlElement(name = "return")
    private com.fis.esme.persistence.EsmeEmsMt _return;

    public com.fis.esme.persistence.EsmeEmsMt getReturn() {
        return this._return;
    }

    public void setReturn(com.fis.esme.persistence.EsmeEmsMt new_return)  {
        this._return = new_return;
    }

}

