package com.fis.esme.scheduler;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.1
 * 2014-10-02T10:51:48.110+07:00
 * Generated source version: 2.4.1
 * 
 */
@WebServiceClient(name = "SchedulerTransfererService", 
                  wsdlLocation = "http://localhost:7080/ESME_Business/services/SchedulerTransfererPort?wsdl",
                  targetNamespace = "http://scheduler.esme.fis.com/") 
public class SchedulerTransfererService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://scheduler.esme.fis.com/", "SchedulerTransfererService");
    public final static QName SchedulerTransfererPort = new QName("http://scheduler.esme.fis.com/", "SchedulerTransfererPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:7080/ESME_Business/services/SchedulerTransfererPort?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SchedulerTransfererService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:7080/ESME_Business/services/SchedulerTransfererPort?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SchedulerTransfererService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SchedulerTransfererService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SchedulerTransfererService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns SchedulerTransferer
     */
    @WebEndpoint(name = "SchedulerTransfererPort")
    public SchedulerTransferer getSchedulerTransfererPort() {
        return super.getPort(SchedulerTransfererPort, SchedulerTransferer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SchedulerTransferer
     */
    @WebEndpoint(name = "SchedulerTransfererPort")
    public SchedulerTransferer getSchedulerTransfererPort(WebServiceFeature... features) {
        return super.getPort(SchedulerTransfererPort, SchedulerTransferer.class, features);
    }

}
