package com.fis.esme.smscparam;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.1
 * 2013-12-11T14:27:26.265+07:00
 * Generated source version: 2.4.1
 * 
 */
@WebService(targetNamespace = "http://smscparam.esme.fis.com/", name = "SmscParamTransferer")
@XmlSeeAlso({ObjectFactory.class})
public interface SmscParamTransferer {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "count", targetNamespace = "http://smscparam.esme.fis.com/", className = "com.fis.esme.smscparam.Count")
    @WebMethod
    @ResponseWrapper(localName = "countResponse", targetNamespace = "http://smscparam.esme.fis.com/", className = "com.fis.esme.smscparam.CountResponse")
    public int count(
        @WebParam(name = "arg0", targetNamespace = "")
        com.fis.esme.persistence.SearchEntity arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        com.fis.esme.persistence.EsmeSmscParam arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        boolean arg2
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "checkConstraints", targetNamespace = "http://smscparam.esme.fis.com/", className = "com.fis.esme.smscparam.CheckConstraints")
    @WebMethod
    @ResponseWrapper(localName = "checkConstraintsResponse", targetNamespace = "http://smscparam.esme.fis.com/", className = "com.fis.esme.smscparam.CheckConstraintsResponse")
    public boolean checkConstraints(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Long arg0
    );

    @RequestWrapper(localName = "delete", targetNamespace = "http://smscparam.esme.fis.com/", className = "com.fis.esme.smscparam.Delete")
    @WebMethod
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://smscparam.esme.fis.com/", className = "com.fis.esme.smscparam.DeleteResponse")
    public void delete(
        @WebParam(name = "arg0", targetNamespace = "")
        com.fis.esme.persistence.EsmeSmscParam arg0
    ) throws Exception_Exception;

    @RequestWrapper(localName = "editDetail", targetNamespace = "http://smscparam.esme.fis.com/", className = "com.fis.esme.smscparam.EditDetail")
    @WebMethod
    @ResponseWrapper(localName = "editDetailResponse", targetNamespace = "http://smscparam.esme.fis.com/", className = "com.fis.esme.smscparam.EditDetailResponse")
    public void editDetail(
        @WebParam(name = "arg0", targetNamespace = "")
        com.fis.esme.persistence.EsmeSmscParam arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        com.fis.esme.persistence.EsmeSmscParam arg1
    ) throws Exception_Exception;

    @RequestWrapper(localName = "update", targetNamespace = "http://smscparam.esme.fis.com/", className = "com.fis.esme.smscparam.Update")
    @WebMethod
    @ResponseWrapper(localName = "updateResponse", targetNamespace = "http://smscparam.esme.fis.com/", className = "com.fis.esme.smscparam.UpdateResponse")
    public void update(
        @WebParam(name = "arg0", targetNamespace = "")
        com.fis.esme.persistence.EsmeSmscParam arg0
    ) throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "checkExisted", targetNamespace = "http://smscparam.esme.fis.com/", className = "com.fis.esme.smscparam.CheckExisted")
    @WebMethod
    @ResponseWrapper(localName = "checkExistedResponse", targetNamespace = "http://smscparam.esme.fis.com/", className = "com.fis.esme.smscparam.CheckExistedResponse")
    public int checkExisted(
        @WebParam(name = "arg0", targetNamespace = "")
        com.fis.esme.persistence.EsmeSmscParam arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://smscparam.esme.fis.com/", className = "com.fis.esme.smscparam.Add")
    @WebMethod
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://smscparam.esme.fis.com/", className = "com.fis.esme.smscparam.AddResponse")
    public java.lang.Long add(
        @WebParam(name = "arg0", targetNamespace = "")
        com.fis.esme.persistence.EsmeSmscParam arg0
    ) throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findAllWithoutParameter", targetNamespace = "http://smscparam.esme.fis.com/", className = "com.fis.esme.smscparam.FindAllWithoutParameter")
    @WebMethod
    @ResponseWrapper(localName = "findAllWithoutParameterResponse", targetNamespace = "http://smscparam.esme.fis.com/", className = "com.fis.esme.smscparam.FindAllWithoutParameterResponse")
    public java.util.List<com.fis.esme.persistence.EsmeSmscParam> findAllWithoutParameter() throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findAllWithOrderPaging", targetNamespace = "http://smscparam.esme.fis.com/", className = "com.fis.esme.smscparam.FindAllWithOrderPaging")
    @WebMethod
    @ResponseWrapper(localName = "findAllWithOrderPagingResponse", targetNamespace = "http://smscparam.esme.fis.com/", className = "com.fis.esme.smscparam.FindAllWithOrderPagingResponse")
    public java.util.List<com.fis.esme.persistence.EsmeSmscParam> findAllWithOrderPaging(
        @WebParam(name = "arg0", targetNamespace = "")
        com.fis.esme.persistence.SearchEntity arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        com.fis.esme.persistence.EsmeSmscParam arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        boolean arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        int arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        int arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        boolean arg6
    ) throws Exception_Exception;
}
