package com.fis.esme.smscparam;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.1
 * 2013-12-11T14:27:26.275+07:00
 * Generated source version: 2.4.1
 * 
 */
@WebServiceClient(name = "SmscParamTransfererService", 
                  wsdlLocation = "http://localhost:1080/ESME_Business/services/SmscParamTransfererPort?wsdl",
                  targetNamespace = "http://smscparam.esme.fis.com/") 
public class SmscParamTransfererService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://smscparam.esme.fis.com/", "SmscParamTransfererService");
    public final static QName SmscParamTransfererPort = new QName("http://smscparam.esme.fis.com/", "SmscParamTransfererPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:1080/ESME_Business/services/SmscParamTransfererPort?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SmscParamTransfererService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:1080/ESME_Business/services/SmscParamTransfererPort?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SmscParamTransfererService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SmscParamTransfererService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SmscParamTransfererService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns SmscParamTransferer
     */
    @WebEndpoint(name = "SmscParamTransfererPort")
    public SmscParamTransferer getSmscParamTransfererPort() {
        return super.getPort(SmscParamTransfererPort, SmscParamTransferer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SmscParamTransferer
     */
    @WebEndpoint(name = "SmscParamTransfererPort")
    public SmscParamTransferer getSmscParamTransfererPort(WebServiceFeature... features) {
        return super.getPort(SmscParamTransfererPort, SmscParamTransferer.class, features);
    }

}
