
package com.fis.esme.subgroups.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.4.1
 * Fri Oct 10 09:13:09 ICT 2014
 * Generated source version: 2.4.1
 */

@XmlRootElement(name = "updateResponse", namespace = "http://subgroups.esme.fis.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "updateResponse", namespace = "http://subgroups.esme.fis.com/")

public class UpdateResponse {


}

