
package com.fis.esme.smsc.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.4.1
 * Thu Mar 06 09:09:36 ICT 2014
 * Generated source version: 2.4.1
 */

@XmlRootElement(name = "addCopyDataParam", namespace = "http://smsc.esme.fis.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "addCopyDataParam", namespace = "http://smsc.esme.fis.com/", propOrder = {"arg0", "arg1"})

public class AddCopyDataParam {

    @XmlElement(name = "arg0")
    private com.fis.esme.persistence.EsmeSmsc arg0;
    @XmlElement(name = "arg1")
    private com.fis.esme.persistence.EsmeSmsc arg1;

    public com.fis.esme.persistence.EsmeSmsc getArg0() {
        return this.arg0;
    }

    public void setArg0(com.fis.esme.persistence.EsmeSmsc newArg0)  {
        this.arg0 = newArg0;
    }

    public com.fis.esme.persistence.EsmeSmsc getArg1() {
        return this.arg1;
    }

    public void setArg1(com.fis.esme.persistence.EsmeSmsc newArg1)  {
        this.arg1 = newArg1;
    }

}

