
package com.fis.esme.smsc.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.4.1
 * Thu Mar 06 09:09:36 ICT 2014
 * Generated source version: 2.4.1
 */

@XmlRootElement(name = "addCopyDataParamResponse", namespace = "http://smsc.esme.fis.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "addCopyDataParamResponse", namespace = "http://smsc.esme.fis.com/")

public class AddCopyDataParamResponse {

    @XmlElement(name = "return")
    private java.util.List<com.fis.esme.persistence.EsmeSmscParam> _return;

    public java.util.List<com.fis.esme.persistence.EsmeSmscParam> getReturn() {
        return this._return;
    }

    public void setReturn(java.util.List<com.fis.esme.persistence.EsmeSmscParam> new_return)  {
        this._return = new_return;
    }

}

