
package com.fis.esme.smsc.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.4.1
 * Thu Mar 06 09:09:36 ICT 2014
 * Generated source version: 2.4.1
 */

@XmlRootElement(name = "deleteResponse", namespace = "http://smsc.esme.fis.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "deleteResponse", namespace = "http://smsc.esme.fis.com/")

public class DeleteResponse {


}

