package com.fis.esme.servicesummary;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.1
 * 2013-12-20T10:51:30.008+07:00
 * Generated source version: 2.4.1
 * 
 */
@WebService(targetNamespace = "http://servicesummary.esme.fis.com/", name = "ServiceSummaryTransferer")
@XmlSeeAlso({ObjectFactory.class})
public interface ServiceSummaryTransferer {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findAllByDate", targetNamespace = "http://servicesummary.esme.fis.com/", className = "com.fis.esme.servicesummary.FindAllByDate")
    @WebMethod
    @ResponseWrapper(localName = "findAllByDateResponse", targetNamespace = "http://servicesummary.esme.fis.com/", className = "com.fis.esme.servicesummary.FindAllByDateResponse")
    public java.util.List<com.fis.esme.persistence.EsmeDailyServiceSummary> findAllByDate(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.Date arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.util.Date arg1
    ) throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findAllByDateByListField", targetNamespace = "http://servicesummary.esme.fis.com/", className = "com.fis.esme.servicesummary.FindAllByDateByListField")
    @WebMethod
    @ResponseWrapper(localName = "findAllByDateByListFieldResponse", targetNamespace = "http://servicesummary.esme.fis.com/", className = "com.fis.esme.servicesummary.FindAllByDateByListFieldResponse")
    public java.util.List<com.fis.esme.persistence.EsmeDailyServiceSummary> findAllByDateByListField(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<java.lang.String> arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.util.Date arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.util.Date arg2
    ) throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findAllByDateAndId", targetNamespace = "http://servicesummary.esme.fis.com/", className = "com.fis.esme.servicesummary.FindAllByDateAndId")
    @WebMethod
    @ResponseWrapper(localName = "findAllByDateAndIdResponse", targetNamespace = "http://servicesummary.esme.fis.com/", className = "com.fis.esme.servicesummary.FindAllByDateAndIdResponse")
    public java.util.List<com.fis.esme.persistence.EsmeDailyServiceSummary> findAllByDateAndId(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Long arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.util.Date arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.util.Date arg2
    ) throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findAllInDateByField", targetNamespace = "http://servicesummary.esme.fis.com/", className = "com.fis.esme.servicesummary.FindAllInDateByField")
    @WebMethod
    @ResponseWrapper(localName = "findAllInDateByFieldResponse", targetNamespace = "http://servicesummary.esme.fis.com/", className = "com.fis.esme.servicesummary.FindAllInDateByFieldResponse")
    public java.util.List<com.fis.esme.persistence.EsmeDailyServiceSummary> findAllInDateByField(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.util.Date arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.util.Date arg2
    ) throws Exception_Exception;
}
