package com.fis.esme.language;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.1
 * 2013-11-28T15:06:43.057+07:00
 * Generated source version: 2.4.1
 * 
 */
@WebServiceClient(name = "languageTransfererService", 
                  wsdlLocation = "http://localhost:7080/ESME_Business/services/languageTransfererPort?wsdl",
                  targetNamespace = "http://language.esme.fis.com/") 
public class LanguageTransfererService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://language.esme.fis.com/", "languageTransfererService");
    public final static QName LanguageTransfererPort = new QName("http://language.esme.fis.com/", "languageTransfererPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:7080/ESME_Business/services/languageTransfererPort?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(LanguageTransfererService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:7080/ESME_Business/services/languageTransfererPort?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public LanguageTransfererService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public LanguageTransfererService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LanguageTransfererService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns LanguageTransferer
     */
    @WebEndpoint(name = "languageTransfererPort")
    public LanguageTransferer getLanguageTransfererPort() {
        return super.getPort(LanguageTransfererPort, LanguageTransferer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LanguageTransferer
     */
    @WebEndpoint(name = "languageTransfererPort")
    public LanguageTransferer getLanguageTransfererPort(WebServiceFeature... features) {
        return super.getPort(LanguageTransfererPort, LanguageTransferer.class, features);
    }

}
