
package com.fis.esme.smscommand;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.1
 * 2013-11-28T10:05:12.457+07:00
 * Generated source version: 2.4.1
 * 
 */
public final class SmsCommandTransferer_SmsCommandTransfererPort_Client {

    private static final QName SERVICE_NAME = new QName("http://smscommand.esme.fis.com/", "SmsCommandTransfererService");

    private SmsCommandTransferer_SmsCommandTransfererPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = SmsCommandTransfererService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        SmsCommandTransfererService ss = new SmsCommandTransfererService(wsdlURL, SERVICE_NAME);
        SmsCommandTransferer port = ss.getSmsCommandTransfererPort();  
        
        System.out.println("ssss>>>>>>>"+port.findAllWithoutParameter().size());

        System.exit(0);
    }

}
