package com.fis.esme.smscommand;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.1
 * 2013-11-28T10:05:12.716+07:00
 * Generated source version: 2.4.1
 * 
 */
@WebServiceClient(name = "SmsCommandTransfererService", 
                  wsdlLocation = "http://localhost:7080/ESME_Business/services/SmsCommandTransfererPort?wsdl",
                  targetNamespace = "http://smscommand.esme.fis.com/") 
public class SmsCommandTransfererService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://smscommand.esme.fis.com/", "SmsCommandTransfererService");
    public final static QName SmsCommandTransfererPort = new QName("http://smscommand.esme.fis.com/", "SmsCommandTransfererPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:7080/ESME_Business/services/SmsCommandTransfererPort?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SmsCommandTransfererService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:7080/ESME_Business/services/SmsCommandTransfererPort?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SmsCommandTransfererService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SmsCommandTransfererService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SmsCommandTransfererService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns SmsCommandTransferer
     */
    @WebEndpoint(name = "SmsCommandTransfererPort")
    public SmsCommandTransferer getSmsCommandTransfererPort() {
        return super.getPort(SmsCommandTransfererPort, SmsCommandTransferer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SmsCommandTransferer
     */
    @WebEndpoint(name = "SmsCommandTransfererPort")
    public SmsCommandTransferer getSmsCommandTransfererPort(WebServiceFeature... features) {
        return super.getPort(SmsCommandTransfererPort, SmsCommandTransferer.class, features);
    }

}
