
package com.fis.esme.subscriberdt.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.4.1
 * Fri Oct 10 09:17:39 ICT 2014
 * Generated source version: 2.4.1
 */

@XmlRootElement(name = "checkExisted", namespace = "http://subscriberdt.esme.fis.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "checkExisted", namespace = "http://subscriberdt.esme.fis.com/")

public class CheckExisted {

    @XmlElement(name = "arg0")
    private com.fis.esme.persistence.Subscriber arg0;

    public com.fis.esme.persistence.Subscriber getArg0() {
        return this.arg0;
    }

    public void setArg0(com.fis.esme.persistence.Subscriber newArg0)  {
        this.arg0 = newArg0;
    }

}

