package com.fis.esme.cp;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.1
 * 2013-11-29T10:03:02.503+07:00
 * Generated source version: 2.4.1
 * 
 */
@WebServiceClient(name = "CpTransfererService", 
                  wsdlLocation = "http://localhost:7080/ESME_Business/services/CpTransfererPort?wsdl",
                  targetNamespace = "http://cp.esme.fis.com/") 
public class CpTransfererService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://cp.esme.fis.com/", "CpTransfererService");
    public final static QName CpTransfererPort = new QName("http://cp.esme.fis.com/", "CpTransfererPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:7080/ESME_Business/services/CpTransfererPort?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CpTransfererService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:7080/ESME_Business/services/CpTransfererPort?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CpTransfererService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CpTransfererService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CpTransfererService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns CpTransferer
     */
    @WebEndpoint(name = "CpTransfererPort")
    public CpTransferer getCpTransfererPort() {
        return super.getPort(CpTransfererPort, CpTransferer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CpTransferer
     */
    @WebEndpoint(name = "CpTransfererPort")
    public CpTransferer getCpTransfererPort(WebServiceFeature... features) {
        return super.getPort(CpTransfererPort, CpTransferer.class, features);
    }

}
