
package com.fis.esme.apparam.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.4.1
 * Thu Nov 28 16:26:42 ICT 2013
 * Generated source version: 2.4.1
 */

@XmlRootElement(name = "findAllWithoutParameter", namespace = "http://apparam.esme.fis.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "findAllWithoutParameter", namespace = "http://apparam.esme.fis.com/")

public class FindAllWithoutParameter {


}

