
package com.fis.esme.isdnpermission.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.4.1
 * Tue Dec 03 15:07:04 ICT 2013
 * Generated source version: 2.4.1
 */

@XmlRootElement(name = "deleteResponse", namespace = "http://isdnpermission.esme.fis.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "deleteResponse", namespace = "http://isdnpermission.esme.fis.com/")

public class DeleteResponse {


}

