package com.fis.esme.isdnpermission;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.1
 * 2013-12-03T15:09:51.872+07:00
 * Generated source version: 2.4.1
 * 
 */
@WebService(targetNamespace = "http://isdnpermission.esme.fis.com/", name = "IsdnPermissionTransferer")
@XmlSeeAlso({ObjectFactory.class})
public interface IsdnPermissionTransferer {

    @RequestWrapper(localName = "delete", targetNamespace = "http://isdnpermission.esme.fis.com/", className = "com.fis.esme.isdnpermission.Delete")
    @WebMethod
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://isdnpermission.esme.fis.com/", className = "com.fis.esme.isdnpermission.DeleteResponse")
    public void delete(
        @WebParam(name = "arg0", targetNamespace = "")
        com.fis.esme.persistence.EsmeIsdnPermission arg0
    ) throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findAllWithOrderPaging", targetNamespace = "http://isdnpermission.esme.fis.com/", className = "com.fis.esme.isdnpermission.FindAllWithOrderPaging")
    @WebMethod
    @ResponseWrapper(localName = "findAllWithOrderPagingResponse", targetNamespace = "http://isdnpermission.esme.fis.com/", className = "com.fis.esme.isdnpermission.FindAllWithOrderPagingResponse")
    public java.util.List<com.fis.esme.persistence.EsmeIsdnPermission> findAllWithOrderPaging(
        @WebParam(name = "arg0", targetNamespace = "")
        com.fis.esme.persistence.SearchEntity arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        com.fis.esme.persistence.EsmeIsdnPermission arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        boolean arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        int arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        int arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        boolean arg6
    ) throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findAllWithParameter", targetNamespace = "http://isdnpermission.esme.fis.com/", className = "com.fis.esme.isdnpermission.FindAllWithParameter")
    @WebMethod
    @ResponseWrapper(localName = "findAllWithParameterResponse", targetNamespace = "http://isdnpermission.esme.fis.com/", className = "com.fis.esme.isdnpermission.FindAllWithParameterResponse")
    public java.util.List<com.fis.esme.persistence.EsmeIsdnPermission> findAllWithParameter(
        @WebParam(name = "arg0", targetNamespace = "")
        com.fis.esme.persistence.SearchEntity arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        com.fis.esme.persistence.EsmeIsdnPermission arg1
    ) throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "checkExisted", targetNamespace = "http://isdnpermission.esme.fis.com/", className = "com.fis.esme.isdnpermission.CheckExisted")
    @WebMethod
    @ResponseWrapper(localName = "checkExistedResponse", targetNamespace = "http://isdnpermission.esme.fis.com/", className = "com.fis.esme.isdnpermission.CheckExistedResponse")
    public int checkExisted(
        @WebParam(name = "arg0", targetNamespace = "")
        com.fis.esme.persistence.SearchEntity arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        com.fis.esme.persistence.EsmeIsdnPermission arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "countAll", targetNamespace = "http://isdnpermission.esme.fis.com/", className = "com.fis.esme.isdnpermission.CountAll")
    @WebMethod
    @ResponseWrapper(localName = "countAllResponse", targetNamespace = "http://isdnpermission.esme.fis.com/", className = "com.fis.esme.isdnpermission.CountAllResponse")
    public int countAll();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findAllWithoutParameter", targetNamespace = "http://isdnpermission.esme.fis.com/", className = "com.fis.esme.isdnpermission.FindAllWithoutParameter")
    @WebMethod
    @ResponseWrapper(localName = "findAllWithoutParameterResponse", targetNamespace = "http://isdnpermission.esme.fis.com/", className = "com.fis.esme.isdnpermission.FindAllWithoutParameterResponse")
    public java.util.List<com.fis.esme.persistence.EsmeIsdnPermission> findAllWithoutParameter() throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "checkConstraints", targetNamespace = "http://isdnpermission.esme.fis.com/", className = "com.fis.esme.isdnpermission.CheckConstraints")
    @WebMethod
    @ResponseWrapper(localName = "checkConstraintsResponse", targetNamespace = "http://isdnpermission.esme.fis.com/", className = "com.fis.esme.isdnpermission.CheckConstraintsResponse")
    public boolean checkConstraints(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Long arg0
    );

    @RequestWrapper(localName = "update", targetNamespace = "http://isdnpermission.esme.fis.com/", className = "com.fis.esme.isdnpermission.Update")
    @WebMethod
    @ResponseWrapper(localName = "updateResponse", targetNamespace = "http://isdnpermission.esme.fis.com/", className = "com.fis.esme.isdnpermission.UpdateResponse")
    public void update(
        @WebParam(name = "arg0", targetNamespace = "")
        com.fis.esme.persistence.EsmeIsdnPermission arg0
    ) throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "count", targetNamespace = "http://isdnpermission.esme.fis.com/", className = "com.fis.esme.isdnpermission.Count")
    @WebMethod
    @ResponseWrapper(localName = "countResponse", targetNamespace = "http://isdnpermission.esme.fis.com/", className = "com.fis.esme.isdnpermission.CountResponse")
    public int count(
        @WebParam(name = "arg0", targetNamespace = "")
        com.fis.esme.persistence.EsmeIsdnPermission arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        boolean arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://isdnpermission.esme.fis.com/", className = "com.fis.esme.isdnpermission.Add")
    @WebMethod
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://isdnpermission.esme.fis.com/", className = "com.fis.esme.isdnpermission.AddResponse")
    public java.lang.Long add(
        @WebParam(name = "arg0", targetNamespace = "")
        com.fis.esme.persistence.EsmeIsdnPermission arg0
    ) throws Exception_Exception;
}
