package com.fis.esme.isdnpermission;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.1
 * 2013-12-03T15:09:51.887+07:00
 * Generated source version: 2.4.1
 * 
 */
@WebServiceClient(name = "IsdnPermissionTransfererService", 
                  wsdlLocation = "file:/E:/Working/FIS/Projects/ESME/ESME_Business/WebContent/wsdl/isdnpermissiontransferer.wsdl",
                  targetNamespace = "http://isdnpermission.esme.fis.com/") 
public class IsdnPermissionTransfererService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://isdnpermission.esme.fis.com/", "IsdnPermissionTransfererService");
    public final static QName IsdnPermissionTransfererPort = new QName("http://isdnpermission.esme.fis.com/", "IsdnPermissionTransfererPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/E:/Working/FIS/Projects/ESME/ESME_Business/WebContent/wsdl/isdnpermissiontransferer.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(IsdnPermissionTransfererService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/E:/Working/FIS/Projects/ESME/ESME_Business/WebContent/wsdl/isdnpermissiontransferer.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public IsdnPermissionTransfererService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public IsdnPermissionTransfererService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IsdnPermissionTransfererService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns IsdnPermissionTransferer
     */
    @WebEndpoint(name = "IsdnPermissionTransfererPort")
    public IsdnPermissionTransferer getIsdnPermissionTransfererPort() {
        return super.getPort(IsdnPermissionTransfererPort, IsdnPermissionTransferer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IsdnPermissionTransferer
     */
    @WebEndpoint(name = "IsdnPermissionTransfererPort")
    public IsdnPermissionTransferer getIsdnPermissionTransfererPort(WebServiceFeature... features) {
        return super.getPort(IsdnPermissionTransfererPort, IsdnPermissionTransferer.class, features);
    }

}
