package com.fis.esme.emsmt;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.1
 * 2014-09-30T18:04:05.698+07:00
 * Generated source version: 2.4.1
 * 
 */
@WebServiceClient(name = "EmsMtTransfererService", 
                  wsdlLocation = "http://localhost:7080/ESME_Business/services/EmsMtTransfererPort?wsdl",
                  targetNamespace = "http://emsmt.esme.fis.com/") 
public class EmsMtTransfererService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://emsmt.esme.fis.com/", "EmsMtTransfererService");
    public final static QName EmsMtTransfererPort = new QName("http://emsmt.esme.fis.com/", "EmsMtTransfererPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:7080/ESME_Business/services/EmsMtTransfererPort?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(EmsMtTransfererService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:7080/ESME_Business/services/EmsMtTransfererPort?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public EmsMtTransfererService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public EmsMtTransfererService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EmsMtTransfererService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns EmsMtTransferer
     */
    @WebEndpoint(name = "EmsMtTransfererPort")
    public EmsMtTransferer getEmsMtTransfererPort() {
        return super.getPort(EmsMtTransfererPort, EmsMtTransferer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EmsMtTransferer
     */
    @WebEndpoint(name = "EmsMtTransfererPort")
    public EmsMtTransferer getEmsMtTransfererPort(WebServiceFeature... features) {
        return super.getPort(EmsMtTransfererPort, EmsMtTransferer.class, features);
    }

}
