
package com.fis.esme.servicesummary.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.4.1
 * Thu Dec 19 16:25:29 ICT 2013
 * Generated source version: 2.4.1
 */

@XmlRootElement(name = "findAllInDateByFieldResponse", namespace = "http://servicesummary.esme.fis.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "findAllInDateByFieldResponse", namespace = "http://servicesummary.esme.fis.com/")

public class FindAllInDateByFieldResponse {

    @XmlElement(name = "return")
    private java.util.List<com.fis.esme.persistence.EsmeDailyServiceSummary> _return;

    public java.util.List<com.fis.esme.persistence.EsmeDailyServiceSummary> getReturn() {
        return this._return;
    }

    public void setReturn(java.util.List<com.fis.esme.persistence.EsmeDailyServiceSummary> new_return)  {
        this._return = new_return;
    }

}

