package com.fis.esme.groups;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.1
 * 2014-09-30T17:25:06.161+07:00
 * Generated source version: 2.4.1
 * 
 */
@WebServiceClient(name = "GroupsTransfererService", 
                  wsdlLocation = "http://localhost:7080/ESME_Business/services/GroupsTransfererPort?wsdl",
                  targetNamespace = "http://groups.esme.fis.com/") 
public class GroupsTransfererService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://groups.esme.fis.com/", "GroupsTransfererService");
    public final static QName GroupsTransfererPort = new QName("http://groups.esme.fis.com/", "GroupsTransfererPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:7080/ESME_Business/services/GroupsTransfererPort?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(GroupsTransfererService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:7080/ESME_Business/services/GroupsTransfererPort?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public GroupsTransfererService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GroupsTransfererService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GroupsTransfererService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns GroupsTransferer
     */
    @WebEndpoint(name = "GroupsTransfererPort")
    public GroupsTransferer getGroupsTransfererPort() {
        return super.getPort(GroupsTransfererPort, GroupsTransferer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GroupsTransferer
     */
    @WebEndpoint(name = "GroupsTransfererPort")
    public GroupsTransferer getGroupsTransfererPort(WebServiceFeature... features) {
        return super.getPort(GroupsTransfererPort, GroupsTransferer.class, features);
    }

}
