
package com.fis.esme.groups;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.1
 * 2014-09-30T17:25:05.912+07:00
 * Generated source version: 2.4.1
 * 
 */
public final class GroupsTransferer_GroupsTransfererPort_Client {

    private static final QName SERVICE_NAME = new QName("http://groups.esme.fis.com/", "GroupsTransfererService");

    private GroupsTransferer_GroupsTransfererPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = GroupsTransfererService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        GroupsTransfererService ss = new GroupsTransfererService(wsdlURL, SERVICE_NAME);
        GroupsTransferer port = ss.getGroupsTransfererPort();  
        
        {
        System.out.println("Invoking update...");
        com.fis.esme.persistence.EsmeGroups _update_arg0 = new com.fis.esme.persistence.EsmeGroups();
        _update_arg0.setCreateDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-09-30T17:25:06.024+07:00"));
        _update_arg0.setDescription("Description-1249360927");
        _update_arg0.setGroupId(-7683974254267472880l);
        _update_arg0.setName("Name1667234842");
        _update_arg0.setParentId(-1469127338462275193l);
        _update_arg0.setRootId(-3076597200971472944l);
        _update_arg0.setStatus("Status1256668210");
        try {
            port.update(_update_arg0);

        } catch (Exception_Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking count...");
        com.fis.esme.persistence.EsmeGroups _count_arg0 = new com.fis.esme.persistence.EsmeGroups();
        _count_arg0.setCreateDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-09-30T17:25:06.048+07:00"));
        _count_arg0.setDescription("Description1612739348");
        _count_arg0.setGroupId(8696025718646578164l);
        _count_arg0.setName("Name-2021176346");
        _count_arg0.setParentId(-328310789346442595l);
        _count_arg0.setRootId(-1840273347382216289l);
        _count_arg0.setStatus("Status1314982769");
        boolean _count_arg1 = false;
        int _count__return = port.count(_count_arg0, _count_arg1);
        System.out.println("count.result=" + _count__return);


        }
        {
        System.out.println("Invoking findAllWithOrderPaging...");
        com.fis.esme.persistence.EsmeGroups _findAllWithOrderPaging_arg0 = new com.fis.esme.persistence.EsmeGroups();
        _findAllWithOrderPaging_arg0.setCreateDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-09-30T17:25:06.050+07:00"));
        _findAllWithOrderPaging_arg0.setDescription("Description45922391");
        _findAllWithOrderPaging_arg0.setGroupId(1543870198656560128l);
        _findAllWithOrderPaging_arg0.setName("Name-1097534661");
        _findAllWithOrderPaging_arg0.setParentId(1937345351150235256l);
        _findAllWithOrderPaging_arg0.setRootId(-8851125677595025746l);
        _findAllWithOrderPaging_arg0.setStatus("Status1355660394");
        java.lang.String _findAllWithOrderPaging_arg1 = "_findAllWithOrderPaging_arg1-341977789";
        boolean _findAllWithOrderPaging_arg2 = false;
        int _findAllWithOrderPaging_arg3 = 1095721421;
        int _findAllWithOrderPaging_arg4 = -730122410;
        boolean _findAllWithOrderPaging_arg5 = true;
        try {
            java.util.List<com.fis.esme.persistence.EsmeGroups> _findAllWithOrderPaging__return = port.findAllWithOrderPaging(_findAllWithOrderPaging_arg0, _findAllWithOrderPaging_arg1, _findAllWithOrderPaging_arg2, _findAllWithOrderPaging_arg3, _findAllWithOrderPaging_arg4, _findAllWithOrderPaging_arg5);
            System.out.println("findAllWithOrderPaging.result=" + _findAllWithOrderPaging__return);

        } catch (Exception_Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking findAllWithoutParameter...");
        try {
            java.util.List<com.fis.esme.persistence.EsmeGroups> _findAllWithoutParameter__return = port.findAllWithoutParameter();
            System.out.println("findAllWithoutParameter.result=" + _findAllWithoutParameter__return);

        } catch (Exception_Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking checkExisted...");
        com.fis.esme.persistence.EsmeGroups _checkExisted_arg0 = new com.fis.esme.persistence.EsmeGroups();
        _checkExisted_arg0.setCreateDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-09-30T17:25:06.053+07:00"));
        _checkExisted_arg0.setDescription("Description390549494");
        _checkExisted_arg0.setGroupId(7804291240696386951l);
        _checkExisted_arg0.setName("Name910130618");
        _checkExisted_arg0.setParentId(-5481936666329349657l);
        _checkExisted_arg0.setRootId(7145685976081237410l);
        _checkExisted_arg0.setStatus("Status1684775573");
        int _checkExisted__return = port.checkExisted(_checkExisted_arg0);
        System.out.println("checkExisted.result=" + _checkExisted__return);


        }
        {
        System.out.println("Invoking checkConstraints...");
        java.lang.Long _checkConstraints_arg0 = Long.valueOf(-934625539214948931l);
        boolean _checkConstraints__return = port.checkConstraints(_checkConstraints_arg0);
        System.out.println("checkConstraints.result=" + _checkConstraints__return);


        }
        {
        System.out.println("Invoking delete...");
        com.fis.esme.persistence.EsmeGroups _delete_arg0 = new com.fis.esme.persistence.EsmeGroups();
        _delete_arg0.setCreateDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-09-30T17:25:06.055+07:00"));
        _delete_arg0.setDescription("Description1058269986");
        _delete_arg0.setGroupId(-6611406248532362656l);
        _delete_arg0.setName("Name1234074184");
        _delete_arg0.setParentId(-2859112829639254386l);
        _delete_arg0.setRootId(1029261975432873550l);
        _delete_arg0.setStatus("Status-174286181");
        try {
            port.delete(_delete_arg0);

        } catch (Exception_Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking add...");
        com.fis.esme.persistence.EsmeGroups _add_arg0 = new com.fis.esme.persistence.EsmeGroups();
        _add_arg0.setCreateDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-09-30T17:25:06.057+07:00"));
        _add_arg0.setDescription("Description1601653800");
        _add_arg0.setGroupId(3937704989120311904l);
        _add_arg0.setName("Name-521579774");
        _add_arg0.setParentId(4415863049900672658l);
        _add_arg0.setRootId(-7101127461618122011l);
        _add_arg0.setStatus("Status2025515616");
        try {
            java.lang.Long _add__return = port.add(_add_arg0);
            System.out.println("add.result=" + _add__return);

        } catch (Exception_Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
