package com.fis.esme.groups;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.1
 * 2014-09-30T17:25:06.134+07:00
 * Generated source version: 2.4.1
 * 
 */
@WebService(targetNamespace = "http://groups.esme.fis.com/", name = "GroupsTransferer")
@XmlSeeAlso({ObjectFactory.class})
public interface GroupsTransferer {

    @RequestWrapper(localName = "update", targetNamespace = "http://groups.esme.fis.com/", className = "com.fis.esme.groups.Update")
    @WebMethod
    @ResponseWrapper(localName = "updateResponse", targetNamespace = "http://groups.esme.fis.com/", className = "com.fis.esme.groups.UpdateResponse")
    public void update(
        @WebParam(name = "arg0", targetNamespace = "")
        com.fis.esme.persistence.EsmeGroups arg0
    ) throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "count", targetNamespace = "http://groups.esme.fis.com/", className = "com.fis.esme.groups.Count")
    @WebMethod
    @ResponseWrapper(localName = "countResponse", targetNamespace = "http://groups.esme.fis.com/", className = "com.fis.esme.groups.CountResponse")
    public int count(
        @WebParam(name = "arg0", targetNamespace = "")
        com.fis.esme.persistence.EsmeGroups arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        boolean arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findAllWithOrderPaging", targetNamespace = "http://groups.esme.fis.com/", className = "com.fis.esme.groups.FindAllWithOrderPaging")
    @WebMethod
    @ResponseWrapper(localName = "findAllWithOrderPagingResponse", targetNamespace = "http://groups.esme.fis.com/", className = "com.fis.esme.groups.FindAllWithOrderPagingResponse")
    public java.util.List<com.fis.esme.persistence.EsmeGroups> findAllWithOrderPaging(
        @WebParam(name = "arg0", targetNamespace = "")
        com.fis.esme.persistence.EsmeGroups arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        boolean arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        int arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        int arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        boolean arg5
    ) throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findAllWithoutParameter", targetNamespace = "http://groups.esme.fis.com/", className = "com.fis.esme.groups.FindAllWithoutParameter")
    @WebMethod
    @ResponseWrapper(localName = "findAllWithoutParameterResponse", targetNamespace = "http://groups.esme.fis.com/", className = "com.fis.esme.groups.FindAllWithoutParameterResponse")
    public java.util.List<com.fis.esme.persistence.EsmeGroups> findAllWithoutParameter() throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "checkExisted", targetNamespace = "http://groups.esme.fis.com/", className = "com.fis.esme.groups.CheckExisted")
    @WebMethod
    @ResponseWrapper(localName = "checkExistedResponse", targetNamespace = "http://groups.esme.fis.com/", className = "com.fis.esme.groups.CheckExistedResponse")
    public int checkExisted(
        @WebParam(name = "arg0", targetNamespace = "")
        com.fis.esme.persistence.EsmeGroups arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "checkConstraints", targetNamespace = "http://groups.esme.fis.com/", className = "com.fis.esme.groups.CheckConstraints")
    @WebMethod
    @ResponseWrapper(localName = "checkConstraintsResponse", targetNamespace = "http://groups.esme.fis.com/", className = "com.fis.esme.groups.CheckConstraintsResponse")
    public boolean checkConstraints(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Long arg0
    );

    @RequestWrapper(localName = "delete", targetNamespace = "http://groups.esme.fis.com/", className = "com.fis.esme.groups.Delete")
    @WebMethod
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://groups.esme.fis.com/", className = "com.fis.esme.groups.DeleteResponse")
    public void delete(
        @WebParam(name = "arg0", targetNamespace = "")
        com.fis.esme.persistence.EsmeGroups arg0
    ) throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://groups.esme.fis.com/", className = "com.fis.esme.groups.Add")
    @WebMethod
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://groups.esme.fis.com/", className = "com.fis.esme.groups.AddResponse")
    public java.lang.Long add(
        @WebParam(name = "arg0", targetNamespace = "")
        com.fis.esme.persistence.EsmeGroups arg0
    ) throws Exception_Exception;
}
