package com.fis.esme.dao.impl;

import java.util.Date;
import java.util.List;

import org.hibernate.Criteria;
import org.hibernate.criterion.Expression;
import org.hibernate.criterion.Order;
import org.hibernate.criterion.ProjectionList;
import org.hibernate.criterion.Projections;
import org.hibernate.criterion.Restrictions;

import com.fis.framework.dao.hibernate.GenericDaoSpringHibernateTemplate;
import com.fis.esme.dao.EsmeDailyCpSummaryDao;
import com.fis.esme.persistence.EsmeDailyCpSummary;
import com.fis.esme.persistence.EsmeDailyCpSummary;

// Generated Apr 26, 2011 6:00:02 PM by Hibernate Tools 3.2.4.GA

/**
 * AccessNumber generated by hbm2java
 */
public class EsmeDailyCpSummaryDaoImpl extends
		GenericDaoSpringHibernateTemplate<EsmeDailyCpSummary, Date> implements
		EsmeDailyCpSummaryDao

{

	@Override
	public List<EsmeDailyCpSummary> findAllByDate(Date fromDate, Date toDate)
			throws Exception {
		
		Criteria criteria = getSession().createCriteria(EsmeDailyCpSummary.class);
		criteria.add(Restrictions.between("summaryDate", fromDate, toDate));
		criteria.addOrder(Order.asc("summaryDate"));
		List<EsmeDailyCpSummary> list = criteria.list();
		return list;
	}

	@Override
	public List<EsmeDailyCpSummary> findAllByDateByListField(List<String> fields,
			Date fromDate, Date toDate) throws Exception {
		
		Criteria criteria = getSession().createCriteria(EsmeDailyCpSummary.class);
		ProjectionList projectionList = Projections.projectionList();
		for (String string : fields) {
			projectionList.add(Projections.property(string));
		}
		criteria.setProjection(projectionList);
		criteria.add(Restrictions.between("summaryDate", fromDate, toDate));
		criteria.addOrder(Order.asc("summaryDate"));
		List<EsmeDailyCpSummary> list = criteria.list();
		return list;
	}

	@Override
	public List<EsmeDailyCpSummary> findAllInDateByField(String field, Date fromDate,
			Date toDate) throws Exception {
		
		Criteria criteria = getSession().createCriteria(EsmeDailyCpSummary.class);
		criteria.add(Expression.between(field, fromDate, toDate));
		return criteria.list();
	}

	@Override
	public List<EsmeDailyCpSummary> findAllByDateAndId(Long serviceId,
			Date fromDate, Date toDate) throws Exception {
		Criteria criteria = getSession().createCriteria(
				EsmeDailyCpSummary.class);
		if (serviceId != null) {
			criteria.add(Restrictions.eq("cpId", serviceId));
		}
		criteria.add(Restrictions.between("summaryDate", fromDate, toDate));
		criteria.addOrder(Order.asc("summaryDate"));
		List<EsmeDailyCpSummary> list = criteria.list();
		return list;
	}

	

}
