package com.fis.esme.dao.impl;

import java.util.Date;
import java.util.List;

import org.hibernate.Criteria;
import org.hibernate.criterion.Expression;
import org.hibernate.criterion.Order;
import org.hibernate.criterion.ProjectionList;
import org.hibernate.criterion.Projections;
import org.hibernate.criterion.Restrictions;

import com.fis.esme.dao.EsmeDailyServiceSummaryDao;
import com.fis.esme.persistence.EsmeDailyServiceSummary;
import com.fis.framework.dao.hibernate.GenericDaoSpringHibernateTemplate;

// Generated Apr 26, 2011 6:00:02 PM by Hibernate Tools 3.2.4.GA

/**
 * AccessNumber generated by hbm2java
 */
public class EsmeDailyServiceSummaryDaoImpl extends
		GenericDaoSpringHibernateTemplate<EsmeDailyServiceSummary, Date>
		implements EsmeDailyServiceSummaryDao

{

	@Override
	public List<EsmeDailyServiceSummary> findAllByDate(Date fromDate,
			Date toDate) throws Exception {

		Criteria criteria = getSession().createCriteria(
				EsmeDailyServiceSummary.class);
		criteria.add(Restrictions.between("summaryDate", fromDate, toDate));
		criteria.addOrder(Order.asc("summaryDate"));
		List<EsmeDailyServiceSummary> list = criteria.list();
		return list;
	}

	@Override
	public List<EsmeDailyServiceSummary> findAllByDateByListField(
			List<String> fields, Date fromDate, Date toDate) throws Exception {

		Criteria criteria = getSession().createCriteria(
				EsmeDailyServiceSummary.class);
		ProjectionList projectionList = Projections.projectionList();
		for (String string : fields) {
			projectionList.add(Projections.property(string));
		}
		criteria.setProjection(projectionList);
		criteria.add(Restrictions.between("summaryDate", fromDate, toDate));
		criteria.addOrder(Order.asc("summaryDate"));
		List<EsmeDailyServiceSummary> list = criteria.list();
		return list;
	}

	@Override
	public List<EsmeDailyServiceSummary> findAllInDateByField(String field,
			Date fromDate, Date toDate) throws Exception {

		Criteria criteria = getSession().createCriteria(
				EsmeDailyServiceSummary.class);
		criteria.add(Expression.between(field, fromDate, toDate));
		return criteria.list();
	}
	
	
	public List<EsmeDailyServiceSummary> findAllByDateAndId(
			Long serviceId, Date fromDate, Date toDate) throws Exception {

		Criteria criteria = getSession().createCriteria(
				EsmeDailyServiceSummary.class);
		if (serviceId != null) {
			criteria.add(Restrictions.eq("serviceId", serviceId));
		}
		criteria.add(Restrictions.between("summaryDate", fromDate, toDate));
		criteria.addOrder(Order.asc("summaryDate"));
		List<EsmeDailyServiceSummary> list = criteria.list();
		return list;
	}
}
