package com.fis.esme.dao.impl;

import java.util.Date;
import java.util.List;

import org.hibernate.Criteria;
import org.hibernate.criterion.Expression;
import org.hibernate.criterion.Order;
import org.hibernate.criterion.ProjectionList;
import org.hibernate.criterion.Projections;
import org.hibernate.criterion.Restrictions;

import com.fis.esme.dao.EsmeDailyCommandSummaryDao;
import com.fis.esme.persistence.EsmeDailyCommandSummary;
import com.fis.framework.dao.hibernate.GenericDaoSpringHibernateTemplate;

// Generated Apr 26, 2011 6:00:02 PM by Hibernate Tools 3.2.4.GA

/**
 * AccessNumber generated by hbm2java
 */
public class EsmeDailyCommandSummaryDaoImpl extends
		GenericDaoSpringHibernateTemplate<EsmeDailyCommandSummary, Date>
		implements EsmeDailyCommandSummaryDao

{

	@Override
	public List<EsmeDailyCommandSummary> findAllByDate(Date fromDate,
			Date toDate) throws Exception {

		Criteria criteria = getSession().createCriteria(
				EsmeDailyCommandSummary.class);
		criteria.add(Restrictions.between("summaryDate", fromDate, toDate));
		criteria.addOrder(Order.asc("summaryDate"));
		List<EsmeDailyCommandSummary> list = criteria.list();
		return list;
	}

	@Override
	public List<EsmeDailyCommandSummary> findAllByDateByListField(
			List<String> fields, Date fromDate, Date toDate) throws Exception {

		Criteria criteria = getSession().createCriteria(
				EsmeDailyCommandSummary.class);
		ProjectionList projectionList = Projections.projectionList();
		for (String string : fields) {
			projectionList.add(Projections.property(string));
		}
		criteria.setProjection(projectionList);
		criteria.add(Restrictions.between("summaryDate", fromDate, toDate));
		criteria.addOrder(Order.asc("summaryDate"));
		List<EsmeDailyCommandSummary> list = criteria.list();
		return list;
	}

	@Override
	public List<EsmeDailyCommandSummary> findAllInDateByField(String field,
			Date fromDate, Date toDate) throws Exception {

		Criteria criteria = getSession().createCriteria(
				EsmeDailyCommandSummary.class);
		criteria.add(Expression.between(field, fromDate, toDate));
		return criteria.list();
	}

	@Override
	public List<EsmeDailyCommandSummary> findAllByDateAndId(Long serviceId,
			Date fromDate, Date toDate) throws Exception {
		Criteria criteria = getSession().createCriteria(
				EsmeDailyCommandSummary.class);
		if (serviceId != null) {
			criteria.add(Restrictions.eq("commandId", serviceId));
		}
		criteria.add(Restrictions.between("summaryDate", fromDate, toDate));
		criteria.addOrder(Order.asc("summaryDate"));
		List<EsmeDailyCommandSummary> list = criteria.list();
		return list;
	}

}
