package com.fis.esme.emsmo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.1
 * 2014-09-30T18:03:19.602+07:00
 * Generated source version: 2.4.1
 * 
 */
@WebService(targetNamespace = "http://emsmo.esme.fis.com/", name = "EmsMoTransferer")
@XmlSeeAlso({ObjectFactory.class})
public interface EmsMoTransferer {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "checkConstraints", targetNamespace = "http://emsmo.esme.fis.com/", className = "com.fis.esme.emsmo.CheckConstraints")
    @WebMethod
    @ResponseWrapper(localName = "checkConstraintsResponse", targetNamespace = "http://emsmo.esme.fis.com/", className = "com.fis.esme.emsmo.CheckConstraintsResponse")
    public boolean checkConstraints(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Long arg0
    );

    @RequestWrapper(localName = "delete", targetNamespace = "http://emsmo.esme.fis.com/", className = "com.fis.esme.emsmo.Delete")
    @WebMethod
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://emsmo.esme.fis.com/", className = "com.fis.esme.emsmo.DeleteResponse")
    public void delete(
        @WebParam(name = "arg0", targetNamespace = "")
        com.fis.esme.persistence.EsmeEmsMo arg0
    ) throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://emsmo.esme.fis.com/", className = "com.fis.esme.emsmo.Add")
    @WebMethod
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://emsmo.esme.fis.com/", className = "com.fis.esme.emsmo.AddResponse")
    public java.lang.Long add(
        @WebParam(name = "arg0", targetNamespace = "")
        com.fis.esme.persistence.EsmeEmsMo arg0
    ) throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findAllWithOrderPaging", targetNamespace = "http://emsmo.esme.fis.com/", className = "com.fis.esme.emsmo.FindAllWithOrderPaging")
    @WebMethod
    @ResponseWrapper(localName = "findAllWithOrderPagingResponse", targetNamespace = "http://emsmo.esme.fis.com/", className = "com.fis.esme.emsmo.FindAllWithOrderPagingResponse")
    public java.util.List<com.fis.esme.persistence.EsmeEmsMo> findAllWithOrderPaging(
        @WebParam(name = "arg0", targetNamespace = "")
        com.fis.esme.persistence.EsmeEmsMo arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        boolean arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        int arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        int arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        boolean arg5
    ) throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findAllWithoutParameter", targetNamespace = "http://emsmo.esme.fis.com/", className = "com.fis.esme.emsmo.FindAllWithoutParameter")
    @WebMethod
    @ResponseWrapper(localName = "findAllWithoutParameterResponse", targetNamespace = "http://emsmo.esme.fis.com/", className = "com.fis.esme.emsmo.FindAllWithoutParameterResponse")
    public java.util.List<com.fis.esme.persistence.EsmeEmsMo> findAllWithoutParameter() throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "count", targetNamespace = "http://emsmo.esme.fis.com/", className = "com.fis.esme.emsmo.Count")
    @WebMethod
    @ResponseWrapper(localName = "countResponse", targetNamespace = "http://emsmo.esme.fis.com/", className = "com.fis.esme.emsmo.CountResponse")
    public int count(
        @WebParam(name = "arg0", targetNamespace = "")
        com.fis.esme.persistence.EsmeEmsMo arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        boolean arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "checkExisted", targetNamespace = "http://emsmo.esme.fis.com/", className = "com.fis.esme.emsmo.CheckExisted")
    @WebMethod
    @ResponseWrapper(localName = "checkExistedResponse", targetNamespace = "http://emsmo.esme.fis.com/", className = "com.fis.esme.emsmo.CheckExistedResponse")
    public int checkExisted(
        @WebParam(name = "arg0", targetNamespace = "")
        com.fis.esme.persistence.EsmeEmsMo arg0
    );

    @RequestWrapper(localName = "update", targetNamespace = "http://emsmo.esme.fis.com/", className = "com.fis.esme.emsmo.Update")
    @WebMethod
    @ResponseWrapper(localName = "updateResponse", targetNamespace = "http://emsmo.esme.fis.com/", className = "com.fis.esme.emsmo.UpdateResponse")
    public void update(
        @WebParam(name = "arg0", targetNamespace = "")
        com.fis.esme.persistence.EsmeEmsMo arg0
    ) throws Exception_Exception;
}
