package com.fis.esme.schedulerdetail;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.1
 * 2014-10-02T10:52:27.975+07:00
 * Generated source version: 2.4.1
 * 
 */
@WebService(targetNamespace = "http://schedulerdetail.esme.fis.com/", name = "SchedulerDetailTransferer")
@XmlSeeAlso({ObjectFactory.class})
public interface SchedulerDetailTransferer {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findAllWithOrderPaging", targetNamespace = "http://schedulerdetail.esme.fis.com/", className = "com.fis.esme.schedulerdetail.FindAllWithOrderPaging")
    @WebMethod
    @ResponseWrapper(localName = "findAllWithOrderPagingResponse", targetNamespace = "http://schedulerdetail.esme.fis.com/", className = "com.fis.esme.schedulerdetail.FindAllWithOrderPagingResponse")
    public java.util.List<com.fis.esme.persistence.EsmeSchedulerDetail> findAllWithOrderPaging(
        @WebParam(name = "arg0", targetNamespace = "")
        com.fis.esme.persistence.EsmeSchedulerDetail arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        boolean arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        int arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        int arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        boolean arg5
    ) throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "count", targetNamespace = "http://schedulerdetail.esme.fis.com/", className = "com.fis.esme.schedulerdetail.Count")
    @WebMethod
    @ResponseWrapper(localName = "countResponse", targetNamespace = "http://schedulerdetail.esme.fis.com/", className = "com.fis.esme.schedulerdetail.CountResponse")
    public int count(
        @WebParam(name = "arg0", targetNamespace = "")
        com.fis.esme.persistence.EsmeSchedulerDetail arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        boolean arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "checkExisted", targetNamespace = "http://schedulerdetail.esme.fis.com/", className = "com.fis.esme.schedulerdetail.CheckExisted")
    @WebMethod
    @ResponseWrapper(localName = "checkExistedResponse", targetNamespace = "http://schedulerdetail.esme.fis.com/", className = "com.fis.esme.schedulerdetail.CheckExistedResponse")
    public int checkExisted(
        @WebParam(name = "arg0", targetNamespace = "")
        com.fis.esme.persistence.EsmeSchedulerDetail arg0
    );

    @RequestWrapper(localName = "update", targetNamespace = "http://schedulerdetail.esme.fis.com/", className = "com.fis.esme.schedulerdetail.Update")
    @WebMethod
    @ResponseWrapper(localName = "updateResponse", targetNamespace = "http://schedulerdetail.esme.fis.com/", className = "com.fis.esme.schedulerdetail.UpdateResponse")
    public void update(
        @WebParam(name = "arg0", targetNamespace = "")
        com.fis.esme.persistence.EsmeSchedulerDetail arg0
    ) throws Exception_Exception;

    @RequestWrapper(localName = "delete", targetNamespace = "http://schedulerdetail.esme.fis.com/", className = "com.fis.esme.schedulerdetail.Delete")
    @WebMethod
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://schedulerdetail.esme.fis.com/", className = "com.fis.esme.schedulerdetail.DeleteResponse")
    public void delete(
        @WebParam(name = "arg0", targetNamespace = "")
        com.fis.esme.persistence.EsmeSchedulerDetail arg0
    ) throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://schedulerdetail.esme.fis.com/", className = "com.fis.esme.schedulerdetail.Add")
    @WebMethod
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://schedulerdetail.esme.fis.com/", className = "com.fis.esme.schedulerdetail.AddResponse")
    public java.lang.Long add(
        @WebParam(name = "arg0", targetNamespace = "")
        com.fis.esme.persistence.EsmeSchedulerDetail arg0
    ) throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "checkConstraints", targetNamespace = "http://schedulerdetail.esme.fis.com/", className = "com.fis.esme.schedulerdetail.CheckConstraints")
    @WebMethod
    @ResponseWrapper(localName = "checkConstraintsResponse", targetNamespace = "http://schedulerdetail.esme.fis.com/", className = "com.fis.esme.schedulerdetail.CheckConstraintsResponse")
    public boolean checkConstraints(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Long arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findAllWithoutParameter", targetNamespace = "http://schedulerdetail.esme.fis.com/", className = "com.fis.esme.schedulerdetail.FindAllWithoutParameter")
    @WebMethod
    @ResponseWrapper(localName = "findAllWithoutParameterResponse", targetNamespace = "http://schedulerdetail.esme.fis.com/", className = "com.fis.esme.schedulerdetail.FindAllWithoutParameterResponse")
    public java.util.List<com.fis.esme.persistence.EsmeSchedulerDetail> findAllWithoutParameter() throws Exception_Exception;
}
