package com.fis.esme.schedulerdetail;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.1
 * 2014-10-02T10:52:27.986+07:00
 * Generated source version: 2.4.1
 * 
 */
@WebServiceClient(name = "SchedulerDetailTransfererService", 
                  wsdlLocation = "http://localhost:7080/ESME_Business/services/SchedulerDetailTransfererPort?wsdl",
                  targetNamespace = "http://schedulerdetail.esme.fis.com/") 
public class SchedulerDetailTransfererService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://schedulerdetail.esme.fis.com/", "SchedulerDetailTransfererService");
    public final static QName SchedulerDetailTransfererPort = new QName("http://schedulerdetail.esme.fis.com/", "SchedulerDetailTransfererPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:7080/ESME_Business/services/SchedulerDetailTransfererPort?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SchedulerDetailTransfererService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:7080/ESME_Business/services/SchedulerDetailTransfererPort?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SchedulerDetailTransfererService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SchedulerDetailTransfererService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SchedulerDetailTransfererService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns SchedulerDetailTransferer
     */
    @WebEndpoint(name = "SchedulerDetailTransfererPort")
    public SchedulerDetailTransferer getSchedulerDetailTransfererPort() {
        return super.getPort(SchedulerDetailTransfererPort, SchedulerDetailTransferer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SchedulerDetailTransferer
     */
    @WebEndpoint(name = "SchedulerDetailTransfererPort")
    public SchedulerDetailTransferer getSchedulerDetailTransfererPort(WebServiceFeature... features) {
        return super.getPort(SchedulerDetailTransfererPort, SchedulerDetailTransferer.class, features);
    }

}
