package com.fis.esme.groupsdt;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.1
 * 2014-10-10T09:19:26.505+07:00
 * Generated source version: 2.4.1
 * 
 */
@WebService(targetNamespace = "http://groupsdt.esme.fis.com/", name = "GroupsDTTransferer")
@XmlSeeAlso({ObjectFactory.class})
public interface GroupsDTTransferer {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findAllWithOrderPaging", targetNamespace = "http://groupsdt.esme.fis.com/", className = "com.fis.esme.groupsdt.FindAllWithOrderPaging")
    @WebMethod
    @ResponseWrapper(localName = "findAllWithOrderPagingResponse", targetNamespace = "http://groupsdt.esme.fis.com/", className = "com.fis.esme.groupsdt.FindAllWithOrderPagingResponse")
    public java.util.List<com.fis.esme.persistence.Groups> findAllWithOrderPaging(
        @WebParam(name = "arg0", targetNamespace = "")
        com.fis.esme.persistence.Groups arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        boolean arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        int arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        int arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        boolean arg5
    ) throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findBySubGgroup", targetNamespace = "http://groupsdt.esme.fis.com/", className = "com.fis.esme.groupsdt.FindBySubGgroup")
    @WebMethod
    @ResponseWrapper(localName = "findBySubGgroupResponse", targetNamespace = "http://groupsdt.esme.fis.com/", className = "com.fis.esme.groupsdt.FindBySubGgroupResponse")
    public com.fis.esme.persistence.Groups findBySubGgroup(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "checkExisted", targetNamespace = "http://groupsdt.esme.fis.com/", className = "com.fis.esme.groupsdt.CheckExisted")
    @WebMethod
    @ResponseWrapper(localName = "checkExistedResponse", targetNamespace = "http://groupsdt.esme.fis.com/", className = "com.fis.esme.groupsdt.CheckExistedResponse")
    public int checkExisted(
        @WebParam(name = "arg0", targetNamespace = "")
        com.fis.esme.persistence.Groups arg0
    );

    @RequestWrapper(localName = "update", targetNamespace = "http://groupsdt.esme.fis.com/", className = "com.fis.esme.groupsdt.Update")
    @WebMethod
    @ResponseWrapper(localName = "updateResponse", targetNamespace = "http://groupsdt.esme.fis.com/", className = "com.fis.esme.groupsdt.UpdateResponse")
    public void update(
        @WebParam(name = "arg0", targetNamespace = "")
        com.fis.esme.persistence.Groups arg0
    ) throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "checkConstraints", targetNamespace = "http://groupsdt.esme.fis.com/", className = "com.fis.esme.groupsdt.CheckConstraints")
    @WebMethod
    @ResponseWrapper(localName = "checkConstraintsResponse", targetNamespace = "http://groupsdt.esme.fis.com/", className = "com.fis.esme.groupsdt.CheckConstraintsResponse")
    public boolean checkConstraints(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Long arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "count", targetNamespace = "http://groupsdt.esme.fis.com/", className = "com.fis.esme.groupsdt.Count")
    @WebMethod
    @ResponseWrapper(localName = "countResponse", targetNamespace = "http://groupsdt.esme.fis.com/", className = "com.fis.esme.groupsdt.CountResponse")
    public int count(
        @WebParam(name = "arg0", targetNamespace = "")
        com.fis.esme.persistence.Groups arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        boolean arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findAllWithoutParameter", targetNamespace = "http://groupsdt.esme.fis.com/", className = "com.fis.esme.groupsdt.FindAllWithoutParameter")
    @WebMethod
    @ResponseWrapper(localName = "findAllWithoutParameterResponse", targetNamespace = "http://groupsdt.esme.fis.com/", className = "com.fis.esme.groupsdt.FindAllWithoutParameterResponse")
    public java.util.List<com.fis.esme.persistence.Groups> findAllWithoutParameter() throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://groupsdt.esme.fis.com/", className = "com.fis.esme.groupsdt.Add")
    @WebMethod
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://groupsdt.esme.fis.com/", className = "com.fis.esme.groupsdt.AddResponse")
    public java.lang.Long add(
        @WebParam(name = "arg0", targetNamespace = "")
        com.fis.esme.persistence.Groups arg0
    ) throws Exception_Exception;

    @RequestWrapper(localName = "delete", targetNamespace = "http://groupsdt.esme.fis.com/", className = "com.fis.esme.groupsdt.Delete")
    @WebMethod
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://groupsdt.esme.fis.com/", className = "com.fis.esme.groupsdt.DeleteResponse")
    public void delete(
        @WebParam(name = "arg0", targetNamespace = "")
        com.fis.esme.persistence.Groups arg0
    ) throws Exception_Exception;
}
