package com.fis.esme.groupsdt;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.1
 * 2014-10-10T09:19:26.514+07:00
 * Generated source version: 2.4.1
 * 
 */
@WebServiceClient(name = "GroupsDTTransfererService", 
                  wsdlLocation = "file:/C:/Users/Cong/Desktop/ESME/ESME_Business/WebContent/wsdl/groupsdttransferer.wsdl",
                  targetNamespace = "http://groupsdt.esme.fis.com/") 
public class GroupsDTTransfererService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://groupsdt.esme.fis.com/", "GroupsDTTransfererService");
    public final static QName GroupsDTTransfererPort = new QName("http://groupsdt.esme.fis.com/", "GroupsDTTransfererPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/Cong/Desktop/ESME/ESME_Business/WebContent/wsdl/groupsdttransferer.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(GroupsDTTransfererService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/Cong/Desktop/ESME/ESME_Business/WebContent/wsdl/groupsdttransferer.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public GroupsDTTransfererService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GroupsDTTransfererService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GroupsDTTransfererService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns GroupsDTTransferer
     */
    @WebEndpoint(name = "GroupsDTTransfererPort")
    public GroupsDTTransferer getGroupsDTTransfererPort() {
        return super.getPort(GroupsDTTransfererPort, GroupsDTTransferer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GroupsDTTransferer
     */
    @WebEndpoint(name = "GroupsDTTransfererPort")
    public GroupsDTTransferer getGroupsDTTransfererPort(WebServiceFeature... features) {
        return super.getPort(GroupsDTTransfererPort, GroupsDTTransferer.class, features);
    }

}
