package com.fis.esme.isdnprefix;

/**
 * Please modify this class to meet your needs This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.4.1 2014-11-24T16:03:54.863+07:00 Generated source version: 2.4.1
 * 
 */
public final class IsdnPrefixTransferer_IsdnPrefixTransfererPort_Client {

	private static final QName SERVICE_NAME = new QName("http://isdnprefix.esme.fis.com/", "IsdnPrefixTransfererService");

	private IsdnPrefixTransferer_IsdnPrefixTransfererPort_Client() {

	}

	public static void main(String args[]) throws java.lang.Exception {

		URL wsdlURL = IsdnPrefixTransfererService.WSDL_LOCATION;
		if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
			File wsdlFile = new File(args[0]);
			try {
				if (wsdlFile.exists()) {
					wsdlURL = wsdlFile.toURI().toURL();
				} else {
					wsdlURL = new URL(args[0]);
				}
			} catch (MalformedURLException e) {
				e.printStackTrace();
			}
		}

		IsdnPrefixTransfererService ss = new IsdnPrefixTransfererService(wsdlURL, SERVICE_NAME);
		IsdnPrefixTransferer port = ss.getIsdnPrefixTransfererPort();

		// {
		// System.out.println("Invoking findAllWithOrderPaging...");
		// com.fis.esme.isdnprefix.EsmeIsdnPrefix _findAllWithOrderPaging_arg0 = new com.fis.esme.isdnprefix.EsmeIsdnPrefix();
		// _findAllWithOrderPaging_arg0.setDescription("Description1098815326");
		// java.util.List<java.lang.Object> _findAllWithOrderPaging_arg0EsmeSmscRoutings = new java.util.ArrayList<java.lang.Object>();
		// java.lang.Object _findAllWithOrderPaging_arg0EsmeSmscRoutingsVal1 = null;
		// _findAllWithOrderPaging_arg0EsmeSmscRoutings.add(_findAllWithOrderPaging_arg0EsmeSmscRoutingsVal1);
		// _findAllWithOrderPaging_arg0.getEsmeSmscRoutings().addAll(_findAllWithOrderPaging_arg0EsmeSmscRoutings);
		// _findAllWithOrderPaging_arg0.setPrefixId(8289940289028420709l);
		// _findAllWithOrderPaging_arg0.setPrefixValue("PrefixValue929519908");
		// _findAllWithOrderPaging_arg0.setStatus("Status-212554917");
		// java.lang.String _findAllWithOrderPaging_arg1 = "_findAllWithOrderPaging_arg1-807296291";
		// boolean _findAllWithOrderPaging_arg2 = false;
		// int _findAllWithOrderPaging_arg3 = -854656232;
		// int _findAllWithOrderPaging_arg4 = -1156165031;
		// boolean _findAllWithOrderPaging_arg5 = true;
		// try {
		// java.util.List<com.fis.esme.isdnprefix.EsmeIsdnPrefix> _findAllWithOrderPaging__return = port.findAllWithOrderPaging(_findAllWithOrderPaging_arg0, _findAllWithOrderPaging_arg1,
		// _findAllWithOrderPaging_arg2, _findAllWithOrderPaging_arg3, _findAllWithOrderPaging_arg4, _findAllWithOrderPaging_arg5);
		// System.out.println("findAllWithOrderPaging.result=" + _findAllWithOrderPaging__return);
		//
		// } catch (Exception_Exception e) {
		// System.out.println("Expected exception: Exception has occurred.");
		// System.out.println(e.toString());
		// }
		// }
		// {
		// System.out.println("Invoking findAllWithoutParameter...");
		// try {
		// java.util.List<com.fis.esme.isdnprefix.EsmeIsdnPrefix> _findAllWithoutParameter__return = port.findAllWithoutParameter();
		// System.out.println("findAllWithoutParameter.result=" + _findAllWithoutParameter__return);
		//
		// } catch (Exception_Exception e) {
		// System.out.println("Expected exception: Exception has occurred.");
		// System.out.println(e.toString());
		// }
		// }
		// {
		// System.out.println("Invoking add...");
		// com.fis.esme.isdnprefix.EsmeIsdnPrefix _add_arg0 = new com.fis.esme.isdnprefix.EsmeIsdnPrefix();
		// _add_arg0.setDescription("Description1364781710");
		// java.util.List<java.lang.Object> _add_arg0EsmeSmscRoutings = new java.util.ArrayList<java.lang.Object>();
		// java.lang.Object _add_arg0EsmeSmscRoutingsVal1 = null;
		// _add_arg0EsmeSmscRoutings.add(_add_arg0EsmeSmscRoutingsVal1);
		// _add_arg0.getEsmeSmscRoutings().addAll(_add_arg0EsmeSmscRoutings);
		// _add_arg0.setPrefixId(6690233005794485465l);
		// _add_arg0.setPrefixValue("PrefixValue1572295090");
		// _add_arg0.setStatus("Status1190409765");
		// try {
		// java.lang.Long _add__return = port.add(_add_arg0);
		// System.out.println("add.result=" + _add__return);
		//
		// } catch (Exception_Exception e) {
		// System.out.println("Expected exception: Exception has occurred.");
		// System.out.println(e.toString());
		// }
		// }
		// {
		// System.out.println("Invoking checkConstraints...");
		// java.lang.Long _checkConstraints_arg0 = Long.valueOf(-8922351668622065481l);
		// boolean _checkConstraints__return = port.checkConstraints(_checkConstraints_arg0);
		// System.out.println("checkConstraints.result=" + _checkConstraints__return);
		//
		//
		// }
		// {
		// System.out.println("Invoking delete...");
		// com.fis.esme.isdnprefix.EsmeIsdnPrefix _delete_arg0 = new com.fis.esme.isdnprefix.EsmeIsdnPrefix();
		// _delete_arg0.setDescription("Description-1295492384");
		// java.util.List<java.lang.Object> _delete_arg0EsmeSmscRoutings = new java.util.ArrayList<java.lang.Object>();
		// java.lang.Object _delete_arg0EsmeSmscRoutingsVal1 = null;
		// _delete_arg0EsmeSmscRoutings.add(_delete_arg0EsmeSmscRoutingsVal1);
		// _delete_arg0.getEsmeSmscRoutings().addAll(_delete_arg0EsmeSmscRoutings);
		// _delete_arg0.setPrefixId(8282660874000671941l);
		// _delete_arg0.setPrefixValue("PrefixValue-1049306922");
		// _delete_arg0.setStatus("Status359722683");
		// try {
		// port.delete(_delete_arg0);
		//
		// } catch (Exception_Exception e) {
		// System.out.println("Expected exception: Exception has occurred.");
		// System.out.println(e.toString());
		// }
		// }
		// {
		// System.out.println("Invoking count...");
		// com.fis.esme.isdnprefix.EsmeIsdnPrefix _count_arg0 = new com.fis.esme.isdnprefix.EsmeIsdnPrefix();
		// _count_arg0.setDescription("Description51818805");
		// java.util.List<java.lang.Object> _count_arg0EsmeSmscRoutings = new java.util.ArrayList<java.lang.Object>();
		// java.lang.Object _count_arg0EsmeSmscRoutingsVal1 = null;
		// _count_arg0EsmeSmscRoutings.add(_count_arg0EsmeSmscRoutingsVal1);
		// _count_arg0.getEsmeSmscRoutings().addAll(_count_arg0EsmeSmscRoutings);
		// _count_arg0.setPrefixId(2575063797894306556l);
		// _count_arg0.setPrefixValue("PrefixValue240692170");
		// _count_arg0.setStatus("Status1796001974");
		// boolean _count_arg1 = false;
		// int _count__return = port.count(_count_arg0, _count_arg1);
		// System.out.println("count.result=" + _count__return);
		//
		//
		// }
		// {
		// System.out.println("Invoking checkExisted...");
		// com.fis.esme.isdnprefix.EsmeIsdnPrefix _checkExisted_arg0 = new com.fis.esme.isdnprefix.EsmeIsdnPrefix();
		// _checkExisted_arg0.setDescription("Description463065081");
		// java.util.List<java.lang.Object> _checkExisted_arg0EsmeSmscRoutings = new java.util.ArrayList<java.lang.Object>();
		// java.lang.Object _checkExisted_arg0EsmeSmscRoutingsVal1 = null;
		// _checkExisted_arg0EsmeSmscRoutings.add(_checkExisted_arg0EsmeSmscRoutingsVal1);
		// _checkExisted_arg0.getEsmeSmscRoutings().addAll(_checkExisted_arg0EsmeSmscRoutings);
		// _checkExisted_arg0.setPrefixId(5330196466532930528l);
		// _checkExisted_arg0.setPrefixValue("PrefixValue-1904190358");
		// _checkExisted_arg0.setStatus("Status223861263");
		// int _checkExisted__return = port.checkExisted(_checkExisted_arg0);
		// System.out.println("checkExisted.result=" + _checkExisted__return);
		//
		//
		// }
		// {
		// System.out.println("Invoking update...");
		// com.fis.esme.isdnprefix.EsmeIsdnPrefix _update_arg0 = new com.fis.esme.isdnprefix.EsmeIsdnPrefix();
		// _update_arg0.setDescription("Description-262922103");
		// java.util.List<java.lang.Object> _update_arg0EsmeSmscRoutings = new java.util.ArrayList<java.lang.Object>();
		// java.lang.Object _update_arg0EsmeSmscRoutingsVal1 = null;
		// _update_arg0EsmeSmscRoutings.add(_update_arg0EsmeSmscRoutingsVal1);
		// _update_arg0.getEsmeSmscRoutings().addAll(_update_arg0EsmeSmscRoutings);
		// _update_arg0.setPrefixId(9210495222831913637l);
		// _update_arg0.setPrefixValue("PrefixValue-518654579");
		// _update_arg0.setStatus("Status-1002796760");
		// try {
		// port.update(_update_arg0);
		//
		// } catch (Exception_Exception e) {
		// System.out.println("Expected exception: Exception has occurred.");
		// System.out.println(e.toString());
		// }
		// }

		System.exit(0);
	}

}
