package com.fis.esme.isdnprefix;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.1
 * 2013-12-02T16:04:53.679+07:00
 * Generated source version: 2.4.1
 * 
 */
@WebService(targetNamespace = "http://isdnprefix.esme.fis.com/", name = "IsdnPrefixTransferer")
@XmlSeeAlso({ObjectFactory.class})
public interface IsdnPrefixTransferer {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findAllWithOrderPaging", targetNamespace = "http://isdnprefix.esme.fis.com/", className = "com.fis.esme.isdnprefix.FindAllWithOrderPaging")
    @WebMethod
    @ResponseWrapper(localName = "findAllWithOrderPagingResponse", targetNamespace = "http://isdnprefix.esme.fis.com/", className = "com.fis.esme.isdnprefix.FindAllWithOrderPagingResponse")
    public java.util.List<com.fis.esme.persistence.EsmeIsdnPrefix> findAllWithOrderPaging(
        @WebParam(name = "arg0", targetNamespace = "")
        com.fis.esme.persistence.EsmeIsdnPrefix arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        boolean arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        int arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        int arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        boolean arg5
    ) throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findAllWithoutParameter", targetNamespace = "http://isdnprefix.esme.fis.com/", className = "com.fis.esme.isdnprefix.FindAllWithoutParameter")
    @WebMethod
    @ResponseWrapper(localName = "findAllWithoutParameterResponse", targetNamespace = "http://isdnprefix.esme.fis.com/", className = "com.fis.esme.isdnprefix.FindAllWithoutParameterResponse")
    public java.util.List<com.fis.esme.persistence.EsmeIsdnPrefix> findAllWithoutParameter() throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://isdnprefix.esme.fis.com/", className = "com.fis.esme.isdnprefix.Add")
    @WebMethod
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://isdnprefix.esme.fis.com/", className = "com.fis.esme.isdnprefix.AddResponse")
    public java.lang.Long add(
        @WebParam(name = "arg0", targetNamespace = "")
        com.fis.esme.persistence.EsmeIsdnPrefix arg0
    ) throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "checkConstraints", targetNamespace = "http://isdnprefix.esme.fis.com/", className = "com.fis.esme.isdnprefix.CheckConstraints")
    @WebMethod
    @ResponseWrapper(localName = "checkConstraintsResponse", targetNamespace = "http://isdnprefix.esme.fis.com/", className = "com.fis.esme.isdnprefix.CheckConstraintsResponse")
    public boolean checkConstraints(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Long arg0
    );

    @RequestWrapper(localName = "delete", targetNamespace = "http://isdnprefix.esme.fis.com/", className = "com.fis.esme.isdnprefix.Delete")
    @WebMethod
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://isdnprefix.esme.fis.com/", className = "com.fis.esme.isdnprefix.DeleteResponse")
    public void delete(
        @WebParam(name = "arg0", targetNamespace = "")
        com.fis.esme.persistence.EsmeIsdnPrefix arg0
    ) throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "count", targetNamespace = "http://isdnprefix.esme.fis.com/", className = "com.fis.esme.isdnprefix.Count")
    @WebMethod
    @ResponseWrapper(localName = "countResponse", targetNamespace = "http://isdnprefix.esme.fis.com/", className = "com.fis.esme.isdnprefix.CountResponse")
    public int count(
        @WebParam(name = "arg0", targetNamespace = "")
        com.fis.esme.persistence.EsmeIsdnPrefix arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        boolean arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "checkExisted", targetNamespace = "http://isdnprefix.esme.fis.com/", className = "com.fis.esme.isdnprefix.CheckExisted")
    @WebMethod
    @ResponseWrapper(localName = "checkExistedResponse", targetNamespace = "http://isdnprefix.esme.fis.com/", className = "com.fis.esme.isdnprefix.CheckExistedResponse")
    public int checkExisted(
        @WebParam(name = "arg0", targetNamespace = "")
        com.fis.esme.persistence.EsmeIsdnPrefix arg0
    );

    @RequestWrapper(localName = "update", targetNamespace = "http://isdnprefix.esme.fis.com/", className = "com.fis.esme.isdnprefix.Update")
    @WebMethod
    @ResponseWrapper(localName = "updateResponse", targetNamespace = "http://isdnprefix.esme.fis.com/", className = "com.fis.esme.isdnprefix.UpdateResponse")
    public void update(
        @WebParam(name = "arg0", targetNamespace = "")
        com.fis.esme.persistence.EsmeIsdnPrefix arg0
    ) throws Exception_Exception;
}
