package com.fis.esme.isdnprefix;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.1
 * 2014-11-24T16:03:54.993+07:00
 * Generated source version: 2.4.1
 * 
 */
@WebServiceClient(name = "IsdnPrefixTransfererService", 
                  wsdlLocation = "file:/media/sonhung/MOUNTHERO/FIS-TES/Ubuntu/Ubuntu-FIS-TES-Projects/git-ESME/ESME_Business/WebContent/wsdl/isdnprefixtransferer.wsdl",
                  targetNamespace = "http://isdnprefix.esme.fis.com/") 
public class IsdnPrefixTransfererService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://isdnprefix.esme.fis.com/", "IsdnPrefixTransfererService");
    public final static QName IsdnPrefixTransfererPort = new QName("http://isdnprefix.esme.fis.com/", "IsdnPrefixTransfererPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/media/sonhung/MOUNTHERO/FIS-TES/Ubuntu/Ubuntu-FIS-TES-Projects/git-ESME/ESME_Business/WebContent/wsdl/isdnprefixtransferer.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(IsdnPrefixTransfererService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/media/sonhung/MOUNTHERO/FIS-TES/Ubuntu/Ubuntu-FIS-TES-Projects/git-ESME/ESME_Business/WebContent/wsdl/isdnprefixtransferer.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public IsdnPrefixTransfererService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public IsdnPrefixTransfererService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IsdnPrefixTransfererService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns IsdnPrefixTransferer
     */
    @WebEndpoint(name = "IsdnPrefixTransfererPort")
    public IsdnPrefixTransferer getIsdnPrefixTransfererPort() {
        return super.getPort(IsdnPrefixTransfererPort, IsdnPrefixTransferer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IsdnPrefixTransferer
     */
    @WebEndpoint(name = "IsdnPrefixTransfererPort")
    public IsdnPrefixTransferer getIsdnPrefixTransfererPort(WebServiceFeature... features) {
        return super.getPort(IsdnPrefixTransfererPort, IsdnPrefixTransferer.class, features);
    }

}
