
package com.fis.esme.smscrouting.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.4.1
 * Wed Dec 11 17:15:48 ICT 2013
 * Generated source version: 2.4.1
 */

@XmlRootElement(name = "findAllWithoutParameterResponse", namespace = "http://smscrouting.esme.fis.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "findAllWithoutParameterResponse", namespace = "http://smscrouting.esme.fis.com/")

public class FindAllWithoutParameterResponse {

    @XmlElement(name = "return")
    private java.util.List<com.fis.esme.persistence.EsmeSmscRouting> _return;

    public java.util.List<com.fis.esme.persistence.EsmeSmscRouting> getReturn() {
        return this._return;
    }

    public void setReturn(java.util.List<com.fis.esme.persistence.EsmeSmscRouting> new_return)  {
        this._return = new_return;
    }

}

