package com.fis.esme.bo.impl;

import java.util.List;

import com.fis.esme.bo.ApParamBo;
import com.fis.esme.dao.ApParamDao;
import com.fis.esme.persistence.ApParam;
import com.fis.framework.bo.GenericBoImp;

// Generated Apr 26, 2011 6:00:02 PM by Hibernate Tools 3.2.4.GA

/**
 * AccessNumber generated by hbm2java
 */
public class ApParamBoImpl extends
		GenericBoImp<ApParam, String, ApParamDao> implements
		ApParamBo {

	@Override
	public int checkExited(ApParam prcService) throws Exception {
		return getDaoInternal().checkExited(prcService);
	}

	@Override
	public boolean checkConstraints(String id) throws Exception {
		return getDaoInternal().checkConstraints(id);
	}

	@Override
	public List<ApParam> findAll(ApParam apParam) throws Exception {
		return getDaoInternal().findAll(apParam);
	}

	@Override
	public List<ApParam> findAll(ApParam apParam, int firstItemIndex,
			int maxItems) throws Exception {
		return getDaoInternal().findAll(apParam, firstItemIndex, maxItems);
	}

	@Override
	public List<ApParam> findAll(ApParam apParam, boolean exactMatch)
			throws Exception {
		return getDaoInternal().findAll(apParam, exactMatch);
	}

	@Override
	public List<ApParam> findAll(ApParam apParam, int firstItemIndex,
			int maxItems, boolean exactMatch) throws Exception {
		return getDaoInternal().findAll(apParam, firstItemIndex, maxItems,
				exactMatch);
	}

	@Override
	public List<ApParam> findAll(ApParam apParam, String sortedColumn,
			boolean ascSorted, int firstItemIndex, int maxItems,
			boolean exactMatch) throws Exception {
		return getDaoInternal().findAll(apParam, sortedColumn, ascSorted,
				firstItemIndex, maxItems, exactMatch);
	}

	@Override
	public int countAll() throws Exception {
		return getDaoInternal().countAll();
	}

	@Override
	public int count(ApParam apParam, boolean exactMatch)
			throws Exception {
		return getDaoInternal().count(apParam, exactMatch);
	}

}
