package com.fis.esme.bo.impl;

import java.util.List;

import com.fis.esme.bo.EsmeMessageContentBo;
import com.fis.esme.dao.EsmeMessageContentDao;
import com.fis.esme.persistence.EsmeMessageContent;
import com.fis.framework.bo.GenericBoImp;

// Generated Apr 26, 2011 6:00:02 PM by Hibernate Tools 3.2.4.GA

/**
 * AccessNumber generated by hbm2java
 */
public class EsmeMessageContentBoImpl extends
		GenericBoImp<EsmeMessageContent, Long, EsmeMessageContentDao> implements
		EsmeMessageContentBo {

	@Override
	public int checkExited(EsmeMessageContent esmeMessage) throws Exception {
		return getDaoInternal().checkExited(esmeMessage);
	}

	@Override
	public boolean checkConstraints(Long id) throws Exception {
		return getDaoInternal().checkConstraints(id);
	}

	@Override
	public List<EsmeMessageContent> findAll(EsmeMessageContent esmeMessage) throws Exception {
		return getDaoInternal().findAll(esmeMessage);
	}

	@Override
	public List<EsmeMessageContent> findAll(EsmeMessageContent esmeMessage, int firstItemIndex,
			int maxItems) throws Exception {
		return getDaoInternal().findAll(esmeMessage, firstItemIndex, maxItems);
	}

	@Override
	public List<EsmeMessageContent> findAll(EsmeMessageContent esmeMessage, boolean exactMatch)
			throws Exception {
		return getDaoInternal().findAll(esmeMessage, exactMatch);
	}

	@Override
	public List<EsmeMessageContent> findAll(EsmeMessageContent esmeMessage, int firstItemIndex,
			int maxItems, boolean exactMatch) throws Exception {
		return getDaoInternal().findAll(esmeMessage, firstItemIndex, maxItems,
				exactMatch);
	}

	@Override
	public List<EsmeMessageContent> findAll(EsmeMessageContent esmeMessage, String sortedColumn,
			boolean ascSorted, int firstItemIndex, int maxItems,
			boolean exactMatch) throws Exception {
		return getDaoInternal().findAll(esmeMessage, sortedColumn, ascSorted,
				firstItemIndex, maxItems, exactMatch);
	}

	@Override
	public int countAll() throws Exception {
		return getDaoInternal().countAll();
	}

	@Override
	public int count(EsmeMessageContent esmeMessage, boolean exactMatch)
			throws Exception {
		return getDaoInternal().count(esmeMessage, exactMatch);
	}

	@Override
	public int deleteByMessageId(long messageId) throws Exception {
		
		return getDaoInternal().deleteByMessageId(messageId);
	}

	@Override
	public List<EsmeMessageContent> findByMessageId(long messageId)
			throws Exception {
		
		return getDaoInternal().findByMessageId(messageId);
	}

	@Override
	public EsmeMessageContent findByMessageIdAndLanguageId(long messageId,
			long languageId) throws Exception {
		
		return getDaoInternal().findByMessageIdAndLanguageId(messageId, languageId);
	}

}
