package com.fis.esme.bo.impl;

import java.util.List;

import com.fis.esme.bo.EsmeLanguageBo;
import com.fis.esme.dao.EsmeLanguageDao;
import com.fis.esme.persistence.EsmeLanguage;
import com.fis.framework.bo.GenericBoImp;

// Generated Apr 26, 2011 6:00:02 PM by Hibernate Tools 3.2.4.GA

/**
 * AccessNumber generated by hbm2java
 */
public class EsmeLanguageBoImpl extends
		GenericBoImp<EsmeLanguage, Long, EsmeLanguageDao> implements
		EsmeLanguageBo {

	@Override
	public int checkExited(EsmeLanguage esmeLanguage) throws Exception {
		return getDaoInternal().checkExited(esmeLanguage);
	}

	@Override
	public boolean checkConstraints(Long id) throws Exception {
		return getDaoInternal().checkConstraints(id);
	}

	@Override
	public List<EsmeLanguage> findAll(EsmeLanguage esmeLanguage) throws Exception {
		return getDaoInternal().findAll(esmeLanguage);
	}

	@Override
	public List<EsmeLanguage> findAll(EsmeLanguage esmeLanguage, int firstItemIndex,
			int maxItems) throws Exception {
		return getDaoInternal().findAll(esmeLanguage, firstItemIndex, maxItems);
	}

	@Override
	public List<EsmeLanguage> findAll(EsmeLanguage esmeLanguage, boolean exactMatch)
			throws Exception {
		return getDaoInternal().findAll(esmeLanguage, exactMatch);
	}

	@Override
	public List<EsmeLanguage> findAll(EsmeLanguage esmeLanguage, int firstItemIndex,
			int maxItems, boolean exactMatch) throws Exception {
		return getDaoInternal().findAll(esmeLanguage, firstItemIndex, maxItems,
				exactMatch);
	}

	@Override
	public List<EsmeLanguage> findAll(EsmeLanguage esmeLanguage, String sortedColumn,
			boolean ascSorted, int firstItemIndex, int maxItems,
			boolean exactMatch) throws Exception {
		return getDaoInternal().findAll(esmeLanguage, sortedColumn, ascSorted,
				firstItemIndex, maxItems, exactMatch);
	}

	@Override
	public int countAll() throws Exception {
		return getDaoInternal().countAll();
	}

	@Override
	public int count(EsmeLanguage esmeLanguage, boolean exactMatch)
			throws Exception {
		return getDaoInternal().count(esmeLanguage, exactMatch);
	}

	@Override
	public void updateAllLanguage(EsmeLanguage language,String field, String value) throws Exception {
		
		getDaoInternal().updateAllLanguage( field, value);
		getDaoInternal().update(language);
	}

	@Override
	public EsmeLanguage getDefaultLanguage() throws Exception {
		
		return getDaoInternal().getDefaultLanguage();
	}

	@Override
	public List<EsmeLanguage> getLanguageStatus() {
		
		return getDaoInternal().getLanguageStatus();
	}

}
