package com.fis.esme.bo.impl;

import java.util.Date;
import java.util.List;

import com.fis.esme.bo.EsmeSmsLogBo;
import com.fis.esme.dao.EsmeSmsLogDao;
import com.fis.esme.persistence.EsmeServices;
import com.fis.esme.persistence.EsmeShortCode;
import com.fis.esme.persistence.EsmeSmsCommand;
import com.fis.esme.persistence.EsmeSmsLog;
import com.fis.esme.persistence.SubSearchDetail;
import com.fis.framework.bo.GenericBoImp;

// Generated Apr 26, 2011 6:00:02 PM by Hibernate Tools 3.2.4.GA

/**
 * AccessNumber generated by hbm2java
 */
public class EsmeSmsLogBoImpl extends
		GenericBoImp<EsmeSmsLog, Long, EsmeSmsLogDao> implements EsmeSmsLogBo {

	@Override
	public int checkExited(EsmeSmsLog prcService) throws Exception {
		return getDaoInternal().checkExited(prcService);
	}

	@Override
	public boolean checkConstraints(Long id) throws Exception {
		return getDaoInternal().checkConstraints(id);
	}

	@Override
	public List<EsmeSmsLog> findAll(EsmeSmsLog prcService) throws Exception {
		return getDaoInternal().findAll(prcService);
	}

	@Override
	public List<EsmeSmsLog> findAll(EsmeSmsLog prcService, int firstItemIndex,
			int maxItems) throws Exception {
		return getDaoInternal().findAll(prcService, firstItemIndex, maxItems);
	}

	@Override
	public List<EsmeSmsLog> findAll(EsmeSmsLog prcService, boolean exactMatch)
			throws Exception {
		return getDaoInternal().findAll(prcService, exactMatch);
	}

	@Override
	public List<EsmeSmsLog> findAll(EsmeSmsLog prcService, int firstItemIndex,
			int maxItems, boolean exactMatch) throws Exception {
		return getDaoInternal().findAll(prcService, firstItemIndex, maxItems,
				exactMatch);
	}

	@Override
	public List<EsmeSmsLog> findAll(EsmeSmsLog prcService, String sortedColumn,
			boolean ascSorted, int firstItemIndex, int maxItems,
			boolean exactMatch) throws Exception {
		return getDaoInternal().findAll(prcService, sortedColumn, ascSorted,
				firstItemIndex, maxItems, exactMatch);
	}

	@Override
	public int countAll() throws Exception {
		return getDaoInternal().countAll();
	}

	@Override
	public int count(EsmeSmsLog prcService, boolean exactMatch)
			throws Exception {
		return getDaoInternal().count(prcService, exactMatch);
	}

	public List<EsmeSmsLog> lookUpInfo(String msisdn, Date strFromDate,
			Date strToDate, String serviceId, String commandId,
			String shortCodeId) throws Exception {
		return getDaoInternal().lookUpInfo(msisdn, strFromDate, strToDate,
				serviceId, commandId, shortCodeId);
	}

	public List<EsmeServices> getServiceActive() throws Exception {
		return getDaoInternal().getServiceActive();
	}

	public List<EsmeSmsCommand> getCommandActive() throws Exception {
		return getDaoInternal().getCommandActive();
	}

	public List<EsmeShortCode> getShortCodeActive() throws Exception {
		return getDaoInternal().getShortCodeActive();
	}

	public List<EsmeSmsLog> reportInfo(Date strFromDate, Date strToDate,
			String serviceId, String commandId, String shortCodeId)
			throws Exception {
		return getDaoInternal().reportInfo(strFromDate, strToDate, serviceId,
				commandId, shortCodeId);
	}

	@Override
	public List<EsmeSmsLog> findAll(SubSearchDetail searchEntity,
			EsmeSmsLog esmeSmsLog) throws Exception {

		return getDaoInternal().findAll(searchEntity, esmeSmsLog);
	}

	@Override
	public List<EsmeSmsLog> findAll(SubSearchDetail searchEntity,
			EsmeSmsLog esmeSmsLog, String sortedColumn, boolean ascSorted,
			int firstItemIndex, int maxItems, boolean exactMatch)
			throws Exception {

		return getDaoInternal().findAll(searchEntity, esmeSmsLog, sortedColumn,
				ascSorted, firstItemIndex, maxItems, exactMatch);
	}

	@Override
	public int count(SubSearchDetail searchEntity, EsmeSmsLog esmeSmsLog,
			boolean exactMatch) throws Exception {

		return getDaoInternal().count(searchEntity, esmeSmsLog, exactMatch);
	}
}
