package com.fis.esme.bo.impl;

import java.util.List;

import com.fis.esme.bo.EsmeSmscBo;
import com.fis.esme.dao.EsmeSmscDao;
import com.fis.esme.dao.EsmeSmscParamDao;
import com.fis.esme.persistence.EsmeSmsc;
import com.fis.esme.persistence.EsmeSmscParam;
import com.fis.framework.bo.GenericBoImp;
import com.fis.framework.dao.DaoFactory;

// Generated Apr 26, 2011 6:00:02 PM by Hibernate Tools 3.2.4.GA

/**
 * AccessNumber generated by hbm2java
 */
public class EsmeSmscBoImpl extends GenericBoImp<EsmeSmsc, Long, EsmeSmscDao>
		implements EsmeSmscBo {

	@Override
	public int checkExited(EsmeSmsc prcService) throws Exception {
		return getDaoInternal().checkExited(prcService);
	}

	@Override
	public boolean checkConstraints(Long id) throws Exception {
		return getDaoInternal().checkConstraints(id);
	}

	@Override
	public List<EsmeSmsc> findAll(EsmeSmsc prcService) throws Exception {
		return getDaoInternal().findAll(prcService);
	}

	@Override
	public List<EsmeSmsc> findAll(EsmeSmsc prcService, int firstItemIndex,
			int maxItems) throws Exception {
		return getDaoInternal().findAll(prcService, firstItemIndex, maxItems);
	}

	@Override
	public List<EsmeSmsc> findAll(EsmeSmsc prcService, boolean exactMatch)
			throws Exception {
		return getDaoInternal().findAll(prcService, exactMatch);
	}

	@Override
	public List<EsmeSmsc> findAll(EsmeSmsc prcService, int firstItemIndex,
			int maxItems, boolean exactMatch) throws Exception {
		return getDaoInternal().findAll(prcService, firstItemIndex, maxItems,
				exactMatch);
	}

	@Override
	public List<EsmeSmsc> findAll(EsmeSmsc prcService, String sortedColumn,
			boolean ascSorted, int firstItemIndex, int maxItems,
			boolean exactMatch) throws Exception {
		return getDaoInternal().findAll(prcService, sortedColumn, ascSorted,
				firstItemIndex, maxItems, exactMatch);
	}

	@Override
	public int countAll() throws Exception {
		return getDaoInternal().countAll();
	}

	@Override
	public int count(EsmeSmsc prcService, boolean exactMatch) throws Exception {
		return getDaoInternal().count(prcService, exactMatch);
	}

	@Override
	public List<EsmeSmscParam> addCopyDataParam(EsmeSmsc copyData,
			EsmeSmsc esmeServices) throws Exception {
		// TODO Auto-generated method stub
		EsmeSmscParamDao dao=DaoFactory.createDao(EsmeSmscParamDao.class);
		List<EsmeSmscParam> lst = getDaoInternal().addCopyDataParam(copyData);
		if (lst != null) {
			for (int i = 0; i < lst.size(); i++) {
				EsmeSmscParam pr = lst.get(i);
				pr.setSmscId(esmeServices);
				Long ind=dao.persist(pr);
				System.out.println(ind);
			}
			return lst;
		}
		return null;
	}

}
