package com.fis.esme.bo.impl;

import java.util.List;

import com.fis.esme.bo.EsmeSmscParamBo;
import com.fis.esme.dao.EsmeSmscParamDao;
import com.fis.esme.persistence.EsmeSmscParam;
import com.fis.framework.bo.GenericBoImp;

// Generated Apr 26, 2011 6:00:02 PM by Hibernate Tools 3.2.4.GA

/**
 * AccessNumber generated by hbm2java
 */
public class EsmeSmscParamBoImpl extends
		GenericBoImp<EsmeSmscParam, Long, EsmeSmscParamDao> implements
		EsmeSmscParamBo {

	@Override
	public int checkExited(EsmeSmscParam prcService) throws Exception {
		return getDaoInternal().checkExited(prcService);
	}

	@Override
	public boolean checkConstraints(Long id) throws Exception {
		return getDaoInternal().checkConstraints(id);
	}

	@Override
	public List<EsmeSmscParam> findAll(EsmeSmscParam prcService)
			throws Exception {
		return getDaoInternal().findAll(prcService);
	}

	@Override
	public List<EsmeSmscParam> findAll(EsmeSmscParam prcService,
			int firstItemIndex, int maxItems) throws Exception {
		return getDaoInternal().findAll(prcService, firstItemIndex, maxItems);
	}

	@Override
	public List<EsmeSmscParam> findAll(EsmeSmscParam prcService,
			boolean exactMatch) throws Exception {
		return getDaoInternal().findAll(prcService, exactMatch);
	}

	@Override
	public List<EsmeSmscParam> findAll(EsmeSmscParam prcService,
			int firstItemIndex, int maxItems, boolean exactMatch)
			throws Exception {
		return getDaoInternal().findAll(prcService, firstItemIndex, maxItems,
				exactMatch);
	}

	@Override
	public List<EsmeSmscParam> findAll(EsmeSmscParam prcService,
			String sortedColumn, boolean ascSorted, int firstItemIndex,
			int maxItems, boolean exactMatch) throws Exception {
		return getDaoInternal().findAll(prcService, sortedColumn, ascSorted,
				firstItemIndex, maxItems, exactMatch);
	}

	@Override
	public int countAll() throws Exception {
		return getDaoInternal().countAll();
	}

	@Override
	public int count(EsmeSmscParam prcService, boolean exactMatch)
			throws Exception {
		return getDaoInternal().count(prcService, exactMatch);
	}
	@Override
	public void update(EsmeSmscParam oldObj, EsmeSmscParam newObj)
			throws Exception {
		getDaoInternal().update(oldObj, newObj);
	}
}
