package com.fis.esme.bo.impl;

import java.util.List;

import com.fis.esme.bo.EsmeShortCodeBo;
import com.fis.esme.dao.EsmeShortCodeDao;
import com.fis.esme.persistence.EsmeShortCode;
import com.fis.framework.bo.GenericBoImp;

// Generated Apr 26, 2011 6:00:02 PM by Hibernate Tools 3.2.4.GA

/**
 * AccessNumber generated by hbm2java
 */
public class EsmeShortCodeBoImpl extends
		GenericBoImp<EsmeShortCode, Long, EsmeShortCodeDao> implements
		EsmeShortCodeBo{

	@Override
	public int checkExited(EsmeShortCode esmeShortCode) throws Exception {
		return getDaoInternal().checkExited(esmeShortCode);
	}

	@Override
	public boolean checkConstraints(Long id) throws Exception {
		return getDaoInternal().checkConstraints(id);
	}

	@Override
	public List<EsmeShortCode> findAll(EsmeShortCode esmeShortCode) throws Exception {
		return getDaoInternal().findAll(esmeShortCode);
	}

	@Override
	public List<EsmeShortCode> findAll(EsmeShortCode esmeShortCode, int firstItemIndex,
			int maxItems) throws Exception {
		return getDaoInternal().findAll(esmeShortCode, firstItemIndex, maxItems);
	}

	@Override
	public List<EsmeShortCode> findAll(EsmeShortCode esmeShortCode, boolean exactMatch)
			throws Exception {
		return getDaoInternal().findAll(esmeShortCode, exactMatch);
	}

	@Override
	public List<EsmeShortCode> findAll(EsmeShortCode esmeShortCode, int firstItemIndex,
			int maxItems, boolean exactMatch) throws Exception {
		return getDaoInternal().findAll(esmeShortCode, firstItemIndex, maxItems,
				exactMatch);
	}

	@Override
	public List<EsmeShortCode> findAll(EsmeShortCode esmeShortCode, String sortedColumn,
			boolean ascSorted, int firstItemIndex, int maxItems,
			boolean exactMatch) throws Exception {
		return getDaoInternal().findAll(esmeShortCode, sortedColumn, ascSorted,
				firstItemIndex, maxItems, exactMatch);
	}

	@Override
	public int countAll() throws Exception {
		return getDaoInternal().countAll();
	}

	@Override
	public int count(EsmeShortCode esmeShortCode, boolean exactMatch)
			throws Exception {
		return getDaoInternal().count(esmeShortCode, exactMatch);
	}

}
