package com.fis.esme.bo.impl;

import java.util.List;

import com.fis.esme.bo.EsmeCPBo;
import com.fis.esme.dao.EsmeCPDao;
import com.fis.esme.persistence.EsmeCp;
import com.fis.framework.bo.GenericBoImp;

// Generated Apr 26, 2011 6:00:02 PM by Hibernate Tools 3.2.4.GA

/**
 * AccessNumber generated by hbm2java
 */
public class EsmeCpBoImpl extends
		GenericBoImp<EsmeCp, Long, EsmeCPDao> implements
		EsmeCPBo {

	@Override
	public int checkExited(EsmeCp esmeCp) throws Exception {
		return getDaoInternal().checkExited(esmeCp);
	}

	@Override
	public boolean checkConstraints(Long id) throws Exception {
		return getDaoInternal().checkConstraints(id);
	}

	@Override
	public List<EsmeCp> findAll(EsmeCp esmeCp) throws Exception {
		return getDaoInternal().findAll(esmeCp);
	}

	@Override
	public List<EsmeCp> findAll(EsmeCp esmeCp, int firstItemIndex,
			int maxItems) throws Exception {
		return getDaoInternal().findAll(esmeCp, firstItemIndex, maxItems);
	}

	@Override
	public List<EsmeCp> findAll(EsmeCp esmeCp, boolean exactMatch)
			throws Exception {
		return getDaoInternal().findAll(esmeCp, exactMatch);
	}

	@Override
	public List<EsmeCp> findAll(EsmeCp esmeCp, int firstItemIndex,
			int maxItems, boolean exactMatch) throws Exception {
		return getDaoInternal().findAll(esmeCp, firstItemIndex, maxItems,
				exactMatch);
	}

	@Override
	public List<EsmeCp> findAll(EsmeCp esmeCp, String sortedColumn,
			boolean ascSorted, int firstItemIndex, int maxItems,
			boolean exactMatch) throws Exception {
		return getDaoInternal().findAll(esmeCp, sortedColumn, ascSorted,
				firstItemIndex, maxItems, exactMatch);
	}

	@Override
	public int countAll() throws Exception {
		return getDaoInternal().countAll();
	}

	@Override
	public int count(EsmeCp esmeCp, boolean exactMatch)
			throws Exception {
		return getDaoInternal().count(esmeCp, exactMatch);
	}

}
