package com.fis.esme.bo.impl;

import java.util.List;

import com.fis.esme.bo.EsmeIsdnPrefixBo;
import com.fis.esme.dao.EsmeIsdnPrefixDao;
import com.fis.esme.persistence.EsmeIsdnPrefix;
import com.fis.framework.bo.GenericBoImp;

// Generated Apr 26, 2011 6:00:02 PM by Hibernate Tools 3.2.4.GA

/**
 * AccessNumber generated by hbm2java
 */
public class EsmeIsdnPrefixBoImpl extends
		GenericBoImp<EsmeIsdnPrefix, Long, EsmeIsdnPrefixDao> implements
		EsmeIsdnPrefixBo {

	@Override
	public int checkExited(EsmeIsdnPrefix prcService) throws Exception {
		return getDaoInternal().checkExited(prcService);
	}

	@Override
	public boolean checkConstraints(Long id) throws Exception {
		return getDaoInternal().checkConstraints(id);
	}

	@Override
	public List<EsmeIsdnPrefix> findAll(EsmeIsdnPrefix prcService) throws Exception {
		return getDaoInternal().findAll(prcService);
	}

	@Override
	public List<EsmeIsdnPrefix> findAll(EsmeIsdnPrefix prcService, int firstItemIndex,
			int maxItems) throws Exception {
		return getDaoInternal().findAll(prcService, firstItemIndex, maxItems);
	}

	@Override
	public List<EsmeIsdnPrefix> findAll(EsmeIsdnPrefix prcService, boolean exactMatch)
			throws Exception {
		return getDaoInternal().findAll(prcService, exactMatch);
	}

	@Override
	public List<EsmeIsdnPrefix> findAll(EsmeIsdnPrefix prcService, int firstItemIndex,
			int maxItems, boolean exactMatch) throws Exception {
		return getDaoInternal().findAll(prcService, firstItemIndex, maxItems,
				exactMatch);
	}

	@Override
	public List<EsmeIsdnPrefix> findAll(EsmeIsdnPrefix prcService, String sortedColumn,
			boolean ascSorted, int firstItemIndex, int maxItems,
			boolean exactMatch) throws Exception {
		return getDaoInternal().findAll(prcService, sortedColumn, ascSorted,
				firstItemIndex, maxItems, exactMatch);
	}

	@Override
	public int countAll() throws Exception {
		return getDaoInternal().countAll();
	}

	@Override
	public int count(EsmeIsdnPrefix prcService, boolean exactMatch)
			throws Exception {
		return getDaoInternal().count(prcService, exactMatch);
	}

}
