package com.fis.esme.bo.impl;

import java.util.Date;
import java.util.List;

import com.fis.esme.bo.EsmeFileUploadBo;
import com.fis.esme.dao.EsmeFileUploadDao;
import com.fis.esme.persistence.EsmeFileUpload;
import com.fis.framework.bo.GenericBoImp;

// Generated Apr 26, 2011 6:00:02 PM by Hibernate Tools 3.2.4.GA

/**
 * AccessNumber generated by hbm2java
 */
public class EsmeFileUploadBoImpl extends
		GenericBoImp<EsmeFileUpload, Long, EsmeFileUploadDao> implements
		EsmeFileUploadBo {

	@Override
	public int checkExited(EsmeFileUpload esmeFileUpload) throws Exception {
		return getDaoInternal().checkExited(esmeFileUpload);
	}

	@Override
	public List<EsmeFileUpload> findAll(EsmeFileUpload esmeFileUpload) throws Exception {
		return getDaoInternal().findAll(esmeFileUpload);
	}

	@Override
	public List<EsmeFileUpload> findAll(EsmeFileUpload esmeFileUpload, int firstItemIndex,
			int maxItems) throws Exception {
		return getDaoInternal().findAll(esmeFileUpload, firstItemIndex, maxItems);
	}

	@Override
	public List<EsmeFileUpload> findAll(EsmeFileUpload esmeFileUpload, boolean exactMatch)
			throws Exception {
		return getDaoInternal().findAll(esmeFileUpload, exactMatch);
	}

	@Override
	public List<EsmeFileUpload> findAll(EsmeFileUpload esmeFileUpload, int firstItemIndex,
			int maxItems, boolean exactMatch) throws Exception {
		return getDaoInternal().findAll(esmeFileUpload, firstItemIndex, maxItems,
				exactMatch);
	}

	@Override
	public List<EsmeFileUpload> findAll(EsmeFileUpload esmeFileUpload, String sortedColumn,
			boolean ascSorted, int firstItemIndex, int maxItems,
			boolean exactMatch) throws Exception {
		return getDaoInternal().findAll(esmeFileUpload, sortedColumn, ascSorted,
				firstItemIndex, maxItems, exactMatch);
	}

	@Override
	public int countAll() throws Exception {
		return getDaoInternal().countAll();
	}

	@Override
	public int count(EsmeFileUpload esmeFileUpload, boolean exactMatch)
			throws Exception {
		return getDaoInternal().count(esmeFileUpload, exactMatch);
	}

	@Override
	public List<EsmeFileUpload> findAllByDate(Date fromDate, Date toDate)
			throws Exception {
		
		return getDaoInternal().findAllByDate(fromDate, toDate);
	}

	@Override
	public List<EsmeFileUpload> findAllInDateByField(String field,
			Date fromDate, Date toDate) throws Exception {
		
		return getDaoInternal().findAllInDateByField(field, fromDate, toDate);
	}

}
