package com.fis.esme.bo.impl;

import java.util.List;

import com.fis.esme.bo.EsmeSmsCommandBo;
import com.fis.esme.dao.EsmeSmsCommandDao;
import com.fis.esme.persistence.EsmeSmsCommand;
import com.fis.framework.bo.GenericBoImp;

// Generated Apr 26, 2011 6:00:02 PM by Hibernate Tools 3.2.4.GA

/**
 * AccessNumber generated by hbm2java
 */
public class EsmeSmsCommandBoImpl extends
		GenericBoImp<EsmeSmsCommand, Long, EsmeSmsCommandDao> implements
		EsmeSmsCommandBo {

	@Override
	public int checkExited(EsmeSmsCommand smsCommand) throws Exception {
		return getDaoInternal().checkExited(smsCommand);
	}

	@Override
	public boolean checkConstraints(Long id) throws Exception {
		return getDaoInternal().checkConstraints(id);
	}

	@Override
	public List<EsmeSmsCommand> findAll(EsmeSmsCommand smsCommand) throws Exception {
		return getDaoInternal().findAll(smsCommand);
	}

	@Override
	public List<EsmeSmsCommand> findAll(EsmeSmsCommand smsCommand, int firstItemIndex,
			int maxItems) throws Exception {
		return getDaoInternal().findAll(smsCommand, firstItemIndex, maxItems);
	}

	@Override
	public List<EsmeSmsCommand> findAll(EsmeSmsCommand smsCommand, boolean exactMatch)
			throws Exception {
		return getDaoInternal().findAll(smsCommand, exactMatch);
	}

	@Override
	public List<EsmeSmsCommand> findAll(EsmeSmsCommand smsCommand, int firstItemIndex,
			int maxItems, boolean exactMatch) throws Exception {
		return getDaoInternal().findAll(smsCommand, firstItemIndex, maxItems,
				exactMatch);
	}

	@Override
	public List<EsmeSmsCommand> findAll(EsmeSmsCommand smsCommand, String sortedColumn,
			boolean ascSorted, int firstItemIndex, int maxItems,
			boolean exactMatch) throws Exception {
		return getDaoInternal().findAll(smsCommand, sortedColumn, ascSorted,
				firstItemIndex, maxItems, exactMatch);
	}

	@Override
	public int countAll() throws Exception {
		return getDaoInternal().countAll();
	}

	@Override
	public int count(EsmeSmsCommand smsCommand, boolean exactMatch)
			throws Exception {
		return getDaoInternal().count(smsCommand, exactMatch);
	}

}
