package com.fis.esme.bo.impl;

import java.util.List;

import com.fis.esme.bo.GroupsBo;
import com.fis.esme.dao.GroupsDao;
import com.fis.esme.persistence.Groups;
import com.fis.framework.bo.GenericBoImp;

// Generated Apr 26, 2011 6:00:02 PM by Hibernate Tools 3.2.4.GA

/**
 * AccessNumber generated by hbm2java
 */
public class GroupsBoImpl extends
		GenericBoImp<Groups, Long, GroupsDao> implements
		GroupsBo {

	@Override
	public int checkExited(Groups Groups) throws Exception {
		return getDaoInternal().checkExited(Groups);
	}

	@Override
	public boolean checkConstraints(Long id) throws Exception {
		return getDaoInternal().checkConstraints(id);
	}

	@Override
	public List<Groups> findAll(Groups Groups) throws Exception {
		return getDaoInternal().findAll(Groups);
	}

	@Override
	public List<Groups> findAll(Groups Groups, int firstItemIndex,
			int maxItems) throws Exception {
		return getDaoInternal().findAll(Groups, firstItemIndex, maxItems);
	}

	@Override
	public List<Groups> findAll(Groups Groups, boolean exactMatch)
			throws Exception {
		return getDaoInternal().findAll(Groups, exactMatch);
	}

	@Override
	public List<Groups> findAll(Groups Groups, int firstItemIndex,
			int maxItems, boolean exactMatch) throws Exception {
		return getDaoInternal().findAll(Groups, firstItemIndex, maxItems,
				exactMatch);
	}

	@Override
	public List<Groups> findAll(Groups Groups, String sortedColumn,
			boolean ascSorted, int firstItemIndex, int maxItems,
			boolean exactMatch) throws Exception {
		return getDaoInternal().findAll(Groups, sortedColumn, ascSorted,
				firstItemIndex, maxItems, exactMatch);
	}

	@Override
	public int countAll() throws Exception {
		return getDaoInternal().countAll();
	}

	@Override
	public int count(Groups Groups, boolean exactMatch)
			throws Exception {
		return getDaoInternal().count(Groups, exactMatch);
	}

	@Override
	public Groups findBySubGgroup(long subId) throws Exception {
		return getDaoInternal().findBySubGgroup(subId);
	}

}
