package com.fis.esme.bo.impl;

import java.util.List;

import com.fis.esme.bo.SubGroupBo;
import com.fis.esme.dao.SubGroupDao;
import com.fis.esme.persistence.SubGroup;
import com.fis.framework.bo.GenericBoImp;

// Generated Apr 26, 2011 6:00:02 PM by Hibernate Tools 3.2.4.GA

/**
 * AccessNumber generated by hbm2java
 */
public class SubGroupBoImpl extends
		GenericBoImp<SubGroup, Long, SubGroupDao> implements
		SubGroupBo {

	@Override
	public int checkExited(SubGroup SubGroup) throws Exception {
		return getDaoInternal().checkExited(SubGroup);
	}

	@Override
	public boolean checkConstraints(Long id) throws Exception {
		return getDaoInternal().checkConstraints(id);
	}

	@Override
	public List<SubGroup> findAll(SubGroup SubGroup) throws Exception {
		return getDaoInternal().findAll(SubGroup);
	}

	@Override
	public List<SubGroup> findAll(SubGroup SubGroup, int firstItemIndex,
			int maxItems) throws Exception {
		return getDaoInternal().findAll(SubGroup, firstItemIndex, maxItems);
	}

	@Override
	public List<SubGroup> findAll(SubGroup SubGroup, boolean exactMatch)
			throws Exception {
		return getDaoInternal().findAll(SubGroup, exactMatch);
	}

	@Override
	public List<SubGroup> findAll(SubGroup SubGroup, int firstItemIndex,
			int maxItems, boolean exactMatch) throws Exception {
		return getDaoInternal().findAll(SubGroup, firstItemIndex, maxItems,
				exactMatch);
	}

	@Override
	public List<SubGroup> findAll(SubGroup SubGroup, String sortedColumn,
			boolean ascSorted, int firstItemIndex, int maxItems,
			boolean exactMatch) throws Exception {
		return getDaoInternal().findAll(SubGroup, sortedColumn, ascSorted,
				firstItemIndex, maxItems, exactMatch);
	}

	@Override
	public int countAll() throws Exception {
		return getDaoInternal().countAll();
	}

	@Override
	public int count(SubGroup SubGroup, boolean exactMatch)
			throws Exception {
		return getDaoInternal().count(SubGroup, exactMatch);
	}

}
