package com.fis.esme.bo.impl;

import java.util.List;

import com.fis.esme.bo.SubscriberBo;
import com.fis.esme.dao.SubscriberDao;
import com.fis.esme.persistence.Groups;
import com.fis.esme.persistence.Subscriber;
import com.fis.framework.bo.GenericBoImp;

// Generated Apr 26, 2011 6:00:02 PM by Hibernate Tools 3.2.4.GA

/**
 * AccessNumber generated by hbm2java
 */
public class SubscriberBoImpl extends GenericBoImp<Subscriber, Long, SubscriberDao> implements SubscriberBo {

	@Override
	public int checkExited(Subscriber prcService) throws Exception {

		return getDaoInternal().checkExited(prcService);
	}

	@Override
	public boolean checkConstraints(Long id) throws Exception {

		return getDaoInternal().checkConstraints(id);
	}

	@Override
	public List<Subscriber> findAll(Subscriber prcService) throws Exception {

		return getDaoInternal().findAll(prcService);
	}

	@Override
	public List<Subscriber> findAll(Subscriber prcService, int firstItemIndex, int maxItems) throws Exception {

		return getDaoInternal().findAll(prcService, firstItemIndex, maxItems);
	}

	@Override
	public List<Subscriber> findAll(Subscriber prcService, boolean exactMatch) throws Exception {

		return getDaoInternal().findAll(prcService, exactMatch);
	}

	@Override
	public List<Subscriber> findAll(Subscriber prcService, int firstItemIndex, int maxItems, boolean exactMatch) throws Exception {

		return getDaoInternal().findAll(prcService, firstItemIndex, maxItems, exactMatch);
	}

	@Override
	public List<Subscriber> findAll(Subscriber prcService, String sortedColumn, boolean ascSorted, int firstItemIndex, int maxItems, boolean exactMatch) throws Exception {

		return getDaoInternal().findAll(prcService, sortedColumn, ascSorted, firstItemIndex, maxItems, exactMatch);
	}

	@Override
	public int countAll() throws Exception {

		return getDaoInternal().countAll();
	}

	@Override
	public int count(Subscriber prcService, boolean exactMatch) throws Exception {

		return getDaoInternal().count(prcService, exactMatch);
	}

	@Override
	public List<Groups> findGroupsBySub(long subId) throws Exception {

		return getDaoInternal().findGroupsBySub(subId);
	}
}
