package com.fis.esme.smsc;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.1
 * 2014-03-06T09:24:06.954+07:00
 * Generated source version: 2.4.1
 * 
 */
@WebServiceClient(name = "SmscTransfererService", 
                  wsdlLocation = "http://localhost:1080/ESME_Business/services/SmscTransfererPort?wsdl",
                  targetNamespace = "http://smsc.esme.fis.com/") 
public class SmscTransfererService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://smsc.esme.fis.com/", "SmscTransfererService");
    public final static QName SmscTransfererPort = new QName("http://smsc.esme.fis.com/", "SmscTransfererPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:1080/ESME_Business/services/SmscTransfererPort?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SmscTransfererService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:1080/ESME_Business/services/SmscTransfererPort?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SmscTransfererService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SmscTransfererService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SmscTransfererService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns SmscTransferer
     */
    @WebEndpoint(name = "SmscTransfererPort")
    public SmscTransferer getSmscTransfererPort() {
        return super.getPort(SmscTransfererPort, SmscTransferer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SmscTransferer
     */
    @WebEndpoint(name = "SmscTransfererPort")
    public SmscTransferer getSmscTransfererPort(WebServiceFeature... features) {
        return super.getPort(SmscTransfererPort, SmscTransferer.class, features);
    }

}
