
package com.fis.esme.fileupload;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.1
 * 2013-12-14T11:28:17.032+07:00
 * Generated source version: 2.4.1
 * 
 */
public final class FileUploadTransferer_FileUploadTransfererPort_Client {

    private static final QName SERVICE_NAME = new QName("http://fileupload.esme.fis.com/", "FileUploadTransfererService");

    private FileUploadTransferer_FileUploadTransfererPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = FileUploadTransfererService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        FileUploadTransfererService ss = new FileUploadTransfererService(wsdlURL, SERVICE_NAME);
        FileUploadTransferer port = ss.getFileUploadTransfererPort();  
        
        System.out.println(""+port.findAllWithoutParameter().size());

        System.exit(0);
    }

}
