package com.fis.esme.fileupload;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.1
 * 2013-12-14T11:28:17.174+07:00
 * Generated source version: 2.4.1
 * 
 */
@WebServiceClient(name = "FileUploadTransfererService", 
                  wsdlLocation = "http://localhost:7080/ESME_Business/services/FileUploadTransfererPort?wsdl",
                  targetNamespace = "http://fileupload.esme.fis.com/") 
public class FileUploadTransfererService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://fileupload.esme.fis.com/", "FileUploadTransfererService");
    public final static QName FileUploadTransfererPort = new QName("http://fileupload.esme.fis.com/", "FileUploadTransfererPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:7080/ESME_Business/services/FileUploadTransfererPort?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(FileUploadTransfererService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:7080/ESME_Business/services/FileUploadTransfererPort?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public FileUploadTransfererService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public FileUploadTransfererService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FileUploadTransfererService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns FileUploadTransferer
     */
    @WebEndpoint(name = "FileUploadTransfererPort")
    public FileUploadTransferer getFileUploadTransfererPort() {
        return super.getPort(FileUploadTransfererPort, FileUploadTransferer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FileUploadTransferer
     */
    @WebEndpoint(name = "FileUploadTransfererPort")
    public FileUploadTransferer getFileUploadTransfererPort(WebServiceFeature... features) {
        return super.getPort(FileUploadTransfererPort, FileUploadTransferer.class, features);
    }

}
