package com.fis.esme.cpsummary;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.1
 * 2013-12-20T10:50:03.744+07:00
 * Generated source version: 2.4.1
 * 
 */
@WebServiceClient(name = "CpSummaryTransfererService", 
                  wsdlLocation = "http://localhost:1080/ESME_Business/services/CpSummaryTransfererPort?wsdl",
                  targetNamespace = "http://cpsummary.esme.fis.com/") 
public class CpSummaryTransfererService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://cpsummary.esme.fis.com/", "CpSummaryTransfererService");
    public final static QName CpSummaryTransfererPort = new QName("http://cpsummary.esme.fis.com/", "CpSummaryTransfererPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:1080/ESME_Business/services/CpSummaryTransfererPort?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CpSummaryTransfererService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:1080/ESME_Business/services/CpSummaryTransfererPort?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CpSummaryTransfererService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CpSummaryTransfererService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CpSummaryTransfererService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns CpSummaryTransferer
     */
    @WebEndpoint(name = "CpSummaryTransfererPort")
    public CpSummaryTransferer getCpSummaryTransfererPort() {
        return super.getPort(CpSummaryTransfererPort, CpSummaryTransferer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CpSummaryTransferer
     */
    @WebEndpoint(name = "CpSummaryTransfererPort")
    public CpSummaryTransferer getCpSummaryTransfererPort(WebServiceFeature... features) {
        return super.getPort(CpSummaryTransfererPort, CpSummaryTransferer.class, features);
    }

}
