package com.fis.esme.cpsummary;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.1
 * 2013-12-20T10:50:03.734+07:00
 * Generated source version: 2.4.1
 * 
 */
@WebService(targetNamespace = "http://cpsummary.esme.fis.com/", name = "CpSummaryTransferer")
@XmlSeeAlso({ObjectFactory.class})
public interface CpSummaryTransferer {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findAllByDateByListField", targetNamespace = "http://cpsummary.esme.fis.com/", className = "com.fis.esme.cpsummary.FindAllByDateByListField")
    @WebMethod
    @ResponseWrapper(localName = "findAllByDateByListFieldResponse", targetNamespace = "http://cpsummary.esme.fis.com/", className = "com.fis.esme.cpsummary.FindAllByDateByListFieldResponse")
    public java.util.List<com.fis.esme.persistence.EsmeDailyCpSummary> findAllByDateByListField(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<java.lang.String> arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.util.Date arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.util.Date arg2
    ) throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findAllByDate", targetNamespace = "http://cpsummary.esme.fis.com/", className = "com.fis.esme.cpsummary.FindAllByDate")
    @WebMethod
    @ResponseWrapper(localName = "findAllByDateResponse", targetNamespace = "http://cpsummary.esme.fis.com/", className = "com.fis.esme.cpsummary.FindAllByDateResponse")
    public java.util.List<com.fis.esme.persistence.EsmeDailyCpSummary> findAllByDate(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.Date arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.util.Date arg1
    ) throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findAllByDateAndId", targetNamespace = "http://cpsummary.esme.fis.com/", className = "com.fis.esme.cpsummary.FindAllByDateAndId")
    @WebMethod
    @ResponseWrapper(localName = "findAllByDateAndIdResponse", targetNamespace = "http://cpsummary.esme.fis.com/", className = "com.fis.esme.cpsummary.FindAllByDateAndIdResponse")
    public java.util.List<com.fis.esme.persistence.EsmeDailyCpSummary> findAllByDateAndId(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Long arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.util.Date arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.util.Date arg2
    ) throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findAllInDateByField", targetNamespace = "http://cpsummary.esme.fis.com/", className = "com.fis.esme.cpsummary.FindAllInDateByField")
    @WebMethod
    @ResponseWrapper(localName = "findAllInDateByFieldResponse", targetNamespace = "http://cpsummary.esme.fis.com/", className = "com.fis.esme.cpsummary.FindAllInDateByFieldResponse")
    public java.util.List<com.fis.esme.persistence.EsmeDailyCpSummary> findAllInDateByField(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.util.Date arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.util.Date arg2
    ) throws Exception_Exception;
}
