package com.fis.esme.commandsummary;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.1
 * 2013-12-20T10:48:11.590+07:00
 * Generated source version: 2.4.1
 * 
 */
@WebServiceClient(name = "CommandSummaryTransfererService", 
                  wsdlLocation = "http://localhost:1080/ESME_Business/services/CommandSummaryTransfererPort?wsdl",
                  targetNamespace = "http://commandsummary.esme.fis.com/") 
public class CommandSummaryTransfererService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://commandsummary.esme.fis.com/", "CommandSummaryTransfererService");
    public final static QName CommandSummaryTransfererPort = new QName("http://commandsummary.esme.fis.com/", "CommandSummaryTransfererPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:1080/ESME_Business/services/CommandSummaryTransfererPort?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CommandSummaryTransfererService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:1080/ESME_Business/services/CommandSummaryTransfererPort?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CommandSummaryTransfererService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CommandSummaryTransfererService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CommandSummaryTransfererService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns CommandSummaryTransferer
     */
    @WebEndpoint(name = "CommandSummaryTransfererPort")
    public CommandSummaryTransferer getCommandSummaryTransfererPort() {
        return super.getPort(CommandSummaryTransfererPort, CommandSummaryTransferer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CommandSummaryTransferer
     */
    @WebEndpoint(name = "CommandSummaryTransfererPort")
    public CommandSummaryTransferer getCommandSummaryTransfererPort(WebServiceFeature... features) {
        return super.getPort(CommandSummaryTransfererPort, CommandSummaryTransferer.class, features);
    }

}
