package com.fis.esme.commandsummary;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.1
 * 2013-12-20T10:48:11.580+07:00
 * Generated source version: 2.4.1
 * 
 */
@WebService(targetNamespace = "http://commandsummary.esme.fis.com/", name = "CommandSummaryTransferer")
@XmlSeeAlso({ObjectFactory.class})
public interface CommandSummaryTransferer {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findAllByDateAndId", targetNamespace = "http://commandsummary.esme.fis.com/", className = "com.fis.esme.commandsummary.FindAllByDateAndId")
    @WebMethod
    @ResponseWrapper(localName = "findAllByDateAndIdResponse", targetNamespace = "http://commandsummary.esme.fis.com/", className = "com.fis.esme.commandsummary.FindAllByDateAndIdResponse")
    public java.util.List<com.fis.esme.persistence.EsmeDailyCommandSummary> findAllByDateAndId(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Long arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.util.Date arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.util.Date arg2
    ) throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findAllByDate", targetNamespace = "http://commandsummary.esme.fis.com/", className = "com.fis.esme.commandsummary.FindAllByDate")
    @WebMethod
    @ResponseWrapper(localName = "findAllByDateResponse", targetNamespace = "http://commandsummary.esme.fis.com/", className = "com.fis.esme.commandsummary.FindAllByDateResponse")
    public java.util.List<com.fis.esme.persistence.EsmeDailyCommandSummary> findAllByDate(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.Date arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.util.Date arg1
    ) throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findAllInDateByField", targetNamespace = "http://commandsummary.esme.fis.com/", className = "com.fis.esme.commandsummary.FindAllInDateByField")
    @WebMethod
    @ResponseWrapper(localName = "findAllInDateByFieldResponse", targetNamespace = "http://commandsummary.esme.fis.com/", className = "com.fis.esme.commandsummary.FindAllInDateByFieldResponse")
    public java.util.List<com.fis.esme.persistence.EsmeDailyCommandSummary> findAllInDateByField(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.util.Date arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.util.Date arg2
    ) throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findAllByDateByListField", targetNamespace = "http://commandsummary.esme.fis.com/", className = "com.fis.esme.commandsummary.FindAllByDateByListField")
    @WebMethod
    @ResponseWrapper(localName = "findAllByDateByListFieldResponse", targetNamespace = "http://commandsummary.esme.fis.com/", className = "com.fis.esme.commandsummary.FindAllByDateByListFieldResponse")
    public java.util.List<com.fis.esme.persistence.EsmeDailyCommandSummary> findAllByDateByListField(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<java.lang.String> arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.util.Date arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.util.Date arg2
    ) throws Exception_Exception;
}
