package com.fis.esme.form;

/**
 * PamAction generated by hbm2java
 */
public class WeeklyTable implements java.io.Serializable {

	private String name;
	private boolean select;

	public WeeklyTable() {
	}

	public WeeklyTable(String name, boolean select) {
		super();
		this.name = name;
		this.select = select;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public boolean isSelect() {
		return select;
	}

	public void setSelect(boolean select) {
		this.select = select;
	}

}
