
package com.fis.esme.shortcode.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.4.1
 * Thu Nov 28 11:21:29 ICT 2013
 * Generated source version: 2.4.1
 */

@XmlRootElement(name = "findAllWithoutParameter", namespace = "http://shortcode.esme.fis.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "findAllWithoutParameter", namespace = "http://shortcode.esme.fis.com/")

public class FindAllWithoutParameter {


}

