
package com.fis.esme.smslog.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.4.1
 * Tue Nov 25 10:20:52 ICT 2014
 * Generated source version: 2.4.1
 */

@XmlRootElement(name = "count", namespace = "http://smslog.esme.fis.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "count", namespace = "http://smslog.esme.fis.com/", propOrder = {"arg0", "arg1", "arg2"})

public class Count {

    @XmlElement(name = "arg0")
    private com.fis.esme.persistence.SubSearchDetail arg0;
    @XmlElement(name = "arg1")
    private com.fis.esme.persistence.EsmeSmsLog arg1;
    @XmlElement(name = "arg2")
    private boolean arg2;

    public com.fis.esme.persistence.SubSearchDetail getArg0() {
        return this.arg0;
    }

    public void setArg0(com.fis.esme.persistence.SubSearchDetail newArg0)  {
        this.arg0 = newArg0;
    }

    public com.fis.esme.persistence.EsmeSmsLog getArg1() {
        return this.arg1;
    }

    public void setArg1(com.fis.esme.persistence.EsmeSmsLog newArg1)  {
        this.arg1 = newArg1;
    }

    public boolean getArg2() {
        return this.arg2;
    }

    public void setArg2(boolean newArg2)  {
        this.arg2 = newArg2;
    }

}

