
package com.fis.esme.smslog.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.4.1
 * Mon Mar 31 11:15:37 ICT 2014
 * Generated source version: 2.4.1
 */

@XmlRootElement(name = "reportInfo", namespace = "http://smslog.esme.fis.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "reportInfo", namespace = "http://smslog.esme.fis.com/", propOrder = {"arg0", "arg1", "arg2", "arg3", "arg4"})

public class ReportInfo {

    @XmlElement(name = "arg0")
    private java.util.Date arg0;
    @XmlElement(name = "arg1")
    private java.util.Date arg1;
    @XmlElement(name = "arg2")
    private java.lang.String arg2;
    @XmlElement(name = "arg3")
    private java.lang.String arg3;
    @XmlElement(name = "arg4")
    private java.lang.String arg4;

    public java.util.Date getArg0() {
        return this.arg0;
    }

    public void setArg0(java.util.Date newArg0)  {
        this.arg0 = newArg0;
    }

    public java.util.Date getArg1() {
        return this.arg1;
    }

    public void setArg1(java.util.Date newArg1)  {
        this.arg1 = newArg1;
    }

    public java.lang.String getArg2() {
        return this.arg2;
    }

    public void setArg2(java.lang.String newArg2)  {
        this.arg2 = newArg2;
    }

    public java.lang.String getArg3() {
        return this.arg3;
    }

    public void setArg3(java.lang.String newArg3)  {
        this.arg3 = newArg3;
    }

    public java.lang.String getArg4() {
        return this.arg4;
    }

    public void setArg4(java.lang.String newArg4)  {
        this.arg4 = newArg4;
    }

}

