
package com.fis.esme.message.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.4.1
 * Fri Nov 14 17:24:02 ICT 2014
 * Generated source version: 2.4.1
 */

@XmlRootElement(name = "updateResponse", namespace = "http://message.esme.fis.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "updateResponse", namespace = "http://message.esme.fis.com/")

public class UpdateResponse {


}

