
package com.fis.esme.smscparam.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.4.1
 * Sat Dec 14 11:33:15 ICT 2013
 * Generated source version: 2.4.1
 */

@XmlRootElement(name = "editDetailResponse", namespace = "http://smscparam.esme.fis.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "editDetailResponse", namespace = "http://smscparam.esme.fis.com/")

public class EditDetailResponse {


}

