
package com.fis.esme.smsmt.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.4.1
 * Fri Sep 26 16:35:55 ICT 2014
 * Generated source version: 2.4.1
 */

@XmlRootElement(name = "addMultiProcess", namespace = "http://smsmt.esme.fis.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "addMultiProcess", namespace = "http://smsmt.esme.fis.com/")

public class AddMultiProcess {

    @XmlElement(name = "arg0")
    private java.util.List<com.fis.esme.persistence.EsmeSmsMt> arg0;

    public java.util.List<com.fis.esme.persistence.EsmeSmsMt> getArg0() {
        return this.arg0;
    }

    public void setArg0(java.util.List<com.fis.esme.persistence.EsmeSmsMt> newArg0)  {
        this.arg0 = newArg0;
    }

}

