
package com.fis.esme.smsmt.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.4.1
 * Fri Sep 26 16:35:55 ICT 2014
 * Generated source version: 2.4.1
 */

@XmlRootElement(name = "FindBySmsRouting", namespace = "http://smsmt.esme.fis.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FindBySmsRouting", namespace = "http://smsmt.esme.fis.com/")

public class FindBySmsRouting {

    @XmlElement(name = "arg0")
    private com.fis.esme.persistence.EsmeSmsRouting arg0;

    public com.fis.esme.persistence.EsmeSmsRouting getArg0() {
        return this.arg0;
    }

    public void setArg0(com.fis.esme.persistence.EsmeSmsRouting newArg0)  {
        this.arg0 = newArg0;
    }

}

