
package com.fis.esme.smsmt.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.4.1
 * Fri Sep 26 16:35:55 ICT 2014
 * Generated source version: 2.4.1
 */

@XmlRootElement(name = "updateResponse", namespace = "http://smsmt.esme.fis.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "updateResponse", namespace = "http://smsmt.esme.fis.com/")

public class UpdateResponse {


}

