
package com.fis.esme.language.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.4.1
 * Thu Nov 28 15:04:24 ICT 2013
 * Generated source version: 2.4.1
 */

@XmlRootElement(name = "editResponse", namespace = "http://language.esme.fis.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "editResponse", namespace = "http://language.esme.fis.com/")

public class EditResponse {


}

