
package com.fis.esme.language.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.4.1
 * Thu Nov 28 15:04:24 ICT 2013
 * Generated source version: 2.4.1
 */

@XmlRootElement(name = "getDefaultLanguageResponse", namespace = "http://language.esme.fis.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getDefaultLanguageResponse", namespace = "http://language.esme.fis.com/")

public class GetDefaultLanguageResponse {

    @XmlElement(name = "return")
    private com.fis.esme.persistence.EsmeLanguage _return;

    public com.fis.esme.persistence.EsmeLanguage getReturn() {
        return this._return;
    }

    public void setReturn(com.fis.esme.persistence.EsmeLanguage new_return)  {
        this._return = new_return;
    }

}

