
package com.fis.esme.language.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.4.1
 * Thu Nov 28 15:04:24 ICT 2013
 * Generated source version: 2.4.1
 */

@XmlRootElement(name = "updateAllLanguage", namespace = "http://language.esme.fis.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "updateAllLanguage", namespace = "http://language.esme.fis.com/", propOrder = {"arg0", "arg1", "arg2"})

public class UpdateAllLanguage {

    @XmlElement(name = "arg0")
    private com.fis.esme.persistence.EsmeLanguage arg0;
    @XmlElement(name = "arg1")
    private java.lang.String arg1;
    @XmlElement(name = "arg2")
    private java.lang.String arg2;

    public com.fis.esme.persistence.EsmeLanguage getArg0() {
        return this.arg0;
    }

    public void setArg0(com.fis.esme.persistence.EsmeLanguage newArg0)  {
        this.arg0 = newArg0;
    }

    public java.lang.String getArg1() {
        return this.arg1;
    }

    public void setArg1(java.lang.String newArg1)  {
        this.arg1 = newArg1;
    }

    public java.lang.String getArg2() {
        return this.arg2;
    }

    public void setArg2(java.lang.String newArg2)  {
        this.arg2 = newArg2;
    }

}

