
package com.fis.esme.messagecontent;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.1
 * 2013-12-02T16:41:09.057+07:00
 * Generated source version: 2.4.1
 * 
 */
public final class MessageContentTransferer_MessageContentTransfererPort_Client {

    private static final QName SERVICE_NAME = new QName("http://messagecontent.esme.fis.com/", "MessageContentTransfererService");

    private MessageContentTransferer_MessageContentTransfererPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = MessageContentTransfererService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        MessageContentTransfererService ss = new MessageContentTransfererService(wsdlURL, SERVICE_NAME);
        MessageContentTransferer port = ss.getMessageContentTransfererPort();  
        
       System.out.println("s>>>>>"+port.findAllWithoutParameter().size());

        System.exit(0);
    }

}
