package com.fis.esme.messagecontent;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.1
 * 2013-12-02T16:41:09.189+07:00
 * Generated source version: 2.4.1
 * 
 */
@WebService(targetNamespace = "http://messagecontent.esme.fis.com/", name = "MessageContentTransferer")
@XmlSeeAlso({ObjectFactory.class})
public interface MessageContentTransferer {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://messagecontent.esme.fis.com/", className = "com.fis.esme.messagecontent.Add")
    @WebMethod
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://messagecontent.esme.fis.com/", className = "com.fis.esme.messagecontent.AddResponse")
    public java.lang.Long add(
        @WebParam(name = "arg0", targetNamespace = "")
        com.fis.esme.persistence.EsmeMessageContent arg0
    ) throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "checkExisted", targetNamespace = "http://messagecontent.esme.fis.com/", className = "com.fis.esme.messagecontent.CheckExisted")
    @WebMethod
    @ResponseWrapper(localName = "checkExistedResponse", targetNamespace = "http://messagecontent.esme.fis.com/", className = "com.fis.esme.messagecontent.CheckExistedResponse")
    public int checkExisted(
        @WebParam(name = "arg0", targetNamespace = "")
        com.fis.esme.persistence.EsmeMessageContent arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "checkConstraints", targetNamespace = "http://messagecontent.esme.fis.com/", className = "com.fis.esme.messagecontent.CheckConstraints")
    @WebMethod
    @ResponseWrapper(localName = "checkConstraintsResponse", targetNamespace = "http://messagecontent.esme.fis.com/", className = "com.fis.esme.messagecontent.CheckConstraintsResponse")
    public boolean checkConstraints(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Long arg0
    );

    @RequestWrapper(localName = "delete", targetNamespace = "http://messagecontent.esme.fis.com/", className = "com.fis.esme.messagecontent.Delete")
    @WebMethod
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://messagecontent.esme.fis.com/", className = "com.fis.esme.messagecontent.DeleteResponse")
    public void delete(
        @WebParam(name = "arg0", targetNamespace = "")
        com.fis.esme.persistence.EsmeMessageContent arg0
    ) throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "count", targetNamespace = "http://messagecontent.esme.fis.com/", className = "com.fis.esme.messagecontent.Count")
    @WebMethod
    @ResponseWrapper(localName = "countResponse", targetNamespace = "http://messagecontent.esme.fis.com/", className = "com.fis.esme.messagecontent.CountResponse")
    public int count(
        @WebParam(name = "arg0", targetNamespace = "")
        com.fis.esme.persistence.EsmeMessageContent arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        boolean arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "deleteByMessageId", targetNamespace = "http://messagecontent.esme.fis.com/", className = "com.fis.esme.messagecontent.DeleteByMessageId")
    @WebMethod
    @ResponseWrapper(localName = "deleteByMessageIdResponse", targetNamespace = "http://messagecontent.esme.fis.com/", className = "com.fis.esme.messagecontent.DeleteByMessageIdResponse")
    public int deleteByMessageId(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findByMessageId", targetNamespace = "http://messagecontent.esme.fis.com/", className = "com.fis.esme.messagecontent.FindByMessageId")
    @WebMethod
    @ResponseWrapper(localName = "findByMessageIdResponse", targetNamespace = "http://messagecontent.esme.fis.com/", className = "com.fis.esme.messagecontent.FindByMessageIdResponse")
    public java.util.List<com.fis.esme.persistence.EsmeMessageContent> findByMessageId(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0
    ) throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findByMessageIdAndLanguageId", targetNamespace = "http://messagecontent.esme.fis.com/", className = "com.fis.esme.messagecontent.FindByMessageIdAndLanguageId")
    @WebMethod
    @ResponseWrapper(localName = "findByMessageIdAndLanguageIdResponse", targetNamespace = "http://messagecontent.esme.fis.com/", className = "com.fis.esme.messagecontent.FindByMessageIdAndLanguageIdResponse")
    public com.fis.esme.persistence.EsmeMessageContent findByMessageIdAndLanguageId(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        long arg1
    ) throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findAllWithoutParameter", targetNamespace = "http://messagecontent.esme.fis.com/", className = "com.fis.esme.messagecontent.FindAllWithoutParameter")
    @WebMethod
    @ResponseWrapper(localName = "findAllWithoutParameterResponse", targetNamespace = "http://messagecontent.esme.fis.com/", className = "com.fis.esme.messagecontent.FindAllWithoutParameterResponse")
    public java.util.List<com.fis.esme.persistence.EsmeMessageContent> findAllWithoutParameter() throws Exception_Exception;

    @RequestWrapper(localName = "update", targetNamespace = "http://messagecontent.esme.fis.com/", className = "com.fis.esme.messagecontent.Update")
    @WebMethod
    @ResponseWrapper(localName = "updateResponse", targetNamespace = "http://messagecontent.esme.fis.com/", className = "com.fis.esme.messagecontent.UpdateResponse")
    public void update(
        @WebParam(name = "arg0", targetNamespace = "")
        com.fis.esme.persistence.EsmeMessageContent arg0
    ) throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findAllWithOrderPaging", targetNamespace = "http://messagecontent.esme.fis.com/", className = "com.fis.esme.messagecontent.FindAllWithOrderPaging")
    @WebMethod
    @ResponseWrapper(localName = "findAllWithOrderPagingResponse", targetNamespace = "http://messagecontent.esme.fis.com/", className = "com.fis.esme.messagecontent.FindAllWithOrderPagingResponse")
    public java.util.List<com.fis.esme.persistence.EsmeMessageContent> findAllWithOrderPaging(
        @WebParam(name = "arg0", targetNamespace = "")
        com.fis.esme.persistence.EsmeMessageContent arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        boolean arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        int arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        int arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        boolean arg5
    ) throws Exception_Exception;
}
