
package com.fis.esme.groupsdt.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.4.1
 * Fri Oct 10 09:08:45 ICT 2014
 * Generated source version: 2.4.1
 */

@XmlRootElement(name = "findBySubGgroup", namespace = "http://groupsdt.esme.fis.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "findBySubGgroup", namespace = "http://groupsdt.esme.fis.com/")

public class FindBySubGgroup {

    @XmlElement(name = "arg0")
    private long arg0;

    public long getArg0() {
        return this.arg0;
    }

    public void setArg0(long newArg0)  {
        this.arg0 = newArg0;
    }

}

